---
permalink: install-ip/concept_considerations_mc_compliant_switches.html 
sidebar: sidebar 
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, requirements, compliant 
summary: 'Gli switch IP MetroCluster elencati come switch supportati in link:https://hwu.netapp.com/["NetApp Hardware Universe"^] E forniti da NetApp sono validati da NetApp. A partire da ONTAP 9.7, le configurazioni IP di MetroCluster possono utilizzare switch compatibili con MetroCluster. Si tratta di switch non validati da NetApp ma conformi alle specifiche NetApp. Tuttavia, NetApp non fornisce servizi di supporto, troubleshooting e/o configurazione per switch non validati.' 
---
= Considerazioni sull'utilizzo di switch compatibili con MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli switch IP MetroCluster elencati come switch supportati in link:https://hwu.netapp.com/["NetApp Hardware Universe"^] E forniti da NetApp sono validati da NetApp. A partire da ONTAP 9.7, le configurazioni IP di MetroCluster possono utilizzare switch compatibili con MetroCluster. Si tratta di switch non validati da NetApp ma conformi alle specifiche NetApp. Tuttavia, NetApp non fornisce servizi di supporto, troubleshooting e/o configurazione per switch non validati.



== Switch validati da NetApp

Uno switch è validato da NetApp se soddisfa tutti i seguenti requisiti:

* Lo switch viene fornito da NetApp come parte della configurazione IP di MetroCluster
* Lo switch è elencato nella link:https://hwu.netapp.com/["NetApp Hardware Universe"^] Come switch supportato in "MetroCluster-over-IP-Connections"
* Lo switch viene utilizzato solo per collegare controller IP MetroCluster e, in alcune configurazioni, shelf di dischi NS224
* Lo switch viene configurato utilizzando il file RCF (Reference Configuration file) fornito da NetApp


Qualsiasi switch che non soddisfa questi criteri è *non* uno switch validato da NetApp.



== Switch compatibili con MetroCluster

Uno switch compatibile con MetroCluster non è validato da NetApp, ma può essere utilizzato in una configurazione MetroCluster IP se soddisfa i requisiti e le linee guida di configurazione riportati di seguito.


NOTE: NetApp non fornisce servizi di supporto, troubleshooting e/o configurazione per switch MetroCluster non validati.



== Requisiti generali per gli switch compatibili con MetroCluster

I requisiti mostrano come configurare gli switch compatibili con MetroCluster senza utilizzare i file di configurazione di riferimento (RCF).

* Gli switch che si connettono ai nodi MetroCluster possono trasportare traffico non MetroCluster.
* Solo le piattaforme che forniscono porte dedicate per le interconnessioni cluster senza switch possono essere utilizzate con uno switch compatibile con MetroCluster. Le piattaforme come FAS2750 e AFF A220 non possono essere utilizzate perché il traffico MetroCluster e il traffico di interconnessione MetroCluster condividono le stesse porte di rete.
+
Lo switch compatibile con MetroCluster non deve essere utilizzato per le connessioni cluster locali.

* L'interfaccia IP di MetroCluster può essere collegata a qualsiasi porta dello switch che può essere configurata per soddisfare i requisiti.
* La velocità delle porte dello switch deve essere di 25 Gbps per le piattaforme FAS8200 e AFF A300 e di almeno 40 Gbps per tutte le altre piattaforme (40 Gbps o 100 Gbps).
* Sono necessari quattro switch IP, due per ciascun fabric dello switch.
* Gli ISL devono essere pari o superiori a 10 Gbps e devono essere dimensionati in modo appropriato per il carico sulla configurazione MetroCluster.
* La configurazione MetroCluster deve essere connessa a due reti. Le interfacce MetroCluster non possono essere collegate alla stessa rete o switch. Ciascun nodo MetroCluster deve essere collegato a due switch di rete.
* La rete deve soddisfare i seguenti requisiti:
+
** link:../install-ip/concept_considerations_isls.html#basic-metrocluster-isl-requirements["Requisiti ISL di base per MetroCluster"]
** link:../install-ip/concept_considerations_isls.html#isl-requirements-in-shared-layer-2-networks["Requisiti ISL nelle reti condivise Layer 2"]
** link:../install-ip/concept_considerations_layer_2.html#required-settings-on-intermediate-switches["Impostazioni richieste sugli switch intermedi"]


* Nelle configurazioni MetroCluster IP che utilizzano switch compatibili con MetroCluster, il ripristino di ONTAP 9.6 o versioni precedenti non è supportato.
* L'MTU di 9216 deve essere configurato su tutti gli switch che trasportano traffico IP MetroCluster.




== Requisiti di switch e cablaggio per switch compatibili con MetroCluster

* Gli switch devono supportare la classificazione QoS/traffico.
* Gli switch devono supportare la notifica esplicita di congestione (ECN).
* Gli switch devono supportare i criteri di bilanciamento del carico porta-vlan L4 per mantenere l'ordine lungo il percorso.
* Gli switch devono supportare il controllo di flusso L2 (L2FC).
* I cavi che collegano i nodi agli switch devono essere acquistati da NetApp. I cavi forniti devono essere supportati dal vendor dello switch.




== Limitazioni degli switch compatibili con MetroCluster

Non è possibile utilizzare alcuna configurazione o funzione che richiede la connessione delle connessioni cluster locali a uno switch. Ad esempio, le seguenti configurazioni e procedure non possono essere utilizzate con uno switch compatibile con MetroCluster:

* Configurazioni MetroCluster a otto nodi
* Transizione da configurazioni MetroCluster FC a MetroCluster IP
* Aggiornamento di una configurazione IP MetroCluster a quattro nodi




== Velocità di rete specifiche della piattaforma e modalità di porta dello switch per switch compatibili con MetroCluster

La seguente tabella fornisce velocità di rete specifiche della piattaforma e modalità delle porte dello switch per gli switch compatibili con MetroCluster. Configurare la modalità della porta dello switch come indicato nella tabella.


NOTE: Valori mancanti indicano che la piattaforma non può essere utilizzata con uno switch compatibile con MetroCluster.

|===


| Piattaforma | Velocità di rete (Gbps) | Switch port mode (modalità porta switch) 


 a| 
AFF A900
 a| 
100
 a| 
modalità trunk



 a| 
AFF A800
 a| 
40 o 100
 a| 
modalità di accesso



 a| 
AFF A700
 a| 
40
 a| 
modalità di accesso



 a| 
AFF A400
 a| 
40 o 100
 a| 
modalità trunk



 a| 
AFF A320
 a| 
100
 a| 
modalità di accesso



 a| 
AFF A300
 a| 
25
 a| 
modalità di accesso



 a| 
AFF A250
 a| 
-
 a| 
-



 a| 
AFF A220
 a| 
-
 a| 
-



 a| 
AFF A150
 a| 
-
 a| 
-



 a| 
FAS9000
 a| 
40
 a| 
modalità di accesso



 a| 
FAS9500
 a| 
100
 a| 
modalità trunk



 a| 
FAS8700
 a| 
100
 a| 
modalità trunk



 a| 
FAS8300
 a| 
40 o 100
 a| 
modalità trunk



 a| 
FAS8200
 a| 
25
 a| 
modalità di accesso



 a| 
FAS2750
 a| 
-
 a| 
-



 a| 
FAS500f
 a| 
-
 a| 
-

|===


== Presupposti per gli esempi

Gli esempi forniti sono validi per gli switch Cisco NX31xx e NX32xx. Se si utilizzano altri switch, questi comandi possono essere utilizzati come guida, ma i comandi potrebbero essere diversi. Se una funzione illustrata negli esempi non è disponibile sullo switch, significa che lo switch non soddisfa i requisiti minimi e non può essere utilizzato per implementare una configurazione MetroCluster. Ciò vale per tutti gli switch che collegano una configurazione MetroCluster e per tutti gli switch sul percorso tra questi switch.

* Le porte ISL sono 15 e 16 e funzionano a una velocità di 40 Gbps.
* La VLAN nella rete 1 è 10 e la VLAN nella rete 2 è 20. Alcuni esempi possono essere mostrati solo per una rete.
* L'interfaccia MetroCluster è collegata alla porta 9 di ogni switch e funziona a una velocità di 100 Gbps.
* Il contesto completo degli esempi non viene impostato o mostrato. Per eseguire i comandi, potrebbe essere necessario immettere ulteriori informazioni di configurazione, ad esempio il profilo, la VLAN o l'interfaccia.




== Configurazione generica dello switch

È necessario configurare una VLAN in ogni rete. L'esempio mostra come configurare una VLAN nella rete 10.

Esempio:

[listing]
----
# vlan 10
----
Il criterio di bilanciamento del carico deve essere impostato in modo da preservare l'ordine.

Esempio:

[listing]
----
# port-channel load-balance src-dst ip-l4port-vlan
----
È necessario configurare le mappe di accesso e di classe, che mappano il traffico RDMA e iSCSI alle classi appropriate.

Tutto il traffico TCP da e verso la porta 65200 viene mappato alla classe di storage (iSCSI). Tutto il traffico TCP da e verso la porta 10006 viene mappato alla classe RDMA.

Esempio:

[listing]
----

ip access-list storage
  10 permit tcp any eq 65200 any
  20 permit tcp any any eq 65200
ip access-list rdma
  10 permit tcp any eq 10006 any
  20 permit tcp any any eq 10006

class-map type qos match-all storage
  match access-group name storage
class-map type qos match-all rdma
  match access-group name rdma
----
È necessario configurare la policy di ingresso. La policy di ingresso mappa il traffico come classificato ai diversi gruppi COS. In questo esempio, il traffico RDMA viene mappato al gruppo COS 5 e il traffico iSCSI al gruppo COS 4.

Esempio:

[listing]
----

policy-map type qos MetroClusterIP_Ingress
class rdma
  set dscp 40
  set cos 5
  set qos-group 5
class storage
  set dscp 32
  set cos 4
  set qos-group 4
----
È necessario configurare la policy di uscita sullo switch. Il criterio di uscita associa il traffico alle code di uscita. In questo esempio, il traffico RDMA viene mappato alla coda 5 e il traffico iSCSI alla coda 4.

Esempio:

[listing]
----

policy-map type queuing MetroClusterIP_Egress
class type queuing c-out-8q-q7
  priority level 1
class type queuing c-out-8q-q6
  priority level 2
class type queuing c-out-8q-q5
  priority level 3
  random-detect threshold burst-optimized ecn
class type queuing c-out-8q-q4
  priority level 4
  random-detect threshold burst-optimized ecn
class type queuing c-out-8q-q3
  priority level 5
class type queuing c-out-8q-q2
  priority level 6
class type queuing c-out-8q-q1
  priority level 7
class type queuing c-out-8q-q-default
  bandwidth remaining percent 100
  random-detect threshold burst-optimized ecn
----
Potrebbe essere necessario configurare uno switch con traffico MetroCluster su un ISL ma che non si connette ad alcuna interfaccia MetroCluster. In questo caso, il traffico è già classificato e deve essere mappato solo alla coda appropriata. Nell'esempio seguente, tutto il traffico COS5 viene mappato alla classe RDMA e tutto il traffico COS4 viene mappato alla classe iSCSI. Si noti che questo avrà effetto su *tutto* il traffico COS5 e COS4, non solo sul traffico MetroCluster. Se si desidera mappare solo il traffico MetroCluster, è necessario utilizzare le mappe delle classi sopra indicate per identificare il traffico utilizzando i gruppi di accesso.

Esempio:

[listing]
----

class-map type qos match-all rdma
  match cos 5
class-map type qos match-all storage
  match cos 4
----


== Configurazione degli ISL

È possibile configurare una porta in modalità 'trunk' quando si imposta una VLAN consentita.

Sono disponibili due comandi, uno per *impostare* l'elenco delle VLAN consentite e uno per *aggiungere* all'elenco delle VLAN consentite esistenti.

È possibile *impostare* le VLAN consentite come mostrato nell'esempio.

Esempio:

[listing]
----
switchport trunk allowed vlan 10
----
È possibile *aggiungere* una VLAN all'elenco consentito, come mostrato nell'esempio.

Esempio:

[listing]
----
switchport trunk allowed vlan add 10
----
Nell'esempio, il canale porta 10 è configurato per la VLAN 10.

Esempio:

[listing]
----

interface port-channel10
switchport mode trunk
switchport trunk allowed vlan 10
mtu 9216
service-policy type queuing output MetroClusterIP_Egress
----
Le porte ISL devono essere configurate come parte di un port-channel e assegnate alle code di uscita come mostrato nell'esempio.

Esempio:

[listing]
----

interface eth1/15-16
switchport mode trunk
switchport trunk allowed vlan 10
no lldp transmit
no lldp receive
mtu 9216
channel-group 10 mode active
service-policy type queuing output MetroClusterIP_Egress
no shutdown
----


== Configurazione delle porte del nodo

Potrebbe essere necessario configurare la porta del nodo in modalità breakout. In questo esempio, le porte 25 e 26 sono configurate in modalità breakout 4 x 25 Gbps.

Esempio:

[listing]
----
interface breakout module 1 port 25-26 map 25g-4x
----
Potrebbe essere necessario configurare la velocità della porta dell'interfaccia MetroCluster. L'esempio mostra come configurare la velocità su "auto".

Esempio:

[listing]
----
speed auto
----
Nell'esempio seguente viene illustrato come correggere la velocità a 40 Gbps.

Esempio:

[listing]
----
speed 40000
----
Potrebbe essere necessario configurare l'interfaccia. Nell'esempio seguente, la velocità dell'interfaccia è impostata su "auto".

La porta è in modalità di accesso nella VLAN 10, MTU è impostato su 9216 e viene assegnato il criterio di ingresso MetroCluster.

Esempio:

[listing]
----

interface eth1/9
description MetroCluster-IP Node Port
speed auto
switchport access vlan 10
spanning-tree port type edge
spanning-tree bpduguard enable
mtu 9216
flowcontrol receive on
flowcontrol send on
service-policy type qos input MetroClusterIP_Ingress
no shutdown
----
Sulle porte a 25 Gbps, potrebbe essere necessario impostare l'opzione FEC su "Off", come mostrato nell'esempio.

Esempio:

[listing]
----
fec off
----

NOTE: Eseguire sempre questo comando *dopo* la configurazione dell'interfaccia. Potrebbe essere necessario inserire un modulo ricetrasmettitore per il funzionamento del comando.
