---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: Se la configurazione include aggregati senza mirror, è necessario essere consapevoli dei potenziali problemi di accesso dopo le operazioni di switchover. 
---
= Utilizzo di aggregati senza mirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la configurazione include aggregati senza mirror, è necessario essere consapevoli dei potenziali problemi di accesso dopo le operazioni di switchover.



== Considerazioni per gli aggregati senza mirror e gli spazi dei nomi gerarchici

Se si utilizzano spazi dei nomi gerarchici, è necessario configurare il percorso di giunzione in modo che tutti i volumi in quel percorso siano solo su aggregati mirrorati o solo su aggregati senza mirror. La configurazione di una combinazione di aggregati senza mirror e mirrorati nel percorso di giunzione potrebbe impedire l'accesso agli aggregati senza mirror dopo l'operazione di switchover.



== Considerazioni per aggregati senza mirror e volumi di metadati CRS e volumi root SVM di dati

Il volume di metadati del servizio di replica della configurazione (CRS) e i volumi radice SVM dei dati devono trovarsi su un aggregato mirrorato. Non è possibile spostare questi volumi in aggregato senza mirror. Se si trovano su aggregato senza mirror, le operazioni di switchover e switchback negoziate vengono vetoed. In questo caso, il comando MetroCluster check fornisce un avviso.



== Considerazioni per aggregati senza mirror e SVM

Le SVM devono essere configurate solo su aggregati mirrorati o solo su aggregati senza mirror. La configurazione di una combinazione di aggregati senza mirror e con mirroring può portare a un'operazione di switchover che supera i 120 secondi e a un'interruzione dei dati se gli aggregati senza mirror non vengono online.



== Considerazioni per aggregati senza mirror e SAN

Prima di ONTAP 9.9.1, un LUN non deve essere posizionato su un aggregato senza mirror. La configurazione di un LUN su un aggregato senza mirror può comportare un'operazione di switchover che supera i 120 secondi e un'interruzione dei dati.



== Considerazioni per l'aggiunta di shelf di storage per aggregati senza mirror


NOTE: Se si aggiungono shelf che verranno utilizzati per aggregati senza mirror in una configurazione MetroCluster IP, è necessario effettuare le seguenti operazioni:

. Prima di iniziare la procedura per aggiungere gli shelf, immettere il seguente comando:
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`

. Verificare che l'assegnazione automatica dei dischi sia disattivata:
+
`disk option show`

. Seguire i passaggi della procedura per aggiungere lo shelf.
. Assegnare manualmente tutti i dischi dal nuovo shelf al nodo che sarà proprietario dell'aggregato o degli aggregati senza mirror.
. Creare gli aggregati:
+
`storage aggregate create`

. Al termine della procedura, immettere il seguente comando:
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`

. Verificare che l'assegnazione automatica dei dischi sia attivata:
+
`disk option show`


