---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: Se la configurazione include aggregati senza mirror, è necessario essere consapevoli dei potenziali problemi di accesso dopo le operazioni di switchover. 
---
= Informazioni sugli aggregati non speculari nelle configurazioni IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la configurazione include aggregati senza mirror, è necessario essere consapevoli dei potenziali problemi di accesso dopo le operazioni di switchover.



== Aggregati non speculari e namespace gerarchici

Se si utilizzano spazi dei nomi gerarchici, è necessario configurare il percorso di giunzione in modo che tutti i volumi in quel percorso siano solo su aggregati mirrorati o solo su aggregati senza mirror. La configurazione di una combinazione di aggregati senza mirror e mirrorati nel percorso di giunzione potrebbe impedire l'accesso agli aggregati senza mirror dopo l'operazione di switchover.



== Aggregati non speculari e manutenzione che richiede l'interruzione dell'alimentazione

Se si esegue un passaggio negoziato per manutenzione che richiede l'interruzione dell'alimentazione in tutto il sito, è necessario innanzitutto disattivare manualmente tutti gli aggregati non sottoposti a mirroring di proprietà del sito interessato dal disastro.

Se non si mettono offline gli aggregati non mirrorati di proprietà del sito del disastro, i nodi del sito sopravvissuto potrebbero non funzionare a causa di errori multi-disco. Questo potrebbe verificarsi se gli aggregati non mirrorati commutati vanno offline o risultano mancanti a causa della perdita di connettività allo storage del sito del disastro in caso di interruzione di corrente o perdita di ISL.



== Aggregati non speculari, volumi di metadati CRS e volumi radice SVM di dati

Il volume di metadati del servizio di replica della configurazione (CRS) e i volumi radice SVM dei dati devono trovarsi su un aggregato mirrorato. Non è possibile spostare questi volumi in un aggregato senza mirror. Se si trovano su un aggregato non speculare, le operazioni di switchover e switchback negoziate vengono sottoposte a veto e  `metrocluster check` il comando restituisce un avviso.



== Aggregati non speculari e SVM

È consigliabile configurare le SVM solo su aggregati con mirroring o solo su aggregati senza mirroring. La configurazione delle SVM su una combinazione di aggregati con e senza mirroring può comportare un'operazione di switchover che dura più di 120 secondi. Ciò può causare un'interruzione dei dati se gli aggregati senza mirroring non sono online.



== Aggregati non speculari e SAN

Prima di ONTAP 9.9.1, una LUN non doveva essere posizionata su un aggregato non sottoposto a mirroring. La configurazione di un LUN su un aggregato senza mirror può comportare un'operazione di switchover che supera i 120 secondi e un'interruzione dei dati.



== Aggiungere ripiani di stoccaggio per aggregati non specchiati

Se si aggiungono ripiani e si desidera utilizzarli per aggregati non speculari in una configurazione IP MetroCluster , è necessario procedere come segue:

. Prima di iniziare la procedura per aggiungere gli shelf, immettere il seguente comando:
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`

. Verificare che l'assegnazione automatica dei dischi sia disattivata:
+
`disk option show`

. Seguire i passaggi della procedura per aggiungere lo shelf.
. Assegnare manualmente tutti i dischi dal nuovo shelf al nodo che sarà proprietario dell'aggregato o degli aggregati senza mirror.
. Creare gli aggregati:
+
`storage aggregate create`

. Al termine della procedura, immettere il seguente comando:
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`

. Verificare che l'assegnazione automatica dei dischi sia attivata:
+
`disk option show`


