---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: Le varie configurazioni MetroCluster presentano differenze chiave nei componenti richiesti. 
---
= Differenze tra ONTAP Mediator e MetroCluster Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.7, è possibile utilizzare il MAUSO (Automatic Unplanned switchover) assistito dal mediatore ONTAP nella configurazione IP di MetroCluster oppure il software MetroCluster Tiebreaker. Non è necessario utilizzare il software MAUSO o Tiebreaker; tuttavia, se si sceglie di non utilizzare uno di questi servizi, è necessario link:../disaster-recovery/concept_dr_workflow.html["eseguire un ripristino manuale"] in caso di disastro

Le diverse configurazioni MetroCluster eseguono lo switchover automatico in diverse circostanze:

* *Configurazioni MetroCluster FC che utilizzano la funzionalità AUSO (non presente nelle configurazioni MetroCluster IP)*
+
In queste configurazioni, AUSO viene avviato se i controller si guastano ma lo storage (e i bridge, se presenti) rimangono operativi.

* *Configurazioni IP MetroCluster che utilizzano il servizio ONTAP Mediator (ONTAP 9.7 e versioni successive)*
+
In queste configurazioni, MAUSO viene avviato nelle stesse circostanze di AUSO, come descritto sopra, e anche dopo un guasto completo del sito (controller, storage e switch).

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Scoprite in che modo ONTAP Mediator supporta lo switchover non pianificato automatico"].

* *Configurazioni MetroCluster IP o FC che utilizzano il software Tiebreaker in modalità attiva*
+
In queste configurazioni, il Tiebreaker avvia lo switchover non pianificato dopo un guasto completo del sito.

+
Prima di utilizzare il software Tiebreaker, consultare link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installazione e configurazione del software MetroCluster Tiebreaker"]





== Interoperabilità di ONTAP Mediator con altre applicazioni e appliance

Non è possibile utilizzare applicazioni o appliance di terze parti in grado di attivare uno switchover in combinazione con ONTAP Mediator. Inoltre, il monitoraggio di una configurazione MetroCluster con il software MetroCluster Tiebreaker non è supportato quando si utilizza ONTAP Mediator.

.Informazioni correlate
link:../manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#mediator-assisted-automatic-unplanned-switchover-in-metrocluster-ip-configurations["Ulteriori informazioni su un MAUSO nelle configurazioni IP di MetroCluster"].
