---
permalink: install-ip/concept-network-speeds-and-switchport-modes.html 
sidebar: sidebar 
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed, switch port mode 
summary: Se si utilizzano switch compatibili MetroCluster, è necessario conoscere le velocità di rete specifiche della piattaforma e i requisiti della modalità porta dello switch. 
---
= Velocità di rete specifiche della piattaforma ONTAP e modalità delle porte di commutazione per switch conformi a MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizzano switch compatibili MetroCluster, è necessario conoscere le velocità di rete specifiche della piattaforma e i requisiti della modalità porta dello switch.

La tabella seguente fornisce velocità di rete specifiche per piattaforma e modalità di porte switch per gli switch compatibili con MetroCluster. È necessario configurare la modalità della porta dello switch in base alla tabella.

[NOTE]
====
* Valori mancanti indicano che la piattaforma non può essere utilizzata con uno switch compatibile con MetroCluster.
* I sistemi AFF A30, AFF C30, AFF C60 e FAS50 richiedono un adattatore da QSFP a SFP+ sulla scheda del controller per supportare una velocità di rete di 25Gbps.


====
[cols="1,2,2"]
|===
| Piattaforma | Velocità di rete (Gbps) | Modalità porta switch 


 a| 
FAS9500

AFF A900

ASA A900
 a| 
100Gbps

40Gbps durante l'aggiornamento del PCM da FAS9000 o AFF A700
 a| 
Modalità trunk



 a| 
AFF C800

ASA C800

AFF A800

ASA A800
 a| 
40Gbps o 100Gbps
 a| 
Modalità di accesso



 a| 
FAS9000

AFF A700
 a| 
40Gbps
 a| 
Modalità di accesso



 a| 
FAS8300

AFF C400

ASA C400

AFF A400

ASA A400
 a| 
40Gbps o 100Gbps
 a| 
Modalità trunk



 a| 
AFF A320
 a| 
40Gbps o 100Gbps
 a| 
Modalità di accesso



 a| 
FAS8200

AFF A300
 a| 
25Gbps
 a| 
Modalità di accesso



 a| 
FAS500f

AFF C250

ASA C250

AFF A250

ASA A250
 a| 
-
 a| 
-



 a| 
FAS2750

AFF A220
 a| 
-
 a| 
-



 a| 
AFF A150

ASA A150
 a| 
-
 a| 
-



 a| 
AFF A20
 a| 
25Gbps
 a| 
Modalità trunk



 a| 
AFF A30
 a| 
25Gbps o 100Gbps
 a| 
Modalità trunk



 a| 
AFF C30
 a| 
25Gbps o 100Gbps
 a| 
Modalità trunk



 a| 
AFF C60
 a| 
25Gbps o 100Gbps
 a| 
Modalità trunk



 a| 
FAS50
 a| 
25Gbps o 100Gbps
 a| 
Modalità trunk



 a| 
AFF A50
 a| 
100Gbps
 a| 
Modalità trunk



 a| 
AFF A70
 a| 
100Gbps
 a| 
Modalità trunk



 a| 
AFF A90
 a| 
100Gbps
 a| 
Modalità trunk



 a| 
AFF A1K
 a| 
100Gbps
 a| 
Modalità trunk



 a| 
AFF C80
 a| 
100Gbps
 a| 
Modalità trunk



 a| 
FAS70
 a| 
100Gbps
 a| 
Modalità trunk



 a| 
FAS90
 a| 
100Gbps
 a| 
Modalità trunk

|===