---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: 'A partire da ONTAP 9.7, il servizio mediatore ONTAP può aiutare la configurazione IP di MetroCluster nell"esecuzione di uno switchover automatico non pianificato, fornendo un repository fisicamente separato per le informazioni di stato.' 
---
= Preparare l'installazione del servizio ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'ambiente deve soddisfare determinati requisiti.

I seguenti requisiti si applicano a un gruppo di disaster recovery (gruppo di DR). Scopri di più link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["Gruppi DR"].

* Se si prevede di aggiornare la versione di Linux, eseguire questa operazione prima di installare il servizio ONTAP Mediator più recente.
* Il servizio ONTAP Mediator e il software MetroCluster Tiebreaker non devono essere utilizzati con la stessa configurazione MetroCluster.
* Il supporto ONTAP deve essere installato su un host LINUX in una posizione separata dai siti MetroCluster.
+
La connettività tra il mediatore ONTAP e ciascun sito deve essere composta da due domini di guasto separati.

* Il servizio ONTAP può supportare fino a cinque configurazioni MetroCluster contemporaneamente.
* Lo switchover automatico non pianificato è supportato in ONTAP 9.7 e versioni successive.
* IPv6 non è supportato con ONTAP Mediator.




== Requisiti di rete per l'utilizzo di Mediator in una configurazione MetroCluster

Per installare il servizio ONTAP Mediator in una configurazione MetroCluster, è necessario assicurarsi che la configurazione soddisfi diversi requisiti di rete.

* Latenza
+
Latenza massima inferiore a 75 ms (RTT).

+
Il jitter non deve superare i 5 ms.

* MTU
+
La dimensione MTU deve essere di almeno 1400.

* Perdita di pacchetti
+
Per il traffico ICMP (Internet Control message Protocol) e TCP, la perdita di pacchetti deve essere inferiore al 0.01%.

* Larghezza di banda
+
Il collegamento tra il servizio Mediator e un gruppo DR deve avere almeno 20 Mbps di larghezza di banda.

* Connettività indipendente
+
È necessaria una connettività indipendente tra ciascun sito e il mediatore ONTAP. Un guasto in un sito non deve interrompere la connettività IP tra gli altri due siti non interessati.





== Requisiti dell'host per il mediatore ONTAP in una configurazione MetroCluster

È necessario assicurarsi che la configurazione soddisfi diversi requisiti dell'host.

* ONTAP Mediator deve essere installato in un sito esterno fisicamente separato dai due cluster ONTAP.
* Il mediatore ONTAP supporta un numero massimo di cinque configurazioni MetroCluster.
* Il mediatore ONTAP non richiede requisiti superiori a quelli minimi del sistema operativo host per CPU e memoria (RAM).
* Oltre ai requisiti minimi del sistema operativo host, devono essere disponibili almeno 30 GB di spazio su disco utilizzabile aggiuntivo.
+
** Ogni gruppo di DR richiede fino a 200 MB di spazio su disco.






== Requisiti del firewall per ONTAP Mediator

Il mediatore ONTAP utilizza una serie di porte per comunicare con servizi specifici.

Se si utilizza un firewall di terze parti:

* L'accesso HTTPS deve essere attivato.
* Deve essere configurato per consentire l'accesso alle porte 31784 e 3260.
+
Quando si utilizza il firewall predefinito Red Hat o CentOS, il firewall viene configurato automaticamente durante l'installazione di Mediator.



La tabella seguente elenca le porte che è necessario consentire nel firewall:

[NOTE]
====
* La porta iSCSI è richiesta solo in una configurazione IP MetroCluster.
* La porta 22/tcp non è necessaria per il normale funzionamento, ma è possibile attivarla temporaneamente per la manutenzione e disattivarla al termine della sessione di manutenzione.


====
|===


| Porta/servizi | Origine | Direzione | Destinazione | Scopo 


 a| 
22/tcp
 a| 
Host di gestione
 a| 
In entrata
 a| 
Mediatore ONTAP
 a| 
Gestione SSH / ONTAP Mediator



 a| 
31784/tcp
 a| 
LIF di gestione del cluster
 a| 
In entrata
 a| 
Server web di ONTAP Mediator
 a| 
API REST (HTTPS)



 a| 
3260/tcp
 a| 
LIF di gestione del cluster
 a| 
Bidirezionale
 a| 
Target iSCSI del mediatore ONTAP
 a| 
Connessione dati iSCSI per caselle postali

|===


== Linee guida per l'aggiornamento del mediatore ONTAP in una configurazione MetroCluster

Se si sta aggiornando il mediatore ONTAP, è necessario soddisfare i requisiti della versione Linux e seguire le linee guida per l'aggiornamento.

* Il servizio Mediator può essere aggiornato da una versione immediatamente precedente alla versione corrente.
* Tutte le versioni di Mediator sono supportate nelle configurazioni MetroCluster IP con ONTAP 9.7 o versioni successive.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installare o aggiornare il servizio di supporto ONTAP"^]



== Dopo l'aggiornamento

Una volta completato l'aggiornamento di Mediator e del sistema operativo, eseguire il `storage iscsi-initiator show` Per confermare che le connessioni del Mediator sono attive.
