---
permalink: install-ip/concept_considerations_tdm_encryption.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: 'È necessario tenere presente alcune considerazioni relative all"utilizzo delle apparecchiature di multiplazione nella configurazione IP di MetroCluster.' 
---
= Utilizzo di TDM/xWDM e apparecchiature di crittografia con configurazioni IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario tenere presente alcune considerazioni relative all'utilizzo delle apparecchiature di multiplazione nella configurazione IP di MetroCluster.

Queste considerazioni si applicano solo ai collegamenti e agli switch back-end MetroCluster diretti e dedicati, non ai collegamenti condivisi con traffico non MetroCluster.

Il tool Hardware Universe fornisce alcune note sui requisiti che le apparecchiature TDM/xWDM devono soddisfare per funzionare con una configurazione IP MetroCluster.

https://hwu.netapp.com["NetApp Hardware Universe"]



== Utilizzo della crittografia su dispositivi WDM o di crittografia esterni

Quando si utilizza la crittografia sui dispositivi WDM nella configurazione IP di MetroCluster, l'ambiente deve soddisfare i seguenti requisiti:

* I dispositivi di crittografia esterni o le apparecchiature DWDM devono essere stati certificati dal vendor con lo switch in questione.
+
La certificazione deve riguardare la modalità operativa (ad esempio trunking e crittografia).

* La latenza end-to-end e il jitter complessivi, inclusa la crittografia, non possono superare il valore massimo indicato nel IMT o nel presente documento.




== Considerazioni su SFP

Tutti gli SFP o i QSFP supportati dal fornitore dell'apparecchiatura sono supportati per gli MetroCluster ISL. È possibile acquistare SFP e QSFP da NetApp o dal fornitore di apparecchiature.



== Considerazioni per gli ISL

Gli ISL su un fabric devono essere tutti della stessa velocità e lunghezza.

Gli ISL su un fabric devono avere tutti la stessa topologia. Ad esempio, devono essere tutti collegamenti diretti o, se la configurazione utilizza WDM, tutti dovrebbero utilizzare WDM.

Se si condividono gli ISL con una rete non MetroCluster, seguire le linee guida della sezione link:concept_considerations_layer_2.html["Considerazioni per la condivisione di reti private Layer 2"].

La massima differenza di distanza supportata tra il fabric 1 e il fabric 2 è di 20 km
