---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: 'A partire da ONTAP 9.7, ONTAP Mediator può assistere la configurazione IP di MetroCluster nell"esecuzione di uno switchover automatico non pianificato fornendo un repository fisicamente separato per le informazioni sullo stato.' 
---
= Requisiti di installazione di ONTAP Mediator per le configurazioni IP di MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'ambiente deve soddisfare determinati requisiti.

I seguenti requisiti si applicano a un gruppo di disaster recovery (gruppo di DR). Scopri di più link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["Gruppi DR"].

* Se si prevede di aggiornare la versione di Linux, farlo prima di installare la versione più recente di ONTAP Mediator.
* I software ONTAP Mediator e MetroCluster Tiebreaker non devono essere utilizzati entrambi con la stessa configurazione MetroCluster.
* ONTAP Mediator deve essere installato su un host Linux in una posizione diversa dai siti MetroCluster.
+
La connettività tra il mediatore ONTAP e ciascun sito deve essere composta da due domini di guasto separati.

* Lo switchover automatico non pianificato è supportato in ONTAP 9.7 e versioni successive.
* A partire da ONTAP 9.19.1 e ONTAP Mediator 1.12, è possibile configurare un ONTAP Mediator che utilizza HTTPS per la comunicazione anziché iSCSI. Quando ONTAP Mediator è configurato con HTTPS, solo una configurazione IP di MetroCluster per istanza di ONTAP Mediator può essere monitorata. Per ulteriori informazioni, vedere <<Selezionare un protocollo di comunicazione per ONTAP Mediator>>.
* A partire da ONTAP 9.18.1 e ONTAP Mediator 1.11, una singola istanza di ONTAP Mediator configurata con iSCSI può gestire fino a dieci MetroCluster configurazioni contemporaneamente. In ONTAP 9.17.1 e ONTAP Mediator 1.10 e versioni precedenti, un'istanza ONTAP Mediator configurata con iSCSI può supportare fino a cinque MetroCluster configurazioni contemporaneamente.
* A partire da ONTAP 9.18.1, IPv6 è supportato per ONTAP Mediator 1.11 o versioni successive in una configurazione IP MetroCluster .




== Requisiti di rete per l'utilizzo di ONTAP Mediator in una configurazione MetroCluster

Per installare ONTAP Mediator in una configurazione MetroCluster, è necessario assicurarsi che la configurazione soddisfi diversi requisiti di rete.

* Latenza
+
Latenza massima inferiore a 75 ms (RTT).

+
Il jitter non deve superare i 5 ms.

* MTU
+
La dimensione MTU deve essere di almeno 1400.

* Perdita di pacchetti
+
Per il traffico ICMP (Internet Control message Protocol) e TCP, la perdita di pacchetti deve essere inferiore al 0.01%.

* Larghezza di banda
+
Il collegamento tra ONTAP Mediator e un gruppo DR deve avere almeno 20 Mbps di larghezza di banda.

* Connettività indipendente
+
È necessaria una connettività indipendente tra ciascun sito e il mediatore ONTAP. Un guasto in un sito non deve interrompere la connettività IP tra gli altri due siti non interessati.





== Requisiti host per ONTAP Mediator in una configurazione MetroCluster

È necessario assicurarsi che la configurazione soddisfi diversi requisiti dell'host.

* ONTAP Mediator deve essere installato in un sito esterno fisicamente separato dai due cluster ONTAP.
* Il mediatore ONTAP non richiede requisiti superiori a quelli minimi del sistema operativo host per CPU e memoria (RAM).
* Oltre ai requisiti minimi del sistema operativo host, devono essere disponibili almeno 30 GB di spazio su disco utilizzabile aggiuntivo.
+
** Ogni gruppo di DR richiede fino a 200 MB di spazio su disco.






== Selezionare un protocollo di comunicazione per ONTAP Mediator

Per impostazione predefinita, i nodi IP MetroCluster accedono alle LUN delle cassette postali di ONTAP Mediator utilizzando sessioni iSCSI. ONTAP Mediator si basa sul pacchetto SCST per fornire iSCSI. Le sessioni iSCSI vengono autenticate utilizzando il Challenge Handshake Authentication Protocol (CHAP) con una chiave precondivisa offuscata e generata automaticamente dalla macchina, ma non sono completamente crittografate.

A partire da ONTAP 9.19.1 e ONTAP Mediator 1.12, è possibile configurare un'istanza di ONTAP Mediator che utilizza HTTPS per la comunicazione anziché iSCSI. HTTPS è un protocollo di comunicazione sicuro che crittografa intere sessioni tramite SSL/TLS, offrendo una maggiore sicurezza rispetto a iSCSI.

È possibile configurare un ONTAP Mediator che utilizza HTTPS solo tramite la CLI. System Manager non è supportato.

[CAUTION]
====
* Se si configura ONTAP Mediator con HTTPS, una singola istanza di ONTAP Mediator può monitorare una sola configurazione IP MetroCluster. Il monitoraggio simultaneo di più configurazioni IP MetroCluster non è supportato.
* Se è necessario configurare ONTAP Mediator con HTTPS per monitorare più configurazioni IP di MetroCluster, è necessario configurare istanze separate di ONTAP Mediator per ciascuna configurazione IP di MetroCluster. È necessario valutare attentamente i requisiti per il proprio ambiente IP di MetroCluster prima di scegliere di configurare ONTAP Mediator con HTTPS per MetroCluster IP.
* Se si desidera utilizzare una singola istanza di ONTAP Mediator per monitorare più configurazioni IP MetroCluster, è necessario configurare ONTAP Mediator utilizzando iSCSI anziché HTTPS.


====
Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["Opzioni di installazione HTTPS e iSCSI per ONTAP Mediator"^].



== Linee guida per l'aggiornamento di ONTAP Mediator in una configurazione MetroCluster

Se si desidera aggiornare ONTAP Mediator, è necessario soddisfare i requisiti della versione Linux e seguire le linee guida per l'aggiornamento.

* ONTAP Mediator può essere aggiornato da una versione immediatamente precedente alla versione corrente.
* Tutte le versioni di Mediator sono supportate nelle configurazioni MetroCluster IP con ONTAP 9.7 o versioni successive.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installa o aggiorna ONTAP Mediator"^]



== Dopo l'aggiornamento

Una volta completato l'aggiornamento di Mediator e del sistema operativo, eseguire il `storage iscsi-initiator show` Per confermare che le connessioni del Mediator sono attive.
