---
sidebar: sidebar 
permalink: install-ip/set-up-mcc-site-system-manager.html 
keywords: system manager, metrocluster, set up, setup, start, initialize, cluster, config, nodes 
summary: A partire da ONTAP 9.8, è possibile utilizzare Gestione sistema per configurare un sito IP MetroCluster. 
---
= Configurare un sito IP MetroCluster con ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.8, è possibile utilizzare Gestione sistema per configurare un sito IP MetroCluster.

Un sito MetroCluster è costituito da due cluster. In genere, i cluster si trovano in posizioni geografiche diverse.

.Prima di iniziare
* Il sistema deve essere già installato e cablato in base a quanto fornito con il https://docs.netapp.com/us-en/ontap-systems/index.html["Istruzioni per l'installazione e la configurazione"^] sistema.
* Le interfacce di rete del cluster devono essere configurate su ciascun nodo di ciascun cluster per la comunicazione all'interno del cluster.




== Assegnare un indirizzo IP di gestione dei nodi



=== Sistema Windows

Collegare il computer Windows alla stessa subnet dei controller. In questo modo viene automaticamente assegnato al sistema un indirizzo IP di gestione dei nodi.

.Fasi
. Dal sistema Windows, aprire l'unità *Network* per rilevare i nodi.
. Fare doppio clic sul nodo per avviare l'installazione guidata del cluster.




=== Altri sistemi

È necessario configurare l'indirizzo IP di gestione dei nodi per uno dei nodi nel cluster. È possibile utilizzare questo indirizzo IP di gestione dei nodi per avviare la configurazione guidata del cluster.

Vedere link:https://docs.netapp.com/us-en/ontap/software_setup/task_create_the_cluster_on_the_first_node.html["Creazione del cluster sul primo nodo"^] per informazioni sull'assegnazione di un indirizzo IP di gestione dei nodi.



== Inizializzare e configurare il cluster

Per inizializzare il cluster, impostare una password amministrativa per il cluster e le reti di gestione dei nodi e del cluster. È inoltre possibile configurare servizi quali un DNS (Domain Name Server) per risolvere i nomi host e un server NTP per sincronizzare l'ora.

.Fasi
. In un browser Web, immettere l'indirizzo IP di gestione dei nodi configurato: "https://node-management-IP"[]
+
System Manager rileva automaticamente i nodi rimanenti nel cluster.

. Nella finestra *Initialize Storage System* (Inizializza sistema di storage), eseguire le seguenti operazioni:
+
.. Inserire i dati di configurazione della rete di gestione del cluster.
.. Inserire gli indirizzi IP di gestione dei nodi per tutti i nodi.
.. Fornire dettagli DNS.
.. Nella sezione *Altro*, selezionare la casella di controllo *Usa servizio ora (NTP)* per aggiungere i server di riferimento orario.




Quando si fa clic su *Submit* (Invia), attendere la creazione e la configurazione del cluster. Quindi, viene eseguito un processo di convalida.

.Quali sono le prossime novità?
Dopo aver impostato, inizializzato e configurato entrambi i cluster, eseguire la link:../install-ip/set-up-mcc-peering-system-manager.html["Impostare il peering IP MetroCluster"] procedura.



== Configurare ONTAP su un nuovo video del cluster

video::PiX41bospbQ[youtube,width=848,height=480]