---
sidebar: sidebar 
permalink: install-ip/set-up-mcc-peering-system-manager.html 
keywords: metrocluster, peer, peering, pair, pairing, configuration, config, mcc, HA 
summary: 'A partire da ONTAP 9.8, è possibile gestire le operazioni del sito IP di MetroCluster con System Manager. Questo implica la configurazione di due cluster e l"esecuzione del peering dei cluster.' 
---
= Configurare il peering IP MetroCluster con ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.8, è possibile gestire le operazioni di configurazione IP di MetroCluster con System Manager. Dopo aver configurato due cluster, è possibile impostare il peering tra di essi.

.Prima di iniziare
Configurare due cluster. Vedere la link:set-up-mcc-site-system-manager.html["Configurare un sito IP MetroCluster"] procedura.

Alcune fasi di questo processo vengono eseguite da diversi amministratori di sistema situati nei siti geografici di ciascun cluster. Ai fini della spiegazione di questo processo, i cluster sono denominati "cluster del sito A" e "cluster del sito B".



== Eseguire il processo di peering dal sito A

Questo processo viene eseguito da un amministratore di sistema presso il sito A.

.Fasi
. Accedere al sito Di Un cluster.
. In System Manager, selezionare *Dashboard* dalla colonna di navigazione a sinistra per visualizzare la panoramica del cluster.
+
La dashboard mostra i dettagli del cluster (sito A). Nella sezione *MetroCluster*, a sinistra viene visualizzato un cluster.

. Fare clic su *Attach Partner Cluster*.
. Inserire i dettagli delle interfacce di rete che consentono ai nodi del cluster del sito A di comunicare con i nodi del cluster del sito B.
. Fare clic su *Salva e continua*.
. Nella finestra *Allega cluster partner*, selezionare *non ho una passphrase*. In questo modo è possibile generare una passphrase.
. Copiare la passphrase generata e condividerla con l'amministratore di sistema nel sito B.
. Selezionare *Chiudi*.




== Eseguire il processo di peering dal sito B

Questo processo viene eseguito da un amministratore di sistema presso il sito B.

.Fasi
. Accedere al cluster del sito B.
. In System Manager, selezionare *Dashboard* per visualizzare la panoramica del cluster.
+
La dashboard mostra i dettagli del cluster (sito B). Nella sezione MetroCluster, il cluster del sito B viene visualizzato a sinistra.

. Fare clic su *Attach Partner Cluster* per avviare il processo di peering.
. Inserire i dettagli delle interfacce di rete che consentono ai nodi del cluster del sito B di comunicare con i nodi del cluster del sito A.
. Fare clic su *Salva e continua*.
. Nella finestra *Allega cluster partner*, selezionare *ho una passphrase*. In questo modo è possibile immettere la passphrase ricevuta dall'amministratore di sistema del sito A.
. Selezionare *Peer* per completare il processo di peering.


.Quali sono le prossime novità?
Una volta completato il processo di peering, sarà necessario configurare i cluster. Vedere link:configure-mcc-site-system-manager.html["Configurare un sito IP MetroCluster"].
