---
permalink: install-ip/switch-move-cluster-lifs.html 
sidebar: sidebar 
keywords: ip, switch, configuring, configure, factory defaults, cisco, MACsec encryption, 9336C, 9336, forward error correction, fec 
summary: 'Quando aggiorni il firmware dello switch o il file di configurazione di riferimento (RCF), sposti i LIF del cluster sullo switch partner per consentire operazioni del cluster senza interruzioni durante l"aggiornamento.' 
---
= Sposta i LIF del cluster prima di una modifica allo switch, RCF o firmware in una configurazione IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando sostituisci uno switch IP MetroCluster o cambi il firmware dello switch o il file di configurazione di riferimento (RCF), devi spostare i LIF del cluster sullo switch partner per consentire operazioni del cluster senza interruzioni.

.A proposito di questa attività
* Devi eseguire questa operazione prima di aggiornare o effettuare il downgrade del firmware dello switch, sostituire l'RCF dello switch o sostituire uno switch IP.
+

NOTE: Se stai configurando gli switch per la prima volta, puoi saltare questo passaggio a meno che tu non stia sostituendo uno switch.

* L'attività richiede di usare sia i comandi ONTAP che i comandi dello switch; si usano i comandi ONTAP, salvo diversa indicazione.
* Negli esempi utilizzati in questa procedura, stai eseguendo l'aggiornamento di IP_switch_A_1, quindi devi migrare i cluster LIF su IP_switch_A_2.
* Gli esempi di output dei comandi in questa procedura mostrano i dettagli relativi a uno switch Cisco. L'output può variare a seconda del modello e del produttore dello switch.


.Fasi
. Visualizza le porte del cluster connesse agli switch del cluster su ciascun nodo:
+
`network device-discovery show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node_A_2/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/18      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/18      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/2       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/2       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/10      N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/10      N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/5       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/6       N9K-C9372PX
node_A_2/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:02)
                                             Eth121/1/1        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:a0)
                                             Ethernet1/18      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:48)
                                             Ethernet1/18      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:28)
                                             Ethernet1/10      -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:80)
                                             Ethernet1/10      -
            e9a    local_network_switch (88:f0:31:86:fe:a8)
                                             Ethernet1/5       -
            e9b    local_network_switch (88:f0:31:86:fe:a9)
                                             Ethernet1/6       -
node_A_1/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/17      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/17      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/1       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/1       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/9       N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/9       N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/3       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/4       N9K-C9372PX
node_A_1/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:03)
                                             Eth121/1/2        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:9c)
                                             Ethernet1/17      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:44)
                                             Ethernet1/17      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:24)
                                             Ethernet1/9       -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:7c)
                                             Ethernet1/9       -
            e9a    local_network_switch (88:f0:31:86:fe:a6)
                                             Ethernet1/3       -
            e9b    local_network_switch (88:f0:31:86:fe:a7)
                                             Ethernet1/4       -
30 entries were displayed.
----
====
. Controlla lo stato amministrativo e operativo di ogni porta del cluster.
+
.. Verifica che tutte le porte del cluster siano attive e con stato integro:
+
`network port show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network port show -role cluster

Node: node_A_1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false

Node: node_A_2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false
4 entries were displayed.
----
====
.. Verifica che tutte le interfacce del cluster (LIF) siano sulla porta home:
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.

cluster_A::*>
----
====
.. Verifica che il cluster visualizzi le informazioni per entrambi gli switch del cluster:
+
`system switch ethernet show -is-monitoring-enabled-operational true`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> system switch ethernet show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
IP_switch_A_1               cluster-network    10.231.7.251     N9K-C9336C-FX2
     Serial Number: FDO26020KLJ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

IP_switch_A_2               cluster-network    10.231.7.252     N9K-C9336C-FX2
     Serial Number: FDO26020KGL
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

2 entries were displayed.

cluster_A::*>
----
====


. Disabilita il ripristino automatico sui cluster LIF. I cluster LIF eseguono il failover sullo switch del cluster partner e vi rimangono mentre esegui la procedura di aggiornamento sullo switch di destinazione:
+

NOTE: Se stai aggiornando il secondo fabric, puoi saltare questo passaggio e andare a <<shut-down-ports,Fase 4>>.

+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert false

Warning: Disabling the auto-revert feature of the cluster logical interface may
         effect the availability of your cluster network. Are you sure you want
         to continue? {y|n}: y

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.
----
====
. [[shut-down-ports]]Sul cluster switch IP_switch_A1, disattiva le porte collegate alle porte cluster dei nodi.
+
[role="tabbed-block"]
====
.Cisco
--
[listing]
----
IP_switch_A_1(config)# sh int eth1/1,eth1/2 brief

--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch
#
--------------------------------------------------------------------------------
Eth1/1          101     eth  access up      none                      40G(D) --
Eth1/2          101     eth  access up      none                      40G(D) --
IP_switch_A_1(config)#
IP_switch_A_1(config)# int eth1/1,eth1/2
IP_switch_A_1(config-if-range)# shut
IP_switch_A_1(config-if-range)#
----
--
.Broadcom
--
[listing]
----
IP_switch_A1(config)# interface eth1/1/1-2,eth1/7-8
IP_switch_A1(config-if-range)# shutdown
----
--
.NVIDIA
--
.. Visualizza le interfacce del cluster:
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ nv show interface
Interface    Admin Status  Oper Status  Speed  MTU    Type      Remote Host     Remote Port  Summary
-----------  ------------  -----------  -----  -----  --------  --------------  -----------  ---------
swp1         up            up           100G   9216   swp       cluster1         e1a
----
.. Spegni la porta dell'interfaccia del cluster:
+
[listing]
----
sudo python3 <RCF_name> runCmd swp1 state down
----


--
====
. [[verify_cluster_lif_migration]] Verifica che i cluster LIF siano stati migrati alle porte ospitate sullo switch del cluster IP_switch_A2. Questo potrebbe richiedere alcuni secondi.
+
`network interface show -role cluster`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4b     false
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4b     false
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.
----
====
. Verificare che il cluster funzioni correttamente:
+
`cluster show`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node_A_1             true    true          false
node_A_2             true    true          false
2 entries were displayed.
----
====


.Al termine
Dopo che le LIF del cluster sono state spostate sullo switch del partner, puoi seguire le procedure di configurazione standard secondo il tuo fornitore di switch per completare l'aggiornamento alla versione di firmware o RCF di destinazione:

* link:../install-ip/task_switch_config_broadcom.html["Configurare gli switch IP Broadcom"]
* link:../install-ip/task_switch_config_cisco.html["Configurare gli switch IP Cisco"]
* link:../install-ip/task_switch_config_nvidia.html["Configurare gli switch NVIDIA IP"]



NOTE: Dopo aver configurato gli switch nel primo fabric, devi ripetere i passaggi per spostare i LIF del cluster sul secondo fabric.
