---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: 'Se l"apparecchiatura non è già stata installata negli armadi, è necessario installarli in rack.' 
---
= Installare i componenti hardware di configurazione IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'apparecchiatura non è già stata installata negli armadi, è necessario installarli in rack.

.A proposito di questa attività
Questa attività deve essere eseguita su entrambi i siti MetroCluster.

.Fasi
. Pianificare il posizionamento dei componenti di MetroCluster.
+
Lo spazio rack dipende dal modello di piattaforma dei moduli controller, dai tipi di switch e dal numero di stack di shelf di dischi nella configurazione.

. Mettere a terra l'utente.
. Installare i moduli controller nel rack o nell'armadietto.
+
Seguire i passaggi per _Installare l'hardware_ nelle istruzioni _Installazione e configurazione_ per il modello di piattaforma in usolink:https://docs.netapp.com/us-en/ontap-systems/index.html["Documentazione dei sistemi hardware ONTAP"^] .

. Installare gli switch IP nel rack o nell'armadietto.
. Installare gli shelf di dischi, accenderli, quindi impostare gli ID degli shelf.
+
** È necessario spegnere e riaccendere ogni shelf di dischi.
** Per agevolare la risoluzione dei problemi, si consiglia di utilizzare ID shelf univoci per ogni shelf di dischi SAS all'interno di ciascun gruppo di DR MetroCluster.


+

IMPORTANT: Non utilizzare shelf di dischi per cavi destinati a contenere aggregati senza mirror. È necessario attendere la distribuzione degli shelf destinati agli aggregati senza mirror fino al completamento della configurazione MetroCluster e implementarli solo dopo l'utilizzo di `metrocluster modify -enable-unmirrored-aggr-deployment true` comando.


