---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: Il servizio ONTAP Mediator deve essere configurato sul nodo ONTAP per essere utilizzato in una configurazione IP MetroCluster. 
---
= Configurare il servizio ONTAP Mediator da una configurazione IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il servizio ONTAP Mediator deve essere configurato sul nodo ONTAP per essere utilizzato in una configurazione IP MetroCluster.

.Prima di iniziare
* Il mediatore ONTAP deve essere stato installato correttamente in una posizione di rete raggiungibile da entrambi i siti MetroCluster.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installare o aggiornare il servizio di supporto ONTAP"^]

* È necessario disporre dell'indirizzo IP dell'host che esegue il servizio ONTAP Mediator.
* È necessario disporre del nome utente e della password per il servizio di supporto ONTAP.
* Tutti i nodi della configurazione IP di MetroCluster devono essere in linea.



CAUTION: A partire da ONTAP 9.12.1, è possibile attivare la funzione di switchover forzato automatico di MetroCluster in una configurazione IP di MetroCluster. Questa funzione è un'estensione dello switchover non pianificato assistito dal mediatore. Prima di attivare questa funzione, consultare link:concept-risks-limitations-automatic-switchover.html["Rischi e limitazioni dell'utilizzo dello switchover forzato automatico di MetroCluster"].

.A proposito di questa attività
* Questa attività attiva lo switchover automatico non pianificato per impostazione predefinita.
* Questa attività può essere eseguita sull'interfaccia ONTAP di qualsiasi nodo della configurazione IP di MetroCluster.
* Una singola installazione del servizio ONTAP può essere configurata con un massimo di cinque configurazioni IP MetroCluster.


.Fasi
. Aggiungere il servizio ONTAP Mediator a ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address _ip-address-of-mediator-host_`

+

NOTE: Verranno richiesti nome utente e password per l'account utente amministratore di Mediator.

. Verificare che la funzione di switchover automatico sia attivata:
+
`metrocluster show`

. Verificare che Mediator sia in esecuzione.
+
.. Mostra i dischi virtuali di Mediator:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. Impostare la modalità dei privilegi su Advanced (avanzata):
+
`set advanced`

+
....
 cluster_A::> set advanced
....
.. Visualizzare gli iniziatori etichettati come mediatore:
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....


. Se si desidera configurare lo switchover forzato automatico di MetroCluster, eseguire il seguente comando: `metrocluster modify -allow-automatic-forced-switchover true`
+
Prima di attivare questa funzione, consultare link:concept-risks-limitations-automatic-switchover.html["Rischi e limitazioni dell'utilizzo dello switchover forzato automatico di MetroCluster"].

+
....
cluster_A::*> metrocluster modify -allow-automatic-forced-switchover true
....

