---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: È possibile rimuovere il mediatore ONTAP dalla configurazione IP di MetroCluster. 
---
= Rimuovere ONTAP Mediator da una configurazione IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile deconfigurare ONTAP Mediator dalla configurazione IP di MetroCluster.

.Prima di iniziare
È necessario aver installato e configurato correttamente ONTAP Mediator su un percorso di rete raggiungibile da entrambi i siti MetroCluster.

.Fasi
. Deconfigurare ONTAP Mediator utilizzando il seguente comando:
+
`metrocluster configuration-settings mediator remove`

+
Vengono richiesti il nome utente e la password per l'account utente admin di ONTAP Mediator.

+

NOTE: Se il mediatore ONTAP è inattivo,  `metrocluster configuration-settings mediator remove` Il comando richiede ancora di immettere il nome utente e la password per l'account utente amministratore di ONTAP Mediator e rimuove ONTAP Mediator dalla configurazione di MetroCluster.

+
.. Controllare se sono presenti dischi rotti utilizzando il seguente comando:
+
`disk show -broken`

+
*Esempio*

+
....
There are no entries matching your query.
....


. Se si utilizza un ONTAP Mediator che usa HTTPS per la comunicazione, eliminare i certificati CA dopo aver rimosso l'ONTAP Mediator:
+
.. Visualizza i certificati CA installati:
+
`security certificate show -common-name ONTAPMediatorCA`

.. Rimuovere i certificati root e intermedi installati:
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. Verificare che ONTAP Mediator sia stato rimosso dalla configurazione MetroCluster eseguendo il seguente comando su entrambi i cluster:
+
.. `metrocluster configuration-settings mediator show`
+
*Esempio*

+
[listing]
----
This table is currently empty.
----



