---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: È possibile scaricare e installare su un terzo sito il software MetroCluster Tiebreaker o, a partire da ONTAP 9.7, il ONTAP Mediator. 
---
= Configurazione del software MetroCluster Tiebreaker o ONTAP Mediator
:allow-uri-read: 


[role="lead"]
È possibile scaricare e installare su un terzo sito il software MetroCluster Tiebreaker o, a partire da ONTAP 9.7, il ONTAP Mediator.

.Prima di iniziare
È necessario disporre di un host Linux dotato di connettività di rete per entrambi i cluster nella configurazione MetroCluster. I requisiti specifici sono contenuti nella documentazione di MetroCluster Tiebreaker o ONTAP Mediator.

Se si effettua la connessione a un'istanza di Tiebreaker o ONTAP Mediator esistente, è necessario disporre del nome utente, della password e dell'indirizzo IP del servizio di spareggio o mediatore.

Se è necessario installare una nuova istanza di ONTAP Mediator, seguire le istruzioni per installare e configurare il software.

link:concept_mediator_requirements.html["Configurazione del servizio ONTAP Mediator per lo switchover automatico non pianificato"]

Se è necessario installare una nuova istanza del software Tiebreaker, seguire la link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["istruzioni per installare e configurare il software"].

.A proposito di questa attività
Non è possibile utilizzare sia il software MetroCluster Tiebreaker che il mediatore ONTAP con la stessa configurazione MetroCluster.

link:../install-ip/concept_considerations_mediator.html["Considerazioni sull'utilizzo di ONTAP Mediator o MetroCluster Tiebreaker"]

.Fase
. Configurare il servizio ONTAP Mediator o il software Tiebreaker:
+
** Se si utilizza un'istanza esistente del mediatore ONTAP, aggiungere il servizio del mediatore ONTAP a ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host`

** Se si utilizza il software Tiebreaker, fare riferimento a. link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Documentazione di Tiebreaker"].



