---
permalink: install-ip/task_sw_config_setup_ontap.html 
sidebar: sidebar 
keywords: metrocluster, ontap, setup 
summary: Dopo aver avviato ciascun nodo, viene richiesto di eseguire la configurazione di base del nodo e del cluster. Dopo aver configurato il cluster, tornare alla CLI ONTAP per creare aggregati e creare la configurazione MetroCluster. 
---
= Configurazione di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver avviato ciascun nodo, viene richiesto di eseguire la configurazione di base del nodo e del cluster. Dopo aver configurato il cluster, tornare alla CLI ONTAP per creare aggregati e creare la configurazione MetroCluster.

.Prima di iniziare
* La configurazione MetroCluster deve essere cablata.


Se è necessario eseguire il netboot dei nuovi controller, consultare link:../upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html#netboot-the-new-controllers["NetBoot i nuovi moduli controller"].

.A proposito di questa attività
Questa attività deve essere eseguita su entrambi i cluster nella configurazione MetroCluster.

.Fasi
. Accendere ciascun nodo nel sito locale, se non è già stato fatto, e lasciare che tutti i nodi si avviino completamente.
+
Se il sistema si trova in modalità manutenzione, è necessario eseguire il comando halt per uscire dalla modalità manutenzione, quindi eseguire il comando `boot_ontap` per avviare il sistema e accedere alla configurazione del cluster.

. Sul primo nodo di ciascun cluster, seguire le istruzioni per configurare il cluster.
+
.. Attivare lo strumento AutoSupport seguendo le istruzioni fornite dal sistema.
+
L'output dovrebbe essere simile a quanto segue:

+
[listing]
----
Welcome to the cluster setup wizard.

    You can enter the following commands at any time:
    "help" or "?" - if you want to have a question clarified,
    "back" - if you want to change previously answered questions, and
    "exit" or "quit" - if you want to quit the cluster setup wizard.
    Any changes you made before quitting will be saved.

    You can return to cluster setup at any time by typing "cluster setup".
    To accept a default or omit a question, do not enter a value.

    This system will send event messages and periodic reports to NetApp Technical
    Support. To disable this feature, enter
    autosupport modify -support disable
    within 24 hours.

    Enabling AutoSupport can significantly speed problem determination and
    resolution should a problem occur on your system.
    For further information on AutoSupport, see:
    http://support.netapp.com/autosupport/

    Type yes to confirm and continue {yes}: yes
.
.
.
----
.. Configurare l'interfaccia di gestione dei nodi rispondendo alle richieste.
+
I prompt sono simili ai seguenti:

+
[listing]
----
Enter the node management interface port [e0M]:
Enter the node management interface IP address: 172.17.8.229
Enter the node management interface netmask: 255.255.254.0
Enter the node management interface default gateway: 172.17.8.1
A node management interface on port e0M with IP address 172.17.8.229 has been created.
----
.. Creare il cluster rispondendo alle richieste.
+
I prompt sono simili ai seguenti:

+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
create


Do you intend for this node to be used as a single node cluster? {yes, no} [no]:
no

Existing cluster interface configuration found:

Port MTU IP Netmask
e0a 1500 169.254.18.124 255.255.0.0
e1a 1500 169.254.184.44 255.255.0.0

Do you want to use this configuration? {yes, no} [yes]: no

System Defaults:
Private cluster network ports [e0a,e1a].
Cluster port MTU values will be set to 9000.
Cluster interface IP addresses will be automatically generated.

Do you want to use these defaults? {yes, no} [yes]: no

Enter the cluster administrator's (username "admin") password:

Retype the password:


Step 1 of 5: Create a Cluster
You can type "back", "exit", or "help" at any question.

List the private cluster network ports [e0a,e1a]:
Enter the cluster ports' MTU size [9000]:
Enter the cluster network netmask [255.255.0.0]: 255.255.254.0
Enter the cluster interface IP address for port e0a: 172.17.10.228
Enter the cluster interface IP address for port e1a: 172.17.10.229
Enter the cluster name: cluster_A

Creating cluster cluster_A

Starting cluster support services ...

Cluster cluster_A has been created.
----
.. Aggiungere licenze, configurare una SVM di amministrazione cluster e immettere le informazioni DNS rispondendo alle richieste.
+
I prompt sono simili ai seguenti:

+
[listing]
----
Step 2 of 5: Add Feature License Keys
You can type "back", "exit", or "help" at any question.

Enter an additional license key []:


Step 3 of 5: Set Up a Vserver for Cluster Administration
You can type "back", "exit", or "help" at any question.


Enter the cluster management interface port [e3a]:
Enter the cluster management interface IP address: 172.17.12.153
Enter the cluster management interface netmask: 255.255.252.0
Enter the cluster management interface default gateway: 172.17.12.1

A cluster management interface on port e3a with IP address 172.17.12.153 has been created. You can use this address to connect to and manage the cluster.

Enter the DNS domain names: lab.netapp.com
Enter the name server IP addresses: 172.19.2.30
DNS lookup for the admin Vserver will use the lab.netapp.com domain.

Step 4 of 5: Configure Storage Failover (SFO)
You can type "back", "exit", or "help" at any question.


SFO will be enabled when the partner joins the cluster.


Step 5 of 5: Set Up the Node
You can type "back", "exit", or "help" at any question.

Where is the controller located []: svl
----
.. Abilitare il failover dello storage e configurare il nodo rispondendo alle richieste.
+
I prompt sono simili ai seguenti:

+
[listing]
----
Step 4 of 5: Configure Storage Failover (SFO)
You can type "back", "exit", or "help" at any question.


SFO will be enabled when the partner joins the cluster.


Step 5 of 5: Set Up the Node
You can type "back", "exit", or "help" at any question.

Where is the controller located []: site_A
----
.. Completare la configurazione del nodo, ma non creare aggregati di dati.
+
Puoi utilizzare ONTAP System Manager puntando il browser web all'indirizzo IP di gestione del cluster (\https://172.17.12.153)., Cluster Management)

+
https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/index.html["Gestione del cluster con Gestore di sistema (ONTAP 9.7 e versioni precedenti)"^]

+
https://docs.netapp.com/us-en/ontap/index.html#about-ontap-system-manager["Gestore di sistema ONTAP (versione 9.7 e successive)"]

.. Configurare il Service Processor (SP):
+
link:https://docs.netapp.com/us-en/ontap/system-admin/sp-bmc-network-config-concept.html["Configurare la rete SP/BMC"^]

+
link:https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_service_processors.html["Utilizza un Service Processor con Gestione di sistema - ONTAP 9.7 e versioni precedenti"^]



. Avviare il controller successivo e unirsi al cluster, seguendo le istruzioni.
. Verificare che i nodi siano configurati in modalità ad alta disponibilità:
+
`storage failover show -fields mode`

+
In caso contrario, è necessario configurare la modalità ha su ciascun nodo, quindi riavviare i nodi:

+
`storage failover modify -mode ha -node localhost`

+
[]
====

NOTE: Lo stato di configurazione previsto di ha e failover dello storage è il seguente:

** La modalità HA è configurata ma il failover dello storage non è abilitato.
** La funzionalità HA Takeover è disattivata.
** Le interfacce HA sono offline.
** La modalità HA, il failover dello storage e le interfacce vengono configurati più avanti nel processo.


====
. Verificare che siano configurate quattro porte come interconnessioni cluster:
+
`network port show`

+
Le interfacce IP di MetroCluster non sono attualmente configurate e non vengono visualizzate nell'output del comando.

+
L'esempio seguente mostra due porte del cluster su Node_A_1:

+
[listing]
----
cluster_A::*> network port show -role cluster



Node: node_A_1

                                                                       Ignore

                                                  Speed(Mbps) Health   Health

Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status

--------- ------------ ---------------- ---- ---- ----------- -------- ------

e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false

e4e       Cluster      Cluster          up   9000  auto/40000 healthy  false


Node: node_A_2

                                                                       Ignore

                                                  Speed(Mbps) Health   Health

Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status

--------- ------------ ---------------- ---- ---- ----------- -------- ------

e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false

e4e       Cluster      Cluster          up   9000  auto/40000 healthy  false


4 entries were displayed.
----
. Ripetere questi passaggi sul cluster partner.


.Cosa fare in seguito
Tornare all'interfaccia della riga di comando di ONTAP e completare la configurazione di MetroCluster eseguendo le seguenti operazioni.
