---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: 'Per l"utilizzo in una configurazione IP MetroCluster, ONTAP Mediator deve essere configurato sul nodo ONTAP.' 
---
= Impostare ONTAP Mediator per una configurazione IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare ONTAP Mediator sul nodo ONTAP per utilizzarlo in una configurazione IP MetroCluster .

.Prima di iniziare
* ONTAP Mediator deve essere stato installato correttamente in una posizione di rete raggiungibile da entrambi i siti MetroCluster.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installa o aggiorna ONTAP Mediator"^]

* È necessario disporre dell'indirizzo IP dell'host su cui è in esecuzione ONTAP Mediator.
* È necessario disporre del nome utente e della password per ONTAP Mediator.
* Tutti i nodi della configurazione IP di MetroCluster devono essere in linea.



CAUTION: A partire da ONTAP 9.12.1, è possibile attivare la funzione di switchover forzato automatico di MetroCluster in una configurazione IP di MetroCluster. Questa funzione è un'estensione dello switchover non pianificato assistito dal mediatore. Prima di attivare questa funzione, consultare la link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["Rischi e limitazioni dell'utilizzo dello switchover forzato automatico di MetroCluster"].

.A proposito di questa attività
* Questa attività attiva lo switchover automatico non pianificato per impostazione predefinita.
* Questa attività può essere eseguita sull'interfaccia ONTAP di qualsiasi nodo della configurazione IP di MetroCluster.
* A partire da ONTAP 9.18.1 e ONTAP Mediator 1.11, una singola istanza ONTAP Mediator può gestire fino a dieci configurazioni MetroCluster contemporaneamente.  Nelle versioni precedenti, ONTAP Mediator può supportare fino a cinque configurazioni MetroCluster contemporaneamente.


.Fasi
. Aggiungere ONTAP Mediator a ONTAP.  I passaggi variano a seconda che si voglia utilizzare un indirizzo IPv4 o IPv6.
+
[NOTE]
====
** Per utilizzare IPv6 è necessario eseguire ONTAP 9.18.1 o versione successiva e ONTAP Mediator 1.11 o versione successiva.
** Se si abilita IPv6 su un cluster, non sarà possibile disabilitarlo in seguito.


====
+
[role="tabbed-block"]
====
.Utilizzare IPv4
--
.. Eseguire il seguente comando per aggiungere ONTAP Mediator:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address>`

+

NOTE: Ti verrà richiesto di inserire il nome utente e la password per l'account utente amministratore del Mediatore.



--
.Utilizzare IPv6
--
.. Eseguire il seguente comando su entrambi i cluster:
+
`network options ipv6 modify -enabled true`

.. Configurare l'indirizzo IP node-mgmt con indirizzi IPv6 su tutti e quattro i nodi.
.. Aggiungere il mediatore ONTAP :
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address>`

+

NOTE: Ti verrà richiesto di inserire il nome utente e la password per l'account utente amministratore del Mediatore.



--
====
. Verificare che la funzione di switchover automatico sia attivata:
+
`metrocluster show`

. Verificare che Mediator sia in esecuzione.
+
.. Mostra i dischi virtuali di Mediator:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. Impostare la modalità dei privilegi su Advanced (avanzata):
+
`set advanced`

+
....
 cluster_A::> set advanced
....
.. Visualizzare gli iniziatori etichettati come mediatore:
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. Verificare lo stato del dominio dell'errore di switchover non pianificato automatico (AURO):
+
`metrocluster show`

+

NOTE: L'output di esempio riportato di seguito è valido per ONTAP 9.13.1 e versioni successive. Per ONTAP 9.12.1 e versioni precedenti, lo stato del dominio di errore AUSO dovrebbe essere `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----


. In alternativa, configurare lo switchover forzato automatico MetroCluster.
+
È possibile utilizzare il seguente comando solo a livello di privilegi avanzati.

+

IMPORTANT: Prima di utilizzare questo comando, rivedere la link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["Rischi e limitazioni dell'utilizzo dello switchover forzato automatico di MetroCluster"].

+
`metrocluster modify -allow-auto-forced-switchover true`

+
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

