---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: 'Se l"apparecchiatura non è già stata installata negli armadi, è necessario installarli in rack.' 
---
= Scaffalatura dei componenti hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'apparecchiatura non è già stata installata negli armadi, è necessario installarli in rack.

.A proposito di questa attività
Questa attività deve essere eseguita su entrambi i siti MetroCluster.

.Fasi
. Pianificare il posizionamento dei componenti di MetroCluster.
+
Lo spazio rack dipende dal modello di piattaforma dei moduli controller, dai tipi di switch e dal numero di stack di shelf di dischi nella configurazione.

. Mettere a terra l'utente.
. Installare i moduli controller nel rack o nell'armadietto.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["Istruzioni per l'installazione e la configurazione dei sistemi AFF A220/FAS2700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2870798["Istruzioni per l'installazione e la configurazione dei sistemi AFF A250"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["Istruzioni per l'installazione e la configurazione dei sistemi AFF A300"^]

+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["Sistemi AFF A320: Installazione e configurazione"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2858854["Istruzioni per l'installazione e la configurazione dei sistemi AFF A400"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2873445["Istruzioni per l'installazione e la configurazione dei sistemi AFF A700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["Istruzioni per l'installazione e la configurazione dei sistemi AFF A800"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2872833["Istruzioni per l'installazione e la configurazione dei sistemi FAS500f"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["Istruzioni per l'installazione e la configurazione dei sistemi FAS8200"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2858856["Istruzioni per l'installazione e la configurazione dei sistemi FAS8300 e FAS8700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874463["Istruzioni per l'installazione e la configurazione dei sistemi FAS9000"^]



. Installare gli switch IP nel rack o nell'armadietto.
. Installare gli shelf di dischi, accenderli, quindi impostare gli ID degli shelf.
+
** È necessario spegnere e riaccendere ogni shelf di dischi.
** Per agevolare la risoluzione dei problemi, si consiglia di utilizzare ID shelf univoci per ogni shelf di dischi SAS all'interno di ciascun gruppo di DR MetroCluster.


+

IMPORTANT: Non utilizzare shelf di dischi per cavi destinati a contenere aggregati senza mirror. È necessario attendere la distribuzione degli shelf destinati agli aggregati senza mirror fino al completamento della configurazione MetroCluster e implementarli solo dopo l'utilizzo di `metrocluster modify -enable-unmirrored-aggr-deployment true` comando.


