---
permalink: install-ip/task_sw_config_verify_haconfig.html 
sidebar: sidebar 
keywords: metrocluster, ha-config, mccip, haconfig, verify, high-availability 
summary: In una configurazione MetroCluster IP non preconfigurata in fabbrica, è necessario verificare che lo stato ha-config dei componenti del controller e del telaio sia impostato su mccip in modo che si avviino correttamente. Per i sistemi ricevuti dalla fabbrica, questo valore è preconfigurato e non è necessario verificarlo. 
---
= Verifica dello stato ha-config dei componenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In una configurazione IP di MetroCluster, è necessario verificare che lo stato ha-config del controller e dei componenti del telaio sia impostato su "mccip" in modo che si avviino correttamente. Sebbene questo valore debba essere preconfigurato nei sistemi ricevuti in fabbrica, è comunque necessario verificare l'impostazione prima di procedere.

[CAUTION]
====
Se lo stato ha del modulo controller e del telaio non è corretto, non è possibile configurare il MetroCluster senza reinizializzare il nodo. È necessario correggere l'impostazione utilizzando questa procedura, quindi inizializzare il sistema utilizzando una delle seguenti procedure:

* In una configurazione IP di MetroCluster, seguire la procedura descritta in link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_restore_defaults.html["Ripristinare le impostazioni predefinite del sistema su un modulo controller"].
* In una configurazione MetroCluster FC, seguire la procedura descritta in link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#restoring-system-defaults-and-configuring-the-hba-type-on-a-controller-module["Ripristinare le impostazioni predefinite del sistema e configurare il tipo di HBA su un modulo controller"].


====
.Prima di iniziare
Verificare che il sistema sia in modalità di manutenzione.

.Fasi
. In modalità Maintenance (manutenzione), visualizzare lo stato ha del modulo controller e dello chassis:
+
`ha-config show`

+
Lo stato ha corretto dipende dalla configurazione di MetroCluster.

+
|===


| Tipo di configurazione di MetroCluster | Stato HA per tutti i componenti... 


 a| 
Configurazione FC MetroCluster a otto o quattro nodi
 a| 
mcc



 a| 
Configurazione MetroCluster FC a due nodi
 a| 
mcc-2n



 a| 
Configurazione IP MetroCluster a otto o quattro nodi
 a| 
mccip

|===
. Se lo stato del sistema visualizzato del controller non è corretto, impostare lo stato ha corretto per la configurazione sul modulo controller:
+
|===


| Tipo di configurazione di MetroCluster | Comando 


 a| 
Configurazione FC MetroCluster a otto o quattro nodi
 a| 
`ha-config modify controller mcc`



 a| 
Configurazione MetroCluster FC a due nodi
 a| 
`ha-config modify controller mcc-2n`



 a| 
Configurazione IP MetroCluster a otto o quattro nodi
 a| 
`ha-config modify controller mccip`

|===
. Se lo stato del sistema visualizzato del telaio non è corretto, impostare lo stato ha corretto per la configurazione sul telaio:
+
|===


| Tipo di configurazione di MetroCluster | Comando 


 a| 
Configurazione FC MetroCluster a otto o quattro nodi
 a| 
`ha-config modify chassis mcc`



 a| 
Configurazione MetroCluster FC a due nodi
 a| 
`ha-config modify chassis mcc-2n`



 a| 
Configurazione IP MetroCluster a otto o quattro nodi
 a| 
`ha-config modify chassis mccip`

|===
. Avviare il nodo su ONTAP:
+
`boot_ontap`

. Ripetere l'intera procedura per verificare lo stato ha su ogni nodo nella configurazione MetroCluster.

