---
permalink: disaster-recovery/task_delete_plexes_mcip.html 
sidebar: sidebar 
keywords: deleting, delete, fail, plex, own 
summary: È necessario accendere gli shelf di dischi e i componenti degli switch IP MetroCluster nel sito di emergenza. 
---
= Eliminazione dei plex guasti di proprietà del sito sopravvissuto (configurazioni IP MetroCluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo la sostituzione dell'hardware e l'assegnazione dei dischi, è necessario eliminare i plessi remoti guasti di proprietà dei nodi del sito sopravvissuti ma che si trovano nel sito di emergenza.

.A proposito di questa attività
Questi passaggi vengono eseguiti sul cluster esistente.

.Fasi
. Identificare gli aggregati locali:
`storage aggregate show -is-home true`
+
[listing]
----
cluster_B::> storage aggregate show -is-home true

cluster_B Aggregates:
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
node_B_1_aggr0 1.49TB  74.12GB 95% online       1 node_B_1         raid4,
                                                                   mirror
                                                                   degraded
node_B_2_aggr0 1.49TB  74.12GB 95% online       1 node_B_2         raid4,
                                                                   mirror
                                                                   degraded
node_B_1_aggr1 2.99TB  2.88TB   3% online      15 node_B_1         raid_dp,
                                                                   mirror
                                                                   degraded
node_B_1_aggr2 2.99TB  2.91TB   3% online      14 node_B_1         raid_tec,
                                                                   mirror
                                                                   degraded
node_B_2_aggr1 2.95TB  2.80TB   5% online      37 node_B_2         raid_dp,
                                                                   mirror
                                                                   degraded
node_B_2_aggr2 2.99TB  2.87TB   4% online      35 node_B_2         raid_tec,
                                                                   mirror
                                                                   degraded
6 entries were displayed.

cluster_B::>
----
. Identificare i plessi remoti guasti:
+
`storage aggregate plex show`

+
Nell'esempio riportato di seguito vengono indicati i plex remoti (non plex0) con stato "failed" (non riuscito):

+
[listing]
----
cluster_B::> storage aggregate plex show -fields aggregate,status,is-online,Plex,pool
aggregate    plex  status        is-online pool
------------ ----- ------------- --------- ----
node_B_1_aggr0 plex0 normal,active true     0
node_B_1_aggr0 plex4 failed,inactive false  - <<<<---Plex at remote site
node_B_2_aggr0 plex0 normal,active true     0
node_B_2_aggr0 plex4 failed,inactive false  - <<<<---Plex at remote site
node_B_1_aggr1 plex0 normal,active true     0
node_B_1_aggr1 plex4 failed,inactive false  - <<<<---Plex at remote site
node_B_1_aggr2 plex0 normal,active true     0
node_B_1_aggr2 plex1 failed,inactive false  - <<<<---Plex at remote site
node_B_2_aggr1 plex0 normal,active true     0
node_B_2_aggr1 plex4 failed,inactive false  - <<<<---Plex at remote site
node_B_2_aggr2 plex0 normal,active true     0
node_B_2_aggr2 plex1 failed,inactive false  - <<<<---Plex at remote site
node_A_1_aggr1 plex0 failed,inactive false  -
node_A_1_aggr1 plex4 normal,active true     1
node_A_1_aggr2 plex0 failed,inactive false  -
node_A_1_aggr2 plex1 normal,active true     1
node_A_2_aggr1 plex0 failed,inactive false  -
node_A_2_aggr1 plex4 normal,active true     1
node_A_2_aggr2 plex0 failed,inactive false  -
node_A_2_aggr2 plex1 normal,active true     1
20 entries were displayed.

cluster_B::>
----
. Portare offline ciascuno dei plessi guasti, quindi eliminarli:
+
.. Take offline the failed plex:
+
`storage aggregate plex offline -aggregate aggregate-name -plex plex-id`

+
L'esempio seguente mostra l'aggregato "Node_B_2_aggr1/plex1" che viene portato offline:

+
[listing]
----
cluster_B::> storage aggregate plex offline -aggregate node_B_1_aggr0 -plex plex4

Plex offline successful on plex: node_B_1_aggr0/plex4
----
.. Eliminare il plesso guasto:
+
`storage aggregate plex delete -aggregate aggregate-name -plex plex-id`

+
Quando richiesto, è possibile distruggere il plex.

+
Nell'esempio seguente viene mostrato il nodo plex_B_2_aggr1/plex1 cancellato.

+
[listing]
----
cluster_B::> storage aggregate plex delete -aggregate  node_B_1_aggr0 -plex plex4

Warning: Aggregate "node_B_1_aggr0" is being used for the local management root
         volume or HA partner management root volume, or has been marked as
         the aggregate to be used for the management root volume after a
         reboot operation. Deleting plex "plex4" for this aggregate could lead
         to unavailability of the root volume after a disaster recovery
         procedure. Use the "storage aggregate show -fields
         has-mroot,has-partner-mroot,root" command to view such aggregates.

Warning: Deleting plex "plex4" of mirrored aggregate "node_B_1_aggr0" on node
         "node_B_1" in a MetroCluster configuration will disable its
         synchronous disaster recovery protection. Are you sure you want to
         destroy this plex? {y|n}: y
[Job 633] Job succeeded: DONE

cluster_B::>
----


+
È necessario ripetere questi passaggi per ciascuno dei plessi guasti.

. Verificare che i plessi siano stati rimossi:
+
`storage aggregate plex show -fields aggregate,status,is-online,plex,pool`

+
[listing]
----
cluster_B::> storage aggregate plex show -fields aggregate,status,is-online,Plex,pool
aggregate    plex  status        is-online pool
------------ ----- ------------- --------- ----
node_B_1_aggr0 plex0 normal,active true     0
node_B_2_aggr0 plex0 normal,active true     0
node_B_1_aggr1 plex0 normal,active true     0
node_B_1_aggr2 plex0 normal,active true     0
node_B_2_aggr1 plex0 normal,active true     0
node_B_2_aggr2 plex0 normal,active true     0
node_A_1_aggr1 plex0 failed,inactive false  -
node_A_1_aggr1 plex4 normal,active true     1
node_A_1_aggr2 plex0 failed,inactive false  -
node_A_1_aggr2 plex1 normal,active true     1
node_A_2_aggr1 plex0 failed,inactive false  -
node_A_2_aggr1 plex4 normal,active true     1
node_A_2_aggr2 plex0 failed,inactive false  -
node_A_2_aggr2 plex1 normal,active true     1
14 entries were displayed.

cluster_B::>
----
. Identificare gli aggregati di switchover:
+
`storage aggregate show -is-home false`

+
È inoltre possibile utilizzare `storage aggregate plex show -fields aggregate,status,is-online,plex,pool` comando per identificare aggregati di switchover plex 0. Avranno lo stato "failed, inactive" (non riuscito, inattivo).

+
I seguenti comandi mostrano quattro aggregati di switchover:

+
** Node_A_1_aggr1
** Node_A_1_aggr2
** Node_A_2_aggr1
** Node_A_2_aggr2


+
[listing]
----
cluster_B::> storage aggregate show -is-home false

cluster_A Switched Over Aggregates:
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
node_A_1_aggr1 2.12TB  1.88TB   11% online      91 node_B_1        raid_dp,
                                                                   mirror
                                                                   degraded
node_A_1_aggr2 2.89TB  2.64TB    9% online      90 node_B_1        raid_tec,
                                                                   mirror
                                                                   degraded
node_A_2_aggr1 2.12TB  1.86TB   12% online      91 node_B_2        raid_dp,
                                                                   mirror
                                                                   degraded
node_A_2_aggr2 2.89TB  2.64TB    9% online      90 node_B_2        raid_tec,
                                                                   mirror
                                                                   degraded
4 entries were displayed.

cluster_B::>
----
. Identificare i plessi di switchover:
+
`storage aggregate plex show -fields aggregate,status,is-online,Plex,pool`

+
Si desidera identificare i plessi con lo stato "failed, inactive" (non riuscito, inattivo).

+
I seguenti comandi mostrano quattro aggregati di switchover:

+
[listing]
----
cluster_B::> storage aggregate plex show -fields aggregate,status,is-online,Plex,pool
aggregate    plex  status        is-online pool
------------ ----- ------------- --------- ----
node_B_1_aggr0 plex0 normal,active true     0
node_B_2_aggr0 plex0 normal,active true     0
node_B_1_aggr1 plex0 normal,active true     0
node_B_1_aggr2 plex0 normal,active true     0
node_B_2_aggr1 plex0 normal,active true     0
node_B_2_aggr2 plex0 normal,active true     0
node_A_1_aggr1 plex0 failed,inactive false  -  <<<<-- Switched over aggr/Plex0
node_A_1_aggr1 plex4 normal,active true     1
node_A_1_aggr2 plex0 failed,inactive false  -  <<<<-- Switched over aggr/Plex0
node_A_1_aggr2 plex1 normal,active true     1
node_A_2_aggr1 plex0 failed,inactive false  -  <<<<-- Switched over aggr/Plex0
node_A_2_aggr1 plex4 normal,active true     1
node_A_2_aggr2 plex0 failed,inactive false  -  <<<<-- Switched over aggr/Plex0
node_A_2_aggr2 plex1 normal,active true     1
14 entries were displayed.

cluster_B::>
----
. Eliminare il plesso guasto:
+
`storage aggregate plex delete -aggregate node_A_1_aggr1 -plex plex0`

+
Quando richiesto, è possibile distruggere il plex.

+
Il seguente esempio mostra che il nodo plex_A_1_aggr1/plex0 è stato cancellato:

+
[listing]
----
cluster_B::> storage aggregate plex delete -aggregate node_A_1_aggr1 -plex plex0

Warning: Aggregate "node_A_1_aggr1" hosts MetroCluster metadata volume
         "MDV_CRS_e8457659b8a711e78b3b00a0988fe74b_A". Deleting plex "plex0"
         for this aggregate can lead to the failure of configuration
         replication across the two DR sites. Use the "volume show -vserver
         <admin-vserver> -volume MDV_CRS*" command to verify the location of
         such volumes.

Warning: Deleting plex "plex0" of mirrored aggregate "node_A_1_aggr1" on node
         "node_A_1" in a MetroCluster configuration will disable its
         synchronous disaster recovery protection. Are you sure you want to
         destroy this plex? {y|n}: y
[Job 639] Job succeeded: DONE

cluster_B::>
----
+
È necessario ripetere questi passaggi per ciascuno degli aggregati guasti.

. Verificare che non vi siano altri plex guasti sul sito sopravvissuto.
+
Il seguente output mostra che tutti i plessi sono normali, attivi e online.

+
[listing]
----
cluster_B::> storage aggregate plex show -fields aggregate,status,is-online,Plex,pool
aggregate    plex  status        is-online pool
------------ ----- ------------- --------- ----
node_B_1_aggr0 plex0 normal,active true     0
node_B_2_aggr0 plex0 normal,active true     0
node_B_1_aggr1 plex0 normal,active true     0
node_B_2_aggr2 plex0 normal,active true     0
node_B_1_aggr1 plex0 normal,active true     0
node_B_2_aggr2 plex0 normal,active true     0
node_A_1_aggr1 plex4 normal,active true     1
node_A_1_aggr2 plex1 normal,active true     1
node_A_2_aggr1 plex4 normal,active true     1
node_A_2_aggr2 plex1 normal,active true     1
10 entries were displayed.

cluster_B::>
----

