---
permalink: disaster-recovery/task_reassign_roots_mcfc.html 
sidebar: sidebar 
keywords: reassign, ownership, nvram, system, id, replaced 
summary: Se uno o entrambi i moduli controller o le schede NVRAM sono stati sostituiti nel sito di emergenza, è necessario riassegnare i dischi appartenenti agli aggregati root ai moduli controller sostitutivi. 
---
= Riassegnazione della proprietà dei dischi per gli aggregati root ai moduli controller sostitutivi (configurazioni MetroCluster FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se uno o entrambi i moduli controller o le schede NVRAM sono stati sostituiti nel sito di emergenza, l'ID del sistema è stato modificato ed è necessario riassegnare i dischi appartenenti agli aggregati root ai moduli controller sostitutivi.

.A proposito di questa attività
Poiché i nodi sono in modalità switchover ed è stata eseguita la riparazione, in questa sezione verranno riassegnati solo i dischi contenenti gli aggregati root del pool 1 del sito di disastro. Si tratta degli unici dischi ancora di proprietà del vecchio ID di sistema a questo punto.

Questa sezione fornisce esempi di configurazioni a due e quattro nodi. Per le configurazioni a due nodi, è possibile ignorare i riferimenti al secondo nodo in ogni sito. Per le configurazioni a otto nodi, è necessario tenere conto dei nodi aggiuntivi nel secondo gruppo di DR. Gli esempi fanno le seguenti ipotesi:

* Il sito A è il sito di disastro.
+
** Il nodo_A_1 è stato sostituito.
** Il nodo_A_2 è stato sostituito.
+
Presente solo nelle configurazioni MetroCluster a quattro nodi.



* Il sito B è il sito sopravvissuto.
+
** Node_B_1 è integro.
** Node_B_2 è integro.
+
Presente solo nelle configurazioni MetroCluster a quattro nodi.





Gli ID di sistema vecchi e nuovi sono stati identificati in link:task_replace_hardware_and_boot_new_controllers.html["Sostituire l'hardware e avviare i nuovi controller"].

Gli esempi di questa procedura utilizzano controller con i seguenti ID di sistema:

|===


| Numero di nodi | Nodo | ID di sistema originale | Nuovo ID di sistema 


.4+| Quattro  a| 
Node_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
Node_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
Node_B_1
 a| 
4068741254
 a| 
invariato



 a| 
Node_B_2
 a| 
4068741256
 a| 
invariato



 a| 
Due
 a| 
Node_A_1
 a| 
4068741258
 a| 
1574774970

|===
.Fasi
. Con il nodo sostitutivo in modalità Maintenance, riassegnare i dischi aggregati root:
+
`disk reassign -s old-system-ID -d new-system-ID`

+
[listing]
----
*> disk reassign -s 4068741258 -d 1574774970
----
. Visualizzare i dischi per confermare la modifica della proprietà dei dischi aggiuntivi root del pool 1 del sito di disastro al nodo sostitutivo:
+
`disk show`

+
L'output potrebbe visualizzare un numero maggiore o minore di dischi, a seconda del numero di dischi presenti nell'aggregato root e se uno di questi dischi è guasto e se è stato sostituito. Se i dischi sono stati sostituiti, i dischi Pool0 non vengono visualizzati nell'output.

+
I dischi aggregati root del pool 1 del sito di emergenza devono ora essere assegnati al nodo sostitutivo.

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK             OWNER                POOL   SERIAL NUMBER   HOME                DR HOME
------------       -------------        -----  -------------   -------------       -------------
sw_A_1:6.126L19    node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L3     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L7     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_B_1:6.126L8     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L24    node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L2     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)

*> aggr status
         Aggr State           Status
 node_A_1_root online          raid_dp, aggr
                               mirror degraded
                               64-bit
*>
----
. Visualizzare lo stato aggregato:
+
`aggr status`

+
L'output potrebbe visualizzare un numero maggiore o minore di dischi, a seconda del numero di dischi presenti nell'aggregato root e se uno di questi dischi è guasto e se è stato sostituito. Se i dischi sono stati sostituiti, i dischi Pool0 non vengono visualizzati nell'output.

+
[listing]
----
*> aggr status
          Aggr State           Status
  node_A_1_root online          raid_dp, aggr
                                mirror degraded
                                64-bit
*>
----
. Eliminare il contenuto dei dischi della mailbox:
+
`mailbox destroy local`

. Se l'aggregato non è online, portalo online:
+
`aggr online aggr_name`

. Arrestare il nodo per visualizzare il prompt DEL CARICATORE:
+
`halt`


