---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: A partire da ONTAP 9.13.1, è possibile eseguire una transizione senza interruzioni di carichi di lavoro e dati da una configurazione MetroCluster FC a otto nodi esistente a una nuova configurazione MetroCluster IP. 
---
= Transizione senza interruzioni da una configurazione MetroCluster FC a una configurazione MetroCluster IP (ONTAP 9.8 e versioni successive)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire transizioni senza interruzioni di carichi di lavoro e dati da una configurazione MetroCluster FC esistente a una nuova configurazione MetroCluster IP.

A partire da ONTAP 9.13.1, questa procedura è supportata nelle configurazioni IP di MetroCluster in cui MetroCluster e gli shelf di dischi sono connessi agli stessi switch IP (configurazione di uno storage condiviso).

A partire da ONTAP 9.13.1, è possibile eseguire una transizione senza interruzioni di carichi di lavoro e dati da una configurazione MetroCluster FC a otto nodi esistente a una nuova configurazione MetroCluster IP.

A partire da ONTAP 9.8, è possibile eseguire una transizione senza interruzioni di carichi di lavoro e dati da una configurazione MetroCluster FC a quattro nodi esistente a una nuova configurazione MetroCluster IP.

* Questa procedura è senza interruzioni.
+
La configurazione MetroCluster può continuare a fornire dati durante l'operazione.

* Questa procedura si applica solo alle configurazioni MetroCluster FC a quattro e otto nodi.
+
Se si dispone di una configurazione MetroCluster FC a due nodi, vedere link:concept_choosing_your_transition_procedure_mcc_transition.html["Scelta della procedura di transizione"].

* Questa procedura descrive i passaggi necessari per la transizione di un gruppo DR FC a quattro nodi. Se si dispone di una configurazione a otto nodi (due gruppi DR FC), è necessario ripetere l'intera procedura per ciascun gruppo DR FC.
* È necessario soddisfare tutti i requisiti e seguire tutte le fasi della procedura.


.Informazioni importanti se si aggiunge un modello di piattaforma precedente
Le seguenti indicazioni riguardano uno scenario insolito in cui è necessario aggiungere un modello di piattaforma precedente (piattaforme rilasciate prima di ONTAP 9.15.1) a una configurazione MetroCluster esistente che contiene un modello di piattaforma più recente (piattaforme rilasciate in ONTAP 9.15.1 o versioni successive).  Per una transizione da FC a IP a otto nodi, questa guida si applica se hai trasferito il tuo primo gruppo DR FC a un modello di piattaforma introdotto in ONTAP 9.15.1 o versione successiva e intendi trasferire il secondo gruppo DR a una piattaforma introdotta prima di ONTAP 9.15.1.

Se la configurazione MetroCluster esistente contiene una piattaforma che utilizza *porte cluster/HA condivise* (piattaforme rilasciate in ONTAP 9.15.1 o versioni successive), non è possibile aggiungere una piattaforma che utilizza *porte MetroCluster/HA condivise* (piattaforme rilasciate prima di ONTAP 9.15.1) senza aggiornare tutti i nodi nella configurazione a ONTAP 9.15.1P11 o ONTAP 9.16.1P4 o versioni successive.

[CAUTION]
====
L'aggiunta di un modello di piattaforma più vecchio che utilizza *porte condivise/ MetroCluster HA* a un MetroCluster contenente un modello di piattaforma più recente che utilizza *porte condivise cluster/HA* è uno scenario insolito e la maggior parte delle combinazioni non ne è interessata.

====
Utilizzare la seguente tabella per verificare se la combinazione è interessata.  Se la piattaforma esistente è elencata nella prima colonna e la piattaforma che si desidera aggiungere alla configurazione è elencata nella seconda colonna, tutti i nodi nella configurazione devono eseguire ONTAP 9.15.1P11 o ONTAP 9.16.1P4 o versioni successive per aggiungere il nuovo gruppo DR.

[cols="20,20,20,20,20"]
|===
2+| Se il tuo MetroCluster esistente contiene... 2+| E la piattaforma che stai aggiungendo è... | Quindi... 


 a| 
Un sistema AFF che utilizza *porte cluster/HA condivise*:

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Un sistema FAS che utilizza *porte cluster/HA condivise*:

* FAS50
* FAS70
* FAS90

 a| 
Un sistema AFF che utilizza *porte MetroCluster/HA condivise*:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Un sistema FAS che utilizza *porte MetroCluster/HA condivise*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Prima di aggiungere la nuova piattaforma alla configurazione MetroCluster esistente, aggiornare tutti i nodi nella configurazione esistente e in quella nuova a ONTAP 9.15.1P11 o ONTAP 9.16.1P4 o versione successiva. 
|===