---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: A partire da ONTAP 9.13.1, è possibile eseguire una transizione senza interruzioni di carichi di lavoro e dati da una configurazione MetroCluster FC a otto nodi esistente a una nuova configurazione MetroCluster IP. 
---
= Transizione senza interruzioni da una configurazione MetroCluster FC a una configurazione MetroCluster IP (ONTAP 9.8 e versioni successive)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire transizioni senza interruzioni di carichi di lavoro e dati da una configurazione MetroCluster FC esistente a una nuova configurazione MetroCluster IP.

A partire da ONTAP 9.13.1, questa procedura è supportata nelle configurazioni IP di MetroCluster in cui MetroCluster e gli shelf di dischi sono connessi agli stessi switch IP (configurazione di uno storage condiviso).

A partire da ONTAP 9.13.1, è possibile eseguire una transizione senza interruzioni dei carichi di lavoro e dei dati da una configurazione MetroCluster FC a otto nodi esistente a una nuova configurazione MetroCluster IP a otto nodi.  Utilizzare questa procedura per trasferire un gruppo FC DR a quattro nodi, rimuovere il gruppo FC DR vuoto e quindi ripetere la procedura per il secondo gruppo FC DR. 

A partire da ONTAP 9.8, è possibile eseguire una transizione senza interruzioni dei carichi di lavoro e dei dati da una configurazione MetroCluster FC a quattro nodi esistente a una nuova configurazione MetroCluster IP a quattro nodi.  Dopo aver completato la transizione, se necessario, è possibile passare a una configurazione IP MetroCluster a otto nodi. Vederelink:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["Espandere una configurazione IP MetroCluster"] .

* Questa procedura è senza interruzioni.
+
La configurazione MetroCluster può continuare a fornire dati durante l'operazione.

* Questa procedura si applica solo alle configurazioni MetroCluster FC a quattro e otto nodi.
+
Se si dispone di una configurazione MetroCluster FC a due nodi, vedere link:concept_choosing_your_transition_procedure_mcc_transition.html["Scelta della procedura di transizione"].

* Questa procedura descrive i passaggi necessari per la transizione di un gruppo DR FC a quattro nodi. Se si dispone di una configurazione a otto nodi (due gruppi DR FC), è necessario ripetere l'intera procedura per ciascun gruppo DR FC.
+

NOTE: Quando si aggiunge o si rimuove un gruppo DR come parte di questa procedura, è necessario verificare che la rimozione o l'aggiunta del gruppo DR sia avvenuta correttamente prima di aggiungere o rimuovere un altro gruppo DR.

* È necessario soddisfare tutti i requisiti e seguire tutte le fasi della procedura.




[[transition-scenarios-supported-by-this-procedure]]
== Scenari di transizione supportati da questa procedura

Consulta la tabella seguente per conoscere gli scenari di transizione supportati da questa procedura.


NOTE: In tutti gli scenari di transizione, puoi aggiungere o rimuovere un solo gruppo di ripristino di emergenza (DR) alla volta. Dopo che l'aggiunta o la rimozione del gruppo DR è andata a buon fine, devi verificare che il MetroCluster sia integro e funzioni normalmente prima di procedere.

[cols="2*"]
|===
| Per questo scenario di transizione... | Esegui le seguenti operazioni... 


 a| 
Configurazione da FC a quattro nodi a IP a quattro nodi
 a| 
Segui questa procedura così come è scritta.



 a| 
Configurazione da FC a quattro nodi a IP a otto nodi
 a| 
È necessario aggiungere un MetroCluster IP DR group. Dopo aver aggiunto il primo MetroCluster IP DR group, controlla lo stato generale del cluster e ripeti i passaggi per il secondo MetroCluster IP DR group.



 a| 
Configurazione da otto nodi FC a quattro nodi IP
 a| 
Segui questa procedura così come è scritta. Durante la transizione, la configurazione MetroCluster si espanderà da otto a dodici nodi. Al termine della transizione e dopo che tutti i nodi FC MetroCluster sono stati scollegati, la configurazione finale sarà una configurazione IP MetroCluster a quattro nodi.



 a| 
Configurazione da otto nodi FC a otto nodi IP
 a| 
Questa transizione richiede l'aggiunta di un MetroCluster IP DR group al cluster.

Dopo aver verificato l'integrità della configurazione a dodici nodi, sposta i dati e i LIF (se necessario) da uno dei gruppi DR MetroCluster FC al gruppo DR MetroCluster IP. Quando uno dei gruppi DR MetroCluster FC è vuoto, rimuovi quel gruppo DR e scollega quei nodi. La configurazione risultante è un cluster a otto nodi composto da un gruppo DR MetroCluster FC e un gruppo DR MetroCluster IP.

Successivamente, aggiungi il secondo gruppo IP DR MetroCluster al cluster ed esegui la transizione dei dati e dei LIF (se necessario). Quando l'ultimo gruppo FC DR MetroCluster rimanente è vuoto, rimuovilo e disconnetti quei nodi.

In qualsiasi momento durante la transizione, il numero di nodi nella configurazione MetroCluster non supera i dodici nodi.

|===
Per ulteriori informazioni, vedere il link:concept_transition_workflow_fc_to_ip_transition.html["Workflow per la transizione MetroCluster senza interruzioni"].



[[important-information-when-adding-an-older-platform-model]]
== Informazioni importanti quando aggiungi un modello di piattaforma precedente

Le seguenti indicazioni riguardano uno scenario insolito in cui è necessario aggiungere un modello di piattaforma precedente (piattaforme rilasciate prima di ONTAP 9.15.1) a una configurazione MetroCluster esistente che contiene un modello di piattaforma più recente (piattaforme rilasciate in ONTAP 9.15.1 o versioni successive).  Per una transizione da FC a IP a otto nodi, questa guida si applica se hai trasferito il tuo primo gruppo DR FC a un modello di piattaforma introdotto in ONTAP 9.15.1 o versione successiva e intendi trasferire il secondo gruppo DR a una piattaforma introdotta prima di ONTAP 9.15.1.

Se la configurazione MetroCluster esistente contiene una piattaforma che utilizza *porte cluster/HA condivise* (piattaforme rilasciate in ONTAP 9.15.1 o versioni successive), non è possibile aggiungere una piattaforma che utilizza *porte MetroCluster/HA condivise* (piattaforme rilasciate prima di ONTAP 9.15.1) senza aggiornare tutti i nodi nella configurazione a ONTAP 9.15.1P11 o ONTAP 9.16.1P4 o versioni successive.

Usa la tabella seguente per verificare se la tua combinazione è interessata. Se la tua piattaforma esistente è elencata nella prima colonna e la piattaforma che vuoi aggiungere alla configurazione è elencata nella seconda colonna, tutti i nodi della configurazione devono eseguire ONTAP 9.15.1P11 o ONTAP 9.16.1P4 o versioni successive (a seconda della versione di ONTAP supportata dalla piattaforma) per aggiungere il nuovo gruppo DR.

[CAUTION]
====
* Aggiungere un modello di piattaforma più vecchio che utilizza *porte MetroCluster/HA condivise* a un MetroCluster che contiene un modello di piattaforma più recente che utilizza *porte cluster/HA condivise* è uno scenario insolito e la maggior parte delle combinazioni non ne è influenzata.
* La tabella mostra tutti i modelli di piattaforma che utilizzano *porte MetroCluster/HA condivise* e *porte cluster/HA condivise*. Non tutte le combinazioni sono supportate da questa procedura. Consulta la link:concept_choosing_your_transition_procedure_mcc_transition.html#supported-platform-combinations["combinazioni di piattaforme supportate"] per verificare se la tua combinazione di transizione è supportata.


====
[cols="20,20,20,20,20"]
|===
2+| Se il tuo MetroCluster esistente contiene... 2+| E la piattaforma che stai aggiungendo è... | Quindi... 


 a| 
Un sistema AFF che utilizza *porte cluster/HA condivise*:

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Un sistema FAS che utilizza *porte cluster/HA condivise*:

* FAS50
* FAS70
* FAS90

 a| 
Un sistema AFF che utilizza *porte MetroCluster/HA condivise*:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Un sistema FAS che utilizza *porte MetroCluster/HA condivise*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Prima di aggiungere la nuova piattaforma alla configurazione MetroCluster esistente, aggiornare tutti i nodi nella configurazione esistente e in quella nuova a ONTAP 9.15.1P11 o ONTAP 9.16.1P4 o versione successiva. 
|===