---
permalink: transition/concept_mcc_operation_during_transition.html 
sidebar: sidebar 
keywords: notice, alert, message, transition, alert, safe, ignore, tool, transition 
summary: Durante la transizione potrebbero essere visualizzati messaggi di avviso. Questi avvisi possono essere ignorati in modo sicuro. Inoltre, alcuni strumenti non sono disponibili durante la transizione. 
---
= Messaggi di avviso e supporto dello strumento durante la transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la transizione potrebbero essere visualizzati messaggi di avviso. Questi avvisi possono essere ignorati in modo sicuro. Inoltre, alcuni strumenti non sono disponibili durante la transizione.

* GLI AR potrebbero inviare un avviso durante la transizione.
+
Questi avvisi possono essere ignorati e dovrebbero scomparire una volta terminata la transizione.

* Il gestore unificato di OnCommand potrebbe inviare un avviso durante la transizione.
+
Questi avvisi possono essere ignorati e dovrebbero scomparire una volta terminata la transizione.

* Config Advisor non è supportato durante la transizione.
* System Manager non è supportato durante la transizione.

