---
permalink: transition/task_move_an_fc_san_workload_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: non-disruptively, transition, metrocluster, fc, ip, node, san, host, moving, move 
summary: Durante la transizione senza interruzioni da MetroCluster FC a nodi IP, è necessario spostare senza interruzioni gli oggetti host FC SAN da MetroCluster FC a nodi IP. 
---
= Spostamento di un carico di lavoro SAN FC da MetroCluster FC a nodi IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la transizione senza interruzioni da MetroCluster FC a nodi IP, è necessario spostare senza interruzioni gli oggetti host FC SAN da MetroCluster FC a nodi IP.

. Impostare nuove interfacce FC (LIFS) sui nodi IP MetroCluster:
+
.. Se necessario, sui nodi IP MetroCluster, modificare le porte FC da utilizzare per la connettività del client al linguaggio di destinazione FC.
+
Questo potrebbe richiedere un riavvio dei nodi.

.. Creare interfacce/LIFS FC sui nodi IP per tutti i vserver SAN. Se si desidera, verificare che le WWPN delle nuove LIF FC siano registrate nello switch FC SAN


. Aggiornare la configurazione dello zoning SAN per le nuove LIF FC aggiunte sui nodi IP MetroCluster.
+
Per facilitare lo spostamento di volumi che contengono LUN che forniscono attivamente i dati ai client FC SAN, aggiornare le zone switch FC esistenti per consentire ai client FC SAN di accedere alle LUN sui nodi IP MetroCluster.

+
.. Sullo switch FC SAN (Cisco o Brocade), aggiungere alla zona le WWPN delle nuove LIF FC SAN aggiunte.
.. Aggiornare, salvare e confermare le modifiche di zoning.
.. Dal client, verificare la presenza di accessi FC Initiator alle nuove LIF SAN sui nodi IP MetroCluster: `sanlun lun show -p`
+
A questo punto, il client dovrebbe visualizzare ed essere connesso alle interfacce FC su entrambi i nodi MetroCluster FC e MetroCluster IP. LUN e volumi sono ancora fisicamente ospitati sui nodi FC MetroCluster.

+
Poiché i LUN sono riportati solo sulle interfacce dei nodi FC MetroCluster, il client mostra solo i percorsi sui nodi FC. Questo è visibile nell'output dei comandi sanlun lun show -p e multipath -ll -d.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_

[root@stemgr]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


. Modificare i nodi di reporting per aggiungere i nodi IP MetroCluster
+
.. Elencare i nodi di reporting per LUN su SVM: `lun mapping show -vserver svm-name -fields reporting-nodes -ostype linux`
+
I nodi di reporting mostrati sono nodi locali in quanto i LUN sono fisicamente presenti sui nodi FC A_1 e A_2.

+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver  path                        igroup         reporting-nodes
-------  --------------------------- ------------   -------------------------------------
vsa_1    /vol/vsa_1_vol1/lun_linux_2 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol1/lun_linux_3 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol2/lun_linux_4 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol3/lun_linux_7 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_8 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_9 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_12 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_13 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol7/lun_linux_14 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol8/lun_linux_17 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_18 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_19 igroup_linux  A_1,A_2
12 entries were displayed.
----
.. Aggiungere nodi di reporting per includere nodi IP MetroCluster.
+
[listing]
----
cluster_A::> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes B_1,B_2 -igroup igroup_linux

12 entries were acted on.
----
.. Elencare i nodi di reporting e verificare la presenza dei nuovi nodi:
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path                          igroup          reporting-nodes
------- ---------------------------   ------------    -------------------------------------------------------------------------------

vsa_1   /vol/vsa_1_vol1/lun_linux_2   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol1/lun_linux_3   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol2/lun_linux_4   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol3/lun_linux_7   igroup_linux    A_1,A_2,B_1,B_2
...

12 entries were displayed.
----
.. Eseguire nuovamente la scansione del bus scsi sull'host per rilevare i percorsi aggiunti di recente: `/usr/bin/rescan-scsi-bus.sh -a`
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
.. Visualizzare i percorsi aggiunti di recente: `sanlun lun show -p`
+
Ogni LUN avrà quattro percorsi.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_
up secondary sdag host4 iscsi_lf__n4_p1_
up secondary sdah host5 iscsi_lf__n3_p1_
----
.. Sui controller, spostare i volumi contenenti LUN dal MetroCluster FC ai nodi MetroCluster IP.
+
[listing]
----
cluster_A::> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate A_1_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "A_1_htp_005_aggr1". Use the "volume move show -vserver vsa_1 -volume vsa_1_vol1"
command to view the status of this operation.
cluster_A::> volume move show
Vserver    Volume    State    Move Phase   Percent-Complete Time-To-Complete
--------- ---------- -------- ----------   ---------------- ----------------
vsa_1     vsa_1_vol1 healthy  initializing
 - -
----
.. Sul client FC SAN, visualizzare le informazioni del LUN: `sanlun lun show -p`
+
Le interfacce FC sui nodi IP MetroCluster in cui risiede il LUN vengono aggiornate come percorsi primari. Se il percorso primario non viene aggiornato dopo lo spostamento del volume, eseguire /usr/bin/rescan-scsi-bus.sh -a o semplicemente attendere che venga eseguita una nuova scansione su più percorsi.

+
Il percorso primario nell'esempio seguente è il LIF sul nodo IP MetroCluster.

+
[listing]
----
[root@localhost ~]# sanlun lun show -p

                    ONTAP Path: vsa_1:/vol/vsa_1_vol1/lun_linux_2
                           LUN: 22
                      LUN Size: 2g
                       Product: cDOT
                   Host Device: 3600a098038302d324e5d50305063546e
              Multipath Policy: service-time 0
            Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host      vserver
path      path       /dev/   host         vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ----------------------------------------------
up        primary    sddv    host6        fc_5
up        primary    sdjx    host7        fc_6
up        secondary  sdgv    host6        fc_8
up        secondary  sdkr    host7        fc_8
----
.. Ripetere i passaggi precedenti per tutti i volumi, le LUN e le interfacce FC appartenenti a un host FC SAN.
+
Una volta completata l'operazione, tutte le LUN di un determinato host SVM e FC SAN devono trovarsi su nodi IP MetroCluster.



. Rimuovere i nodi di reporting e i percorsi di nuova scansione dal client.
+
.. Rimuovere i nodi di reporting remoti (i nodi FC MetroCluster) per le LUN linux: `lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true`
+
[listing]
----
cluster_A::> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true
12 entries were acted on.
----
.. Controllare i nodi di reporting per le LUN: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path igroup reporting-nodes
------- --------------------------- ------------ -----------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol2/lun_linux_4 igroup_linux B_1,B_2
...

12 entries were displayed.
----
.. Eseguire nuovamente la scansione del bus scsi sul client: `/usr/bin/rescan-scsi-bus.sh -r`
+
I percorsi dai nodi MetroCluster FC vengono rimossi:

+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
...
----
.. Verificare che dall'host siano visibili solo i percorsi dei nodi IP MetroCluster: `sanlun lun show -p`
.. Se necessario, rimuovere le LIF iSCSI dai nodi FC MetroCluster.
+
Questa operazione deve essere eseguita se non sono presenti altre LUN sui nodi mappati ad altri client.




