---
permalink: transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: transition, metrocluster, node, fc, ip, iscsi, host, connection, moving, move, linux, set, up, add, report, removing, remove, rescan, path 
summary: Dopo aver eseguito la transizione dei nodi MetroCluster da FC a IP, potrebbe essere necessario spostare le connessioni host iSCSI nei nuovi nodi. 
---
= Spostamento degli host iSCSI Linux da MetroCluster FC a nodi IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver eseguito la transizione dei nodi MetroCluster da FC a IP, potrebbe essere necessario spostare le connessioni host iSCSI nei nuovi nodi.

In questa procedura vengono create le interfacce IPv4.

I comandi host e gli esempi forniti in queste procedure sono specifici per i sistemi operativi LINUX.



== Configurazione di nuove connessioni iSCSI

[role="lead"]
Per spostare le connessioni iSCSI, è necessario impostare nuove connessioni iSCSI ai nodi IP di MetroCluster.

. Creare interfacce iSCSI sui nodi IP MetroCluster e controllare la connettività ping dai client iSCSI alle nuove interfacce IP sui nodi IP MetroCluster.
+
https://docs.netapp.com/us-en/ontap/networking/create_a_lif.html["Creazione di interfacce di rete"^]

+
Tutte le interfacce iSCSI della SVM devono essere raggiungibili dal client iSCSI.

. Sull'host o sul client iSCSI, identificare le connessioni iSCSI esistenti dall'host al nodo FC MetroCluster: `iscsiadm -m session`
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session

tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)

tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. Verificare le connessioni dal nodo IP MetroCluster: `iscsi session show -vserver svm-name`
+
[listing]
----
node_A_1-IP::*> iscsi session show -vserver vsa_1

 Tpgroup Initiator Initiator

Vserver Name TSIH Name ISID Alias
--------- ------- ---- ------------------------ --------- ---------------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 scspr1789621001.gdl.englab.netapp.com
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 scspr1789621001.gdl.englab.netapp.com

2 entries were displayed.
----
. Elencare le interfacce iscsi in ONTAP per la SVM che contiene le interfacce: `iscsi interface show -vserver svm-name`
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi interface show -vserver vsa_1

 Logical Status Curr Curr

Vserver    Interface  TPGT Admin/Oper IP Address Node Port Enabled
---------- ---------- ---- ---------- --------------- ----------- ---- -------

vsa_1 iscsi_lf__n1_p1_ 1156 up/up 10.230.68.236 sti8200mcc-htp-001 e0g true
vsa_1 iscsi_lf__n1_p2_ 1157 up/up fd20:8b1e:b255:805e::78c9 sti8200mcc-htp-001 e0h true
vsa_1 iscsi_lf__n2_p1_ 1158 up/up 10.230.68.237 sti8200mcc-htp-002 e0g true
vsa_1 iscsi_lf__n2_p2_ 1159 up/up fd20:8b1e:b255:805e::78ca sti8200mcc-htp-002 e0h true
vsa_1 iscsi_lf__n3_p1_ 1183 up/up 10.226.43.134 sti8200mccip-htp-005 e0c true
vsa_1 iscsi_lf__n4_p1_ 1188 up/up 10.226.43.142 sti8200mccip-htp-006 e0c true

6 entries were displayed.
----
. Sul client iSCSI, eseguire il rilevamento su uno qualsiasi degli indirizzi IP iSCSI sulla SVM per rilevare le nuove destinazioni: `iscsiadm -m discovery -t sendtargets -p iscsi-ip-address`
+
Il rilevamento può essere eseguito su qualsiasi indirizzo IP della SVM, incluse le interfacce non iSCSI.

+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m discovery -t sendtargets -p 10.230.68.236:3260

10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.134:3260,1183 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
----
. Sul client iSCSI, accedere a tutti gli indirizzi rilevati: `iscsiadm -m node -L all -T node-address -p portal-address -l`
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m node -L all -T iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 -p 10.230.68.236:3260 -l

Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] (multiple)
Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] (multiple)
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] successful.
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] successful.
----
. Sul client iSCSI, verificare l'accesso e le connessioni: `iscsiadm -m session`
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session

tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [3] 10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. Dal nodo MetroCluster, verificare l'accesso e la connessione con il client: `iscsi initiator show -vserver vsa_1`
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi initiator show -vserver vsa_1

 Tpgroup Initiator

Vserver Name             TSIH Name                  ISID              Igroup Name
------- --------         ---- --------------------- ----------------- -----------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 igroup_linux
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 igroup_linux
vsa_1 iscsi_lf__n3_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:04 igroup_linux
vsa_1 iscsi_lf__n4_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:03 igroup_linux

4 entries were displayed.
----


Al termine di queste attività, il client è in grado di visualizzare tutte le interfacce iSCSI (sui nodi MetroCluster FC e MetroCluster IP) e di accedere a tutte queste interfacce.

LUN e volumi sono ancora fisicamente ospitati su nodi FC. Poiché i LUN sono riportati solo sulle interfacce dei nodi FC MetroCluster, il client mostra solo i percorsi sui nodi FC MetroCluster. Questo è visibile negli output dei comandi sanlun lun show -p e multipath -ll -d. Il passaggio successivo consiste nell'aggiungere nodi IP come nodi di reporting.

[listing]
----
[root@scspr1789621001 ~]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state     type       node     adapter     LIF
--------- ---------- ------- ------------ ----------------------------------------------
up        primary    sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_

[root@scspr1789621001 ~]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


== Aggiunta dei nodi IP MetroCluster come nodi di reporting

[role="lead"]
Dopo aver impostato le connessioni ai nuovi nodi IP di MetroCluster, è necessario aggiungere nuovi nodi di reporting.

. Nel nodo MetroCluster, elencare i nodi di reporting per le LUN sulla SVM: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
I seguenti nodi di reporting sono nodi locali in quanto i LUN sono fisicamente presenti sui nodi FC Node_A_1-FC e Node_A_2-FC.

+
[listing]
----
node_A_1-IP::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path igroup reporting-nodes
------- --------------------------- ------------ -------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux node_A_1-FC,node_A_2-FC
.
.
.
vsa_1 /vol/vsa_1_vol9/lun_linux_19 igroup_linux node_A_1-FC,node_A_2-FC
12 entries were displayed.
----
. Nel nodo MetroCluster, aggiungere i nodi di reporting: `lun mapping add-reporting-nodes -vserver svm-name -path /vol/vsa_1_vol*/lun_linux_* -nodes node1,node2 -igroup igroup_linux`
+
[listing]
----
node_A_1-IP::*> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes node_A_1-IP,node_A_2-IP
-igroup igroup_linux

12 entries were acted on.
----
. Sul nodo MetroCluster, verificare che siano presenti i nodi appena aggiunti: `lun mapping show -vserver svm-name -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes`
+
[listing]
----

node_A_1-IP::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes
------- --------------------------- ------------ -------------------------------------------------------------------------------

vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux node_A_1-FC,node_A_2-FC,node_A_1-IP,node_A_2-IP
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux node_A_1-FC,node_A_2-FC,node_A_1-IP,node_A_2-IP.
.
.
.

12 entries were displayed.
----
. Sull'host, immettere il seguente comando per eseguire nuovamente la scansione del bus scsi sull'host e individuare i percorsi aggiunti di recente:``/usr/bin/rescan-scsi-bus.sh -a``
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
. Sull'host, immettere il seguente comando per elencare i percorsi aggiunti di recente: `sanlun lun show -p`
+
Per ogni LUN vengono visualizzati quattro percorsi.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_
up secondary sdag host4 iscsi_lf__n4_p1_
up secondary sdah host5 iscsi_lf__n3_p1_
----
. In MetroCluster, spostare i volumi contenenti LUN dai nodi FC a quelli IP.
+
[listing]
----
node_A_1-IP::*> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate sti8200mccip_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "sti8200mccip_htp_005_aggr1". Use the "volume move show -vserver
vsa_1 -volume vsa_1_vol1" command to view the status of this operation.
node_A_1-IP::*> vol move show
Vserver    Volume     State       Move       Phase            Percent-Complete  Time-To-Complete
---------  ---------- --------    ---------- ---------------- ----------------  ----------------
vsa_1     vsa_1_vol1  healthy                initializing     -                 -
----
. Una volta completato lo spostamento del volume, su MetroCluster, utilizzare il comando di visualizzazione del volume per verificare che il volume o il LUN sia in linea.
. Le interfacce iSCSI sui nodi IP MetroCluster in cui risiede il LUN vengono aggiornate come percorsi primari. Se il percorso primario non viene aggiornato dopo lo spostamento del volume, eseguire /usr/bin/rescan-scsi-bus.sh -a e multipath -v3 o semplicemente attendere che venga eseguita la nuova scansione di più percorsi.
+
Nell'esempio seguente, il percorso primario è un LIF sul nodo IP MetroCluster.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ -----------------------
host vserver
path path /dev/ host vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ------------------------
up        primary    sdag    host4        iscsi_lf__n4_p1_
up        secondary  sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_
up        secondary  sdah    host5        iscsi_lf__n3_p1_
----




== Rimozione dei nodi di reporting e dei percorsi di nuova scansione

[role="lead"]
È necessario rimuovere i nodi di reporting e ripetere la scansione dei percorsi.

. Dal nodo IP di MetroCluster, rimuovere i nodi di reporting remoti (i nodi IP di MetroCluster) per le LUN Linux: `lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true`
+
In questo caso, i nodi remoti sono nodi FC.

+
[listing]
----
node_A_1-IP::*> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true

12 entries were acted on.
----
. Dal nodo IP di MetroCluster, controllare i nodi di reporting per le LUN: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
[listing]
----
node_A_1-IP::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver  path                        igroup      reporting-nodes
------- --------------------------- ------------ -----------------------------------------

vsa_1 /vol/vsa_1_vol1/lun_linux_2   igroup_linux  node_A_1-IP,node_A_2-IP
vsa_1 /vol/vsa_1_vol1/lun_linux_3   igroup_linux  node_A_1-IP,node_A_2-IP
vsa_1 /vol/vsa_1_vol2/lun_linux_4   group_linux   node_A_1-IP,node_A_2-IP
.
.
.

12 entries were displayed.
----
. Sull'host iSCSI, eseguire nuovamente la scansione del bus scsi: `/usr/bin/rescan-scsi-bus.sh -r`
+
I percorsi rimossi sono i percorsi dei nodi FC.

+
[listing]
----
[root@scspr1789621001 ~]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
 .
.
.
----
. Sull'host iSCSI, verificare che siano visibili solo i percorsi dai nodi IP MetroCluster: `sanlun lun show -p``multipath -ll -d`

