---
permalink: transition/task_remove_mc_fc_controllers.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Per preparare la configurazione per la transizione, aggiungere i nuovi nodi alla configurazione MetroCluster esistente e spostare i dati nei nuovi nodi. 
---
= Rimozione dei controller FC MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario eseguire attività di pulizia e rimuovere i vecchi moduli controller dalla configurazione MetroCluster.

. Per impedire la generazione automatica del caso di supporto, inviare un messaggio AutoSupport per indicare che la manutenzione è in corso.
+
.. Immettere il seguente comando: `system node autosupport invoke -node * -type all -message MAINT=maintenance-window-in-hours`
+
intervallo di manutenzione in ore specifica la durata della finestra di manutenzione, con un massimo di 72 ore. Se la manutenzione viene completata prima che sia trascorso il tempo, è possibile richiamare un messaggio AutoSupport che indica la fine del periodo di manutenzione:``system node autosupport invoke -node * -type all -message MAINT=end``

.. Ripetere il comando sul cluster partner.


. Identificare gli aggregati ospitati sulla configurazione MetroCluster FC che devono essere cancellati.
+
In questo esempio, i seguenti aggregati di dati sono ospitati dal cluster MetroCluster FC_B e devono essere cancellati: aggr_data_a1 e aggr_data_a2.

+

NOTE: È necessario eseguire i passaggi per identificare, offline ed eliminare gli aggregati di dati su entrambi i cluster. L'esempio riguarda un solo cluster.

+
....
cluster_B::> aggr show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_node_A_1-FC
           349.0GB   16.83GB   95% online       1 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_2-FC
           349.0GB   16.83GB   95% online       1 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.63GB   95% online       1 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.62GB   95% online       1 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a1
            1.02TB    1.02TB    0% online       0 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a2
            1.02TB    1.02TB    0% online       0 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a3
            1.37TB    1.35TB    1% online       3 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a4
            1.25TB    1.24TB    1% online       2 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
8 entries were displayed.

cluster_B::>
....
. Controllare se gli aggregati di dati sui nodi FC hanno volumi MDV_aud ed eliminarli prima di eliminare gli aggregati.
+
È necessario eliminare i volumi MDV_aud in quanto non possono essere spostati.

. Portare tutti gli aggregati di dati offline, quindi eliminarli:
+
.. Portare l'aggregato offline: `storage aggregate offline -aggregate aggregate-name`
+
L'esempio seguente mostra l'aggregato aggr_data_a1 portato offline:

+
....
cluster_B::> storage aggregate offline -aggregate aggr_data_a1

Aggregate offline successful on aggregate: aggr_data_a1
....
.. Eliminare l'aggregato: `storage aggregate delete -aggregate aggregate-name`
+
Quando richiesto, è possibile distruggere il plex.

+
L'esempio seguente mostra l'aggregato aggr_data_a1 che viene cancellato.

+
....
cluster_B::> storage aggregate delete -aggregate aggr_data_a1
Warning: Are you sure you want to destroy aggregate "aggr_data_a1"? {y|n}: y
[Job 123] Job succeeded: DONE

cluster_B::>
....


. Identificare il gruppo DR FC MetroCluster che deve essere rimosso.
+
Nell'esempio seguente, i nodi FC MetroCluster sono nel gruppo DR '1' e questo è il gruppo DR che deve essere rimosso.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        configured     enabled   normal
              node_A_2-FC        configured     enabled   normal
      cluster_B
              node_B_1-FC        configured     enabled   normal
              node_B_2-FC        configured     enabled   normal
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_3-IP        configured     enabled   normal
8 entries were displayed.

cluster_B::>
....
. Spostare la LIF di gestione del cluster da un nodo FC MetroCluster a un nodo IP MetroCluster: `cluster_B::> network interface migrate -vserver svm-name -lif cluster_mgmt -destination-node node-in-metrocluster-ip-dr-group -destination-port available-port`
. Modificare il nodo home e la porta home della LIF di gestione del cluster: `cluster_B::> network interface modify -vserver svm-name -lif cluster_mgmt -service-policy default-management -home-node node-in-metrocluster-ip-dr-group -home-port lif-port`
. Spostamento di epsilon da un nodo FC MetroCluster a un nodo IP MetroCluster:
+
.. Identificare il nodo attualmente dotato di epsilon: `cluster show -fields epsilon`
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      true
node_A_2-FC      false
node_A_1-IP      false
node_A_2-IP      false
4 entries were displayed.
....
.. Impostare epsilon su false sul nodo FC MetroCluster (Node_A_1-FC): `cluster modify -node fc-node -epsilon false`
.. Impostare epsilon su true sul nodo IP MetroCluster (Node_A_1-IP): `cluster modify -node ip-node -epsilon true`
.. Verificare che epsilon sia stato spostato nel nodo corretto: `cluster show -fields epsilon`
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      false
node_A_2-FC      false
node_A_1-IP      true
node_A_2-IP      false
4 entries were displayed.
....


. Modificare l'indirizzo IP per il peer del cluster dei nodi IP in transizione per ciascun cluster:
+
.. Identificare il peer cluster_A utilizzando `cluster peer show` comando:
+
[listing]
----
cluster_A::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
cluster_B         1-80-000011           Unavailable    absent
----
+
... Modificare l'indirizzo IP del peer cluster_A:
+
`cluster peer modify -cluster cluster_A -peer-addrs node_A_3_IP -address-family ipv4`



.. Identificare il peer cluster_B utilizzando `cluster peer show` comando:
+
[listing]
----
cluster_B::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
cluster_A         1-80-000011           Unavailable    absent
----
+
... Modificare l'indirizzo IP del peer cluster_B:
+
`cluster peer modify -cluster cluster_B -peer-addrs node_B_3_IP -address-family ipv4`



.. Verificare che l'indirizzo IP del peer del cluster sia aggiornato per ciascun cluster:
+
... Verificare che l'indirizzo IP sia aggiornato per ciascun cluster utilizzando `cluster peer show -instance` comando.
+
Il `Remote Intercluster Addresses` Nei seguenti esempi viene visualizzato l'indirizzo IP aggiornato.

+
Esempio per cluster_A:

+
[listing]
----
cluster_A::> cluster peer show -instance

Peer Cluster Name: cluster_B
           Remote Intercluster Addresses: 172.21.178.204, 172.21.178.212
      Availability of the Remote Cluster: Available
                     Remote Cluster Name: cluster_B
                     Active IP Addresses: 172.21.178.212, 172.21.178.204
                   Cluster Serial Number: 1-80-000011
                    Remote Cluster Nodes: node_B_3-IP,
                                          node_B_4-IP
                   Remote Cluster Health: true
                 Unreachable Local Nodes: -
          Address Family of Relationship: ipv4
    Authentication Status Administrative: use-authentication
       Authentication Status Operational: ok
                        Last Update Time: 4/20/2023 18:23:53
            IPspace for the Relationship: Default
Proposed Setting for Encryption of Inter-Cluster Communication: -
Encryption Protocol For Inter-Cluster Communication: tls-psk
  Algorithm By Which the PSK Was Derived: jpake

cluster_A::>

----
+
Esempio per cluster_B.

+
[listing]
----
cluster_B::> cluster peer show -instance

                       Peer Cluster Name: cluster_A
           Remote Intercluster Addresses: 172.21.178.188, 172.21.178.196 <<<<<<<< Should reflect the modified address
      Availability of the Remote Cluster: Available
                     Remote Cluster Name: cluster_A
                     Active IP Addresses: 172.21.178.196, 172.21.178.188
                   Cluster Serial Number: 1-80-000011
                    Remote Cluster Nodes: node_A_3-IP,
                                          node_A_4-IP
                   Remote Cluster Health: true
                 Unreachable Local Nodes: -
          Address Family of Relationship: ipv4
    Authentication Status Administrative: use-authentication
       Authentication Status Operational: ok
                        Last Update Time: 4/20/2023 18:23:53
            IPspace for the Relationship: Default
Proposed Setting for Encryption of Inter-Cluster Communication: -
Encryption Protocol For Inter-Cluster Communication: tls-psk
  Algorithm By Which the PSK Was Derived: jpake

cluster_B::>
----




. In ciascun cluster, rimuovere il gruppo di DR contenente i vecchi nodi dalla configurazione MetroCluster FC.
+
È necessario eseguire questo passaggio su entrambi i cluster, uno alla volta.

+
....
cluster_B::> metrocluster remove-dr-group -dr-group-id 1

Warning: Nodes in the DR group that are removed from the MetroCluster
         configuration will lose their disaster recovery protection.

         Local nodes "node_A_1-FC, node_A_2-FC" will be removed from the
         MetroCluster configuration. You must repeat the operation on the
         partner cluster "cluster_B" to remove the remote nodes in the DR group.
Do you want to continue? {y|n}: y

Info: The following preparation steps must be completed on the local and partner
      clusters before removing a DR group.

      1. Move all data volumes to another DR group.
      2. Move all MDV_CRS metadata volumes to another DR group.
      3. Delete all MDV_aud metadata volumes that may exist in the DR group to
      be removed.
      4. Delete all data aggregates in the DR group to be removed. Root
      aggregates are not deleted.
      5. Migrate all data LIFs to home nodes in another DR group.
      6. Migrate the cluster management LIF to a home node in another DR group.
      Node management and inter-cluster LIFs are not migrated.
      7. Transfer epsilon to a node in another DR group.

      The command is vetoed ifthe preparation steps are not completed on the
      local and partner clusters.
Do you want to continue? {y|n}: y
[Job 513] Job succeeded: Remove DR Group is successful.

cluster_B::>
....
. Verificare che i nodi siano pronti per essere rimossi dai cluster.
+
È necessario eseguire questa operazione su entrambi i cluster.

+

NOTE: A questo punto, il `metrocluster node show` Il comando mostra solo i nodi FC MetroCluster locali e non mostra più i nodi che fanno parte del cluster partner.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        ready to configure
                                                -         -
              node_A_2-FC        ready to configure
                                                -         -
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_4-IP        configured     enabled   normal
6 entries were displayed.

cluster_B::>
....
. Disattiva il failover dello storage per i nodi FC MetroCluster.
+
È necessario eseguire questa operazione su ciascun nodo.

+
....
cluster_A::> storage failover modify -node node_A_1-FC -enabled false
cluster_A::> storage failover modify -node node_A_2-FC -enabled false
cluster_A::>
....
. Disunire i nodi MetroCluster FC dai cluster: `cluster unjoin -node node-name`
+
È necessario eseguire questa operazione su ciascun nodo.

+
....
cluster_A::> cluster unjoin -node node_A_1-FC

Warning: This command will remove node "node_A_1-FC"from the cluster. You must
         remove the failover partner as well. After the node is removed, erase
         its configuration and initialize all disks by usingthe "Clean
         configuration and initialize all disks (4)" option from the boot menu.
Do you want to continue? {y|n}: y
[Job 553] Job is queued: Cluster remove-node of Node:node_A_1-FC with UUID:6c87de7e-ff54-11e9-8371
[Job 553] Checking prerequisites
[Job 553] Cleaning cluster database
[Job 553] Job succeeded: Node remove succeeded
If applicable, also remove the node's HA partner, and then clean its configuration and initialize all disks with the boot menu.
Run "debug vreport show" to address remaining aggregate or volume issues.

cluster_B::>
....
. Se la configurazione utilizza bridge FC-SAS o switch back-end FC, scollegarli e rimuoverli.
+
[role="tabbed-block"]
====
.Rimozione dei bridge FC-to-SAS
--
.. Identificare i ponti:
+
`system bridge show`

.. Rimuovere i ponti:
+
`system bridge remove -name <bridge_name>`

.. Verificare che i ponti siano stati rimossi:
+
`system bridge show`



L'esempio seguente mostra che i ponti vengono rimossi:

.Esempio
[%collapsible]
=====
[listing]
----
cluster1::> system bridge remove -name ATTO_10.226.197.16
cluster1::> system bridge show
                                                                Is        Monitor
    Bridge     Symbolic Name Vendor  Model     Bridge WWN       Monitored Status
    ---------- ------------- ------- --------- ---------------- --------- -------
    ATTO_FibreBridge6500N_1
               Bridge Number 16
                             Atto    FibreBridge 6500N
                                               2000001086603824 false     -
    ATTO_FibreBridge6500N_2
               Not Set       Atto    FibreBridge 6500N
                                               20000010866037e8 false     -
    ATTO_FibreBridge6500N_3
               Not Set       Atto    FibreBridge 6500N
                                               2000001086609e0e false     -
    ATTO_FibreBridge6500N_4
               Not Set       Atto    FibreBridge 6500N
                                               2000001086609c06 false     -
    4 entries were displayed.
----
=====
--
.Rimuovere gli switch FC
--
.. Identificare gli interruttori:
+
`system switch fibre-channel show`

.. Rimuovere gli interruttori:
+
`system switch fibre-channel remove -switch-name <switch_name>`

.. Verificare che gli interruttori siano stati rimossi:
+
`system switch fibre-channel show`



.Esempio
[%collapsible]
=====
[listing]
----
cluster1::> system switch fibre-channel show
                Symbolic                                     Is        Monitor
    Switch      Name     Vendor  Model      Switch WWN       Monitored Status
    ----------- -------- ------- ---------- ---------------- --------- -------
    Cisco_10.226.197.34
                mcc-cisco-8Gb-fab-4
                         Cisco   DS-C9148-16P-K9
                                            2000547fee78f088 true      ok
    mcc-cisco-8Gb-fab-1
                mcc-cisco-8Gb-fab-1
                         Cisco   -          -                false     -
    mcc-cisco-8Gb-fab-2
                mcc-cisco-8Gb-fab-2
                         Cisco   -          -                false     -
    mcc-cisco-8Gb-fab-3
                mcc-cisco-8Gb-fab-3
                         Cisco   -          -                false     -
    4 entries were displayed.
cluster1::> system switch fibre-channel remove -switch-name Cisco_10.226.197.34
cluster1::> system switch fibre-channel show
                Symbolic                                     Is        Monitor
    Switch      Name     Vendor  Model      Switch WWN       Monitored Status
    ----------- -------- ------- ---------- ---------------- --------- -------
    mcc-cisco-8Gb-fab-4
                mcc-cisco-8Gb-fab-4
                         Cisco
                                 -          -                false     -
    mcc-cisco-8Gb-fab-1
                mcc-cisco-8Gb-fab-1
                         Cisco   -          -                false     -
    mcc-cisco-8Gb-fab-2
                mcc-cisco-8Gb-fab-2
                         Cisco   -          -                false     -
    mcc-cisco-8Gb-fab-3
                mcc-cisco-8Gb-fab-3
                         Cisco   -          -                false     -
    4 entries were displayed
cluster1::>
----
=====
--
====
. Spegnere i moduli controller FC MetroCluster e gli shelf di storage.
. Scollegare e rimuovere i moduli controller FC MetroCluster e gli shelf di storage.

