---
permalink: upgrade/reference_where_to_find_additional_information_mcc_ug.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, additional, information 
summary: Scopri di più sulla configurazione e sul funzionamento di MetroCluster. 
---
= Dove trovare ulteriori informazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri di più sulla configurazione e sul funzionamento di MetroCluster.



== MetroCluster e informazioni varie

|===


| Informazioni | Soggetto 


 a| 
link:../index.html["Documentazione MetroCluster"]
 a| 
* Tutte le informazioni MetroCluster




 a| 
link:../install-fc/index.html["Installazione e configurazione di Fabric-Attached MetroCluster"]
 a| 
* Architettura Fabric-Attached MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione degli switch FC
* Configurazione di MetroCluster in ONTAP




 a| 
link:../install-stretch/concept_considerations_differences.html["Estensione dell'installazione e della configurazione di MetroCluster"]
 a| 
* Estendi l'architettura MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione di MetroCluster in ONTAP




 a| 
link:../disaster-recovery/concept_dr_workflow.html["Gestione MetroCluster e disaster recovery"]
 a| 
* Informazioni sulla configurazione di MetroCluster
* Switchover, healing e switchback
* Disaster recovery




 a| 
link:../maintain/index.html["Gestire i componenti di MetroCluster"]
 a| 
* Linee guida per la manutenzione in una configurazione MetroCluster FC
* Procedure di sostituzione o aggiornamento dell'hardware e aggiornamento del firmware per bridge FC-SAS e switch FC
* Aggiunta a caldo di uno shelf di dischi in una configurazione MetroCluster FC fabric-attached o stretch
* Rimozione a caldo di uno shelf di dischi in una configurazione MetroCluster FC con connessione fabric o stretch
* Sostituzione dell'hardware in un sito di emergenza in una configurazione FC MetroCluster Fabric-Attached o Stretch
* Espansione di una configurazione MetroCluster FC a due nodi collegata a fabric o estesa a una configurazione MetroCluster a quattro nodi.
* Espansione di una configurazione FC MetroCluster con collegamento fabric a quattro nodi o estensione in una configurazione FC MetroCluster a otto nodi.




 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Upgrade, transizione ed espansione di MetroCluster"]
 a| 
* Aggiornamento o aggiornamento di una configurazione MetroCluster
* Passaggio da una configurazione MetroCluster FC a una configurazione MetroCluster IP
* Espansione di una configurazione MetroCluster mediante l'aggiunta di nodi aggiuntivi




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installazione e configurazione del software MetroCluster Tiebreaker"]
 a| 
* Monitoraggio della configurazione MetroCluster con il software MetroCluster Tiebreaker




 a| 
https://docs.netapp.com/platstor/index.jsp["Centro di documentazione AFF e FAS"^]


NOTE: Le procedure di manutenzione standard dello shelf storage possono essere utilizzate con le configurazioni IP di MetroCluster.
 a| 
* Aggiunta a caldo di uno shelf di dischi
* Rimozione a caldo di uno shelf di dischi




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transizione basata sulla copia"^]
 a| 
* Transizione dei dati dai sistemi storage 7-Mode ai sistemi storage in cluster




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["Concetti di ONTAP"^]
 a| 
* Come funzionano gli aggregati mirrorati


|===