---
permalink: upgrade/task_install_and_cable_the_new_controller.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, install, cable, new, controller, module 
summary: È necessario installare fisicamente il nuovo modulo controller nello chassis e collegarlo via cavo. 
---
= Installazione e cablaggio del nuovo modulo controller
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare fisicamente il nuovo modulo controller nello chassis e collegarlo via cavo.

.Fasi
. Se si dispone di un modulo di espansione i/o (IOXM) nel sistema e si sta creando una coppia ha a chassis singolo, è necessario scollegare e rimuovere IOXM.
+
È quindi possibile utilizzare l'alloggiamento vuoto per il nuovo modulo controller. Tuttavia, la nuova configurazione non avrà l'i/o extra fornito da IOXM.

. Installare fisicamente il nuovo modulo controller e, se necessario, installare ventole aggiuntive:
+
|===


| Se si aggiunge un modulo controller... | Quindi, eseguire questa procedura... 


 a| 
A un alloggiamento vuoto per creare una coppia ha a chassis singolo e il sistema appartiene a una delle seguenti piattaforme:
 a| 
.. Rimuovere la piastra vuota nella parte posteriore dello chassis che copre l'alloggiamento vuoto che contiene il nuovo modulo controller.
.. Spingere delicatamente il modulo controller a metà nel telaio.
+
Per evitare che il modulo controller si avvii automaticamente, non inserirlo completamente nel telaio fino a quando non viene eseguita questa procedura.





 a| 
In uno chassis separato dal partner ha per creare una coppia ha a doppio chassis quando la configurazione esistente si trova in una configurazione controller-modulo IOX.

** FAS8200
** 80xx

 a| 
Installare il nuovo sistema nel rack o nell'armadietto del sistema.

|===
. Cablare le connessioni di rete del cluster, se necessario:
+
.. Identificare le porte sul modulo controller per le connessioni del cluster.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["Sistemi AFF A320: Installazione e configurazione"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["Istruzioni per l'installazione e la configurazione dei sistemi AFF A220/FAS2700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["Istruzioni per l'installazione e la configurazione dei sistemi AFF A800"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["Istruzioni per l'installazione e la configurazione dei sistemi AFF A300"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["Istruzioni per l'installazione e la configurazione dei sistemi FAS8200"^]

.. Se si configura un cluster con switch, identificare le porte che verranno utilizzate sugli switch di rete del cluster.
+
Consultare la _Guida alla configurazione dello switch Clustered Data ONTAP per gli switch Cisco_, la _Guida all'installazione dello switch in modalità cluster 10G di NetApp_ o la _Guida all'installazione dello switch in modalità cluster 1G di NetApp_, a seconda degli switch in uso.

.. Collegare i cavi alle porte del cluster:


+
|===


| Se il cluster è... | Quindi... 


 a| 
Un cluster senza switch a due nodi
 a| 
Collegare direttamente le porte del cluster sul modulo controller esistente alle porte del cluster corrispondenti sul nuovo modulo controller.



 a| 
Un cluster con switch
 a| 
Collegare le porte del cluster di ciascun controller alle porte degli switch di rete del cluster identificati nel passo b.

|===

