---
permalink: upgrade/task-clear-configuration-controller-four-node.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, clear, configuration, controller, module 
summary: Prima di utilizzare un nuovo modulo controller nella configurazione MetroCluster, è necessario cancellare la configurazione. 
---
= Cancella la configurazione su un modulo controller durante un'espansione FC a quattro nodi di MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare un nuovo modulo controller nella configurazione MetroCluster, è necessario cancellare la configurazione esistente.

.Fasi
. Se necessario, arrestare il nodo per visualizzare il `LOADER` prompt:
+
`halt`

. Quando `LOADER` richiesto, impostare le variabili ambientali sui valori predefiniti:
+
`set-defaults`

. Salvare l'ambiente:
+
`saveenv`

. Quando `LOADER` richiesto, avviare il menu di avvio:
+
`boot_ontap menu`

. Al prompt del menu di avvio, cancellare la configurazione:
+
`wipeconfig`

+
Rispondere `yes` al prompt di conferma.

+
Il nodo si riavvia e viene visualizzato di nuovo il menu di avvio.

. Nel menu di avvio, selezionare l'opzione *5* per avviare il sistema in modalità di manutenzione.
+
Rispondere `yes` al prompt di conferma.


