---
permalink: upgrade/task_mirror_the_root_aggregates_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, mirror, root, aggregate 
summary: È necessario eseguire il mirroring degli aggregati root per garantire la protezione dei dati. 
---
= Mirroring degli aggregati root
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario eseguire il mirroring degli aggregati root per garantire la protezione dei dati.

Per impostazione predefinita, l'aggregato root viene creato come aggregato di tipo RAID-DP. È possibile modificare l'aggregato root da RAID-DP a aggregato di tipo RAID4. Il seguente comando modifica l'aggregato root per l'aggregato di tipo RAID4:

[listing]
----
storage aggregate modify –aggregate aggr_name -raidtype raid4
----

NOTE: Nei sistemi non ADP, il tipo RAID dell'aggregato può essere modificato dal RAID-DP predefinito a RAID4 prima o dopo il mirroring dell'aggregato.

.Fasi
. Eseguire il mirroring dell'aggregato root:
+
`storage aggregate mirror _aggr_name_`

+
Il seguente comando esegue il mirroring dell'aggregato root per controller_A_1:

+
[listing]
----
controller_A_1::> storage aggregate mirror aggr0_controller_A_1
----
+
Questo esegue il mirroring dell'aggregato, quindi è costituito da un plex locale e da un plex remoto situati nel sito MetroCluster remoto.

. Ripetere il passaggio precedente per ciascun nodo della configurazione MetroCluster.

