---
permalink: upgrade/task-expand-four-to-eight-mcc-fc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, mirrored, data, aggregate, node 
summary: È necessario creare un aggregato di dati mirrorato su ciascun nodo del gruppo DR. 
---
= Crea un aggregato di dati mirrorati su ciascun nodo FC MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare un aggregato di dati mirrorato su ciascun nodo del gruppo DR.

.A proposito di questa attività
* Devi sapere quali dischi verranno utilizzati nel nuovo aggregato.
* Se nel sistema sono presenti più tipi di unità (storage eterogeneo), è necessario comprendere come assicurarsi che venga selezionato il tipo di unità corretto.
* I dischi sono di proprietà di un nodo specifico; quando si crea un aggregato, tutti i dischi in tale aggregato devono essere di proprietà dello stesso nodo, che diventa il nodo principale per quell'aggregato.
+
Nei sistemi che utilizzano ADP, gli aggregati vengono creati utilizzando partizioni in cui ciascun disco viene partizionato nelle partizioni P1, P2 e P3.

* I nomi degli aggregati devono essere conformi allo schema di denominazione stabilito al momento della pianificazione della configurazione MetroCluster.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestione di dischi e aggregati"]

* I nomi degli aggregati devono essere univoci in tutti i siti MetroCluster. Ciò significa che non è possibile avere due aggregati diversi con lo stesso nome sul sito A e sul sito B.



NOTE: Si consiglia di mantenere almeno il 20% di spazio libero per gli aggregati con mirroring per performance dello storage e disponibilità ottimali. Sebbene la raccomandazione sia del 10% per gli aggregati non con mirroring, il 10% di spazio aggiuntivo può essere utilizzato dal filesystem per assorbire modifiche incrementali. Le modifiche incrementali aumentano l'utilizzo dello spazio per gli aggregati con mirroring a causa dell'architettura copy-on-write basata su Snapshot di ONTAP. Il mancato rispetto di queste best practice potrebbe avere un impatto negativo sulle performance.

.Fasi
. Visualizzare un elenco delle parti di ricambio disponibili:
+
`storage disk show -spare -owner <node_name>`

. Creare l'aggregato:
+
`storage aggregate create -mirror true`

+
Se si è effettuato l'accesso al cluster tramite l'interfaccia di gestione del cluster, è possibile creare un aggregato su qualsiasi nodo del cluster. Per verificare che l'aggregato sia stato creato su un nodo specifico, utilizzare il  `-node` parametro o specificare le unità di proprietà di quel nodo.

+
È possibile specificare le seguenti opzioni:

+
** Nodo principale dell'aggregato (ovvero, il nodo proprietario dell'aggregato durante il normale funzionamento)
** Elenco dei dischi specifici da aggiungere all'aggregato
** Numero di dischi da includere
+

NOTE: Nella configurazione minima supportata, in cui è disponibile un numero limitato di dischi, è necessario utilizzare l'opzione force-Small-aggregate per consentire la creazione di un aggregato RAID-DP a tre dischi.

** Stile checksum da utilizzare per l'aggregato
** Tipo di dischi da utilizzare
** Dimensioni delle unità da utilizzare
** Velocità del disco da utilizzare
** Tipo RAID per i gruppi RAID sull'aggregato
** Numero massimo di dischi che possono essere inclusi in un gruppo RAID
** Se sono consentiti dischi con diversi RPM
+
Per ulteriori informazioni su queste opzioni, consultare `storage aggregate create` pagina man.

+
Il seguente comando crea un aggregato mirrorato con 10 dischi:

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. Verificare il gruppo RAID e i dischi del nuovo aggregato:
+
`storage aggregate show-status -aggregate <aggregate-name>`


