---
permalink: upgrade/upgrade-mcc-ip-manual-boot-new-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Avviare i nuovi controller e verificare che le LIF siano ospitate sui nodi e sulle porte appropriati. 
---
= Avvia i nuovi controller IP di MetroCluster e ripristina la configurazione LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avviare i nuovi controller e verificare che le LIF siano ospitate sui nodi e sulle porte appropriati.



== Avviare le nuove centraline

È necessario avviare i nuovi controller, assicurandosi che le variabili di boot siano corrette e, se necessario, eseguire le operazioni di ripristino della crittografia.

.Fasi
. Arrestare i nuovi nodi:
+
`halt`

. Se è configurato un gestore di chiavi esterno, impostare i relativi bootargs:
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`

+
`setenv bootarg.kmip.init.netmask <netmask>`

+
`setenv bootarg.kmip.init.gateway <gateway-addres>`

+
`setenv bootarg.kmip.init.interface <interface-id>`

. Verificare se il sistema partner è quello corrente:
+
`printenv partner-sysid`

+
Se il partner-sysid non è corretto, impostarlo:

+
`setenv partner-sysid <partner-sysID>`

. Visualizzare il menu di avvio di ONTAP:
+
`boot_ontap menu`

. Se viene utilizzata la crittografia root, selezionare l'opzione del menu di avvio per la configurazione della gestione delle chiavi.
+
|===


| Se si utilizza... | Selezionare questa opzione del menu di avvio... 


 a| 
Gestione delle chiavi integrata
 a| 
Opzione `10`

Seguire le istruzioni per fornire gli input necessari per ripristinare la configurazione di gestione delle chiavi.



 a| 
Gestione esterna delle chiavi
 a| 
Opzione `11`

Seguire le istruzioni per fornire gli input necessari per ripristinare la configurazione di gestione delle chiavi.

|===
. Dal menu di avvio, selezionare "`(6) Update flash from backup config`".
+

NOTE: L'opzione 6 riavvia il nodo due volte prima del completamento del processo.

+
Rispondere con "`y'" alle richieste di modifica dell'ID di sistema. Attendere i secondi messaggi di riavvio:

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
. Al `LOADER` prompt, verificare i valori di bootarg e aggiornare i valori secondo necessità.
+
Utilizzare i passaggi descritti in link:upgrade-mcc-ip-manual-apply-rcf-set-bootarg.html#set-the-metrocluster-ip-bootarg-variables["Impostare le variabili di boot IP di MetroCluster"].

. Verificare che il partner-sysid sia corretto:
+
`printenv partner-sysid`

+
Se il partner-sysid non è corretto, impostarlo:

+
`setenv partner-sysid <partner-sysID>`

. Se viene utilizzata la crittografia root, selezionare nuovamente l'opzione del menu di avvio per la configurazione della gestione delle chiavi.
+
|===


| Se si utilizza... | Selezionare questa opzione del menu di avvio... 


 a| 
Gestione delle chiavi integrata
 a| 
Opzione `10`

Seguire le istruzioni per fornire gli input necessari per ripristinare la configurazione di gestione delle chiavi.



 a| 
Gestione esterna delle chiavi
 a| 
Opzione "`11`"

Seguire le istruzioni per fornire gli input necessari per ripristinare la configurazione di gestione delle chiavi.

|===
+
A seconda dell'impostazione del gestore delle chiavi, eseguire la procedura di ripristino selezionando l'opzione "`10`" o l'opzione "`11`", quindi l'opzione `6` al primo prompt del menu di avvio. Per avviare completamente i nodi, potrebbe essere necessario ripetere la procedura di ripristino, continua con l'opzione "`1`" (boot normale).

. Attendere l'avvio dei nodi sostituiti.
+
Se uno dei nodi è in modalità Takeover, eseguire un giveback utilizzando `storage failover giveback` comando.

. Se viene utilizzata la crittografia, ripristinare le chiavi utilizzando il comando corretto per la configurazione di gestione delle chiavi.
+
|===


| Se si utilizza... | Utilizzare questo comando... 


 a| 
Gestione delle chiavi integrata
 a| 
`security key-manager onboard sync`

Per ulteriori informazioni, vedere https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["Ripristinare le chiavi di crittografia integrate per la gestione delle chiavi"^].



 a| 
Gestione esterna delle chiavi
 a| 
`security key-manager external restore -vserver <SVM> -node <node> -key-server <host_name|IP_address:port> -key-id key_id -key-tag key_tag <node_name>`

Per ulteriori informazioni, vedere https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["Ripristinare le chiavi di crittografia esterne per la gestione delle chiavi"^].

|===
. Verificare che tutte le porte si trovino in un dominio di trasmissione:
+
.. Visualizzare i domini di trasmissione:
+
`network port broadcast-domain show`

.. Se viene creato un nuovo dominio di broadcast per le porte dati sui controller aggiornati di recente, eliminare il dominio di broadcast:
+

NOTE: Eliminare solo il nuovo dominio di trasmissione. Non eliminare nessuno dei domini di broadcast esistenti prima di iniziare l'aggiornamento.

+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`

.. Aggiungere porte a un dominio di broadcast in base alle esigenze.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["Aggiungere o rimuovere porte da un dominio di broadcast"^]

.. Ricreare VLAN e gruppi di interfacce in base alle esigenze.
+
L'appartenenza alla VLAN e al gruppo di interfacce potrebbe essere diversa dal nodo precedente.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["Creare un VLAN"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["Combinine porte fisiche per creare gruppi di interfacce"^]







== Verificare e ripristinare la configurazione LIF

Verificare che i file LIF siano ospitati su nodi e porte appropriati, come mappati all'inizio della procedura di aggiornamento.

.A proposito di questa attività
* Questa attività viene eseguita sul sito_B.
* Vedere il piano di mappatura delle porte creato in link:upgrade-mcc-ip-prepare-system.html#map-ports-from-the-old-nodes-to-the-new-nodes["Mappare le porte dai vecchi nodi ai nuovi nodi"].



CAUTION: Prima di eseguire uno switchback, devi verificare che la posizione delle LIF dati sia corretta sui nuovi nodi. Quando si esegue il switchback della configurazione, ONTAP tenta di riprendere il traffico sulla porta home utilizzata dalle LIF. Il guasto i/o può verificarsi quando la connessione della porta principale alla porta dello switch e alla VLAN non è corretta.

.Fasi
. Verificare che le LIF siano ospitate nel nodo e nelle porte appropriate prima del switchback.
+
.. Passare al livello di privilegio avanzato:
+
`set -privilege advanced`

.. Visualizza le LIF e conferma che ogni LIF dati sta utilizzando la porta home corretta:
+
`network interface show`

.. Modificare le LIF che non utilizzano la porta home corretta:
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
Se il comando restituisce un errore, è possibile ignorare la configurazione della porta:

+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`

+
Quando si immette il comando di modifica dell'interfaccia di rete in `vserver config override` non è possibile utilizzare la funzione di completamento automatico della scheda. È possibile creare la rete `interface modify` utilizzando il completamento automatico e quindi racchiuderlo in `vserver config override` comando.

.. Verificare che tutte le LIF dati si trovino sulla porta home corretta:
+
`network interface show`

.. Tornare al livello di privilegio admin:
+
`set -privilege admin`



. Ripristinare le interfacce nel nodo principale:
+
`network interface revert * -vserver <svm-name>`

+
Eseguire questo passaggio su tutte le SVM secondo necessità.



.Quali sono le prossime novità?
link:upgrade-mcc-ip-manual-switchback.html["Switchback della configurazione MetroCluster"].
