---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 'Gli aggiornamenti ai sistemi introdotti in ONTAP 9.15.1 o versioni successive richiedono l"impostazione di un bootarg prima di procedere con l"aggiornamento.' 
---
= Impostare il bootarg richiesto (per gli aggiornamenti MetroCluster IP ai sistemi introdotti in ONTAP 9.15.1 o versioni successive)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli aggiornamenti ai sistemi introdotti in ONTAP 9.15.1 o versioni successive richiedono di impostare un bootarg sui vecchi controller prima di poter avviare l'aggiornamento.


NOTE: È necessario impostare il bootarg richiesto su tutti i vecchi nodi in entrambi i siti prima di avviare l'aggiornamento.



== Passo 1: Determinare il bootarg da impostare sui vecchi controller

Tutti gli aggiornamenti supportati ai seguenti sistemi richiedono di impostare un bootarg sui vecchi controller prima di eseguire l'aggiornamento del controller:

* AFF A70, AFF A90, AFF A1K
* FAS70, FAS90
* AFF C80
* AFF A50, AFF A20, AFF A30
* AFF C30, AFF C60
* FAS50



CAUTION: Se si sta eseguendo l'aggiornamento a uno dei sistemi elencati, è *necessario* impostare un bootarg richiesto sul sistema esistente prima di eseguire l'aggiornamento. Per tutti gli altri aggiornamenti, è possibile saltare questa attività e passare direttamente a link:upgrade-mcc-ip-system-controller-replace-prechecks.html["Preparare il sistema per l'aggiornamento"].

La maggior parte degli aggiornamenti ai sistemi introdotti in ONTAP 9.15.1 o versioni successive richiedono di impostare il `hw.cxgbe.toe_keepalive_disable` bootarg sui vecchi controller. Tuttavia, alcuni percorsi di aggiornamento richiedono invece di impostare il `bootarg.siw.interop_enabled` bootarg.

Utilizzare la tabella seguente per determinare quale bootarg impostare per la combinazione di aggiornamento specifica.

[cols="2*"]
|===
| Per questo aggiornamento... | Impostare il bootarg... 


| Da AFF A250 a AFF A30 | `bootarg.siw.interop_enabled` 


| Da AFF C250 a AFF C30 | `bootarg.siw.interop_enabled` 


| Da AFF A150 a AFF A20 | `bootarg.siw.interop_enabled` 


| Da AFF A220 a AFF A20 | `bootarg.siw.interop_enabled` 


| Tutti gli altri aggiornamenti supportati per i sistemi AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A30, AFF C30, AFF C60 o FAS50 | `hw.cxgbe.toe_keepalive_disable` 
|===


== Fase 2: Impostare il bootarg richiesto sui vecchi controller

Questa attività è *solo* necessaria quando si esegue l'aggiornamento a un sistema AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A20, AFF A30, AFF C30, AFF C60 o FAS50.

.Fasi
. Arrestare un nodo in entrambi i siti e consentire al partner ha di eseguire un takeover dello storage del nodo:
+
`halt  -node <node_name>`

. Impostare il bootarg richiesto per la combinazione di aggiornamento. È già stato determinato il bootarg che è necessario impostare utilizzando la tabella in <<upgrade_paths_bootarg_assisted,determinare il bootarg da impostare>>.
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
.. Al `LOADER` prompt del nodo arrestato, immettere quanto segue:
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
`saveenv`

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. Al `LOADER` prompt del nodo arrestato, immettere quanto segue:
+
`setenv bootarg.siw.interop_enabled 1`

+
`saveenv`

+
`printenv bootarg.siw.interop_enabled`



--
====
. Avviare il nodo:
+
`boot_ontap`

. All'avvio del nodo, eseguire un giveback per il nodo quando richiesto:
+
`storage failover giveback -ofnode <node_name>`

. Ripetere la procedura su tutti e quattro i nodi del gruppo DR che si sta aggiornando.


.Cosa succederà
link:upgrade-mcc-ip-system-controller-replace-prechecks.html["Preparare il sistema per l'aggiornamento"].
