---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-console-logging.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 'Abilitare la registrazione della console sui dispositivi prima di eseguire l"aggiornamento del controller.' 
---
= Attivare la registrazione della console prima dell'aggiornamento dell'IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Abilitare la registrazione della console sui dispositivi prima di eseguire l'aggiornamento del controller.

NetApp consiglia vivamente di attivare la registrazione della console sui dispositivi in uso e di eseguire le seguenti operazioni quando si esegue questa procedura:

* Lasciare attivato AutoSupport durante la manutenzione.
* Attivare un messaggio AutoSupport di manutenzione prima e dopo la manutenzione per disattivare la creazione del caso per tutta la durata dell'attività di manutenzione.
+
Consultare l'articolo della Knowledge base link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Come eliminare la creazione automatica del caso durante le finestre di manutenzione pianificata"^].

* Abilita la registrazione della sessione per qualsiasi sessione CLI. Per istruzioni su come attivare la registrazione della sessione, consultare la sezione "registrazione dell'output della sessione" nell'articolo della Knowledge base link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare Putty per una connettività ottimale ai sistemi ONTAP"^].


.Quali sono le prossime novità?
Esaminare le informazioni in link:upgrade-mcc-ip-system-controller-replace-set-bootarg.html["Impostare il bootarg richiesto (per gli aggiornamenti ai sistemi introdotti nella versione 9.15.1 o successiva)"] per confermare se è necessario impostare un bootarg richiesto sul sistema esistente.
