---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 'Gli aggiornamenti ai sistemi introdotti in ONTAP 9.15.1 o versioni successive richiedono l"impostazione di un bootarg prima di procedere con l"aggiornamento.' 
---
= Impostare il bootarg richiesto (per gli aggiornamenti MetroCluster IP ai sistemi introdotti in ONTAP 9.15.1 o versioni successive)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si esegue l'aggiornamento a un sistema introdotto in ONTAP 9.15.1 o versione successiva, solitamente è necessario impostare un bootarg sui vecchi controller prima di poter avviare l'aggiornamento.


NOTE: Se la combinazione di aggiornamento è interessata, per un aggiornamento riuscito è necessario impostare un bootarg su tutti i vecchi controller.  Esaminare attentamente le informazioni contenute in questa sezione per verificare se la combinazione di aggiornamento richiede l'impostazione di un bootarg e come impostare il bootarg corretto per la combinazione.



== Passaggio 1: determinare se è necessario impostare un bootarg sui vecchi controller

Prima di iniziare l'upgrade, determina se è necessario impostare un bootarg sui vecchi controller utilizzando le seguenti informazioni:

* *È necessario* impostare un bootarg sui vecchi controller per gli aggiornamenti supportati sui seguenti sistemi, salvo diversa indicazione:
+
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60
** FAS50


* *Non* è necessario impostare alcun bootarg sui vecchi controller se l'aggiornamento è una delle seguenti combinazioni:
+
** Da un sistema AFF A70 a un sistema AFF A90
** Da un sistema FAS70 a un sistema FAS90





CAUTION: Se l'upgrade non richiede di impostare alcun bootarg, puoi saltare questa operazione e andare direttamente a link:upgrade-mcc-ip-system-controller-replace-prechecks.html["Preparare il sistema per l'aggiornamento"].



== Passaggio 2: determina il bootarg che devi impostare sui vecchi controller

La maggior parte degli aggiornamenti interessati richiedono di impostare `hw.cxgbe.toe_keepalive_disable` bootarg sui vecchi controller.  Tuttavia, alcuni percorsi di aggiornamento richiedono di impostare `bootarg.siw.interop_enabled` bootarg invece.

Utilizzare la tabella seguente per determinare quale bootarg impostare per la combinazione di aggiornamento specifica.

[cols="2*"]
|===
| Per questo aggiornamento... | Impostare il bootarg... 


| Da AFF A250 a AFF A30 | `bootarg.siw.interop_enabled` 


| Da AFF C250 a AFF C30 | `bootarg.siw.interop_enabled` 


| Da AFF A150 a AFF A20 | `bootarg.siw.interop_enabled` 


| Da AFF A220 a AFF A20 | `bootarg.siw.interop_enabled` 


 a| 
Tutti gli altri aggiornamenti ai sistemi AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A30, AFF C30, AFF C60 o FAS50

*Nota:* non è necessario impostare alcun bootarg se l'aggiornamento avviene da un sistema AFF A70 a un sistema AFF A90 o da un sistema FAS70 a un sistema FAS90.
| `hw.cxgbe.toe_keepalive_disable` 
|===


== Passaggio 3: impostare il bootarg richiesto sui vecchi controller

Dopo aver determinato il bootarg richiesto per la tua combinazione di aggiornamento, segui i passaggi per impostare il bootarg sui vecchi controller.


NOTE: Prima di avviare l'aggiornamento, è necessario impostare bootarg su tutti i vecchi nodi in entrambi i siti.

.Fasi
. Arrestare un nodo in entrambi i siti e consentire al partner ha di eseguire un takeover dello storage del nodo:
+
`halt  -node <node_name>`

. Impostare il bootarg richiesto per la combinazione di aggiornamento. È già stato determinato il bootarg che è necessario impostare utilizzando la tabella in <<upgrade_paths_bootarg_assisted,determinare il bootarg da impostare>>.
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
.. Al `LOADER` prompt del nodo arrestato, immettere quanto segue:
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
`saveenv`

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. Al `LOADER` prompt del nodo arrestato, immettere quanto segue:
+
`setenv bootarg.siw.interop_enabled 1`

+
`saveenv`

+
`printenv bootarg.siw.interop_enabled`



--
====
. Avviare il nodo:
+
`boot_ontap`

. All'avvio del nodo, eseguire un giveback per il nodo quando richiesto:
+
`storage failover giveback -ofnode <node_name>`

. Ripetere la procedura su tutti e quattro i nodi del gruppo DR che si sta aggiornando.


.Cosa succederà
link:upgrade-mcc-ip-system-controller-replace-prechecks.html["Preparare il sistema per l'aggiornamento"].
