---
permalink: tiebreaker/reference_where_to_find_additional_information_tb_icg.html 
sidebar: sidebar 
keywords: metrocluster, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: Scopri di più sulla configurazione e sul funzionamento di MetroCluster. 
---
= Dove trovare ulteriori informazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri di più sulla configurazione e sul funzionamento di MetroCluster.



== MetroCluster e informazioni varie

|===


| Informazioni | Soggetto 


 a| 
link:../index.html["Documentazione MetroCluster"]
 a| 
* Tutte le informazioni MetroCluster




 a| 
http://www.netapp.com/us/media/tr-4375.pdf["Report tecnico NetApp 4375: NetApp MetroCluster per ONTAP 9.3"^]
 a| 
* Panoramica tecnica della configurazione e del funzionamento di MetroCluster.
* Best practice per la configurazione di MetroCluster.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installazione e configurazione di Fabric-Attached MetroCluster"]
 a| 
* Architettura Fabric-Attached MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione degli switch FC
* Configurazione di MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["Estensione dell'installazione e della configurazione di MetroCluster"]
 a| 
* Estendi l'architettura MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione di MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["Installazione e configurazione di MetroCluster IP"]
 a| 
* Architettura IP di MetroCluster
* Collegamento della configurazione IP di MetroCluster
* Configurazione di MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["Gestire i componenti di MetroCluster"]
 a| 
* Linee guida per la manutenzione in una configurazione MetroCluster
* Procedure di sostituzione o aggiornamento dell'hardware e aggiornamento del firmware per bridge FC-SAS e switch FC
* Aggiunta a caldo di uno shelf di dischi in una configurazione Fabric-Attached o Stretch MetroCluster
* Rimozione a caldo di uno shelf di dischi in una configurazione Fabric-Attached o Stretch MetroCluster
* Sostituzione dell'hardware in un sito di emergenza in una configurazione MetroCluster con connessione fabric o stretch
* Espansione di una configurazione MetroCluster a due nodi collegata a fabric o estesa a una configurazione MetroCluster a quattro nodi.
* Espansione di una configurazione fabric-attached o stretch MetroCluster a quattro nodi in una configurazione MetroCluster a otto nodi.




 a| 
Documentazione Active IQ Unified Manager

https://docs.netapp.com["Documentazione NetApp: Guide e risorse sui prodotti"^]
 a| 
* Monitoraggio della configurazione e delle prestazioni di MetroCluster




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Transizione basata sulla copia"]
 a| 
* Transizione dei dati dai sistemi storage 7-Mode ai sistemi storage in cluster


|===