---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: Per utilizzare SNMP con il software Tiebreaker, è necessario configurare le impostazioni SNMP. 
---
= Configurazione delle impostazioni SNMP per il software Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare SNMP con il software Tiebreaker, è necessario configurare le impostazioni SNMP.

. Utilizzare l'interfaccia CLI di tiebreaker `snmp config wizard` Comando per aggiungere configurazioni MetroCluster.
+

NOTE: Al momento è supportato un solo host trap SNMP.

+
L'esempio seguente mostra la configurazione di un ricevitore SNMP che supporta SNMP V3 con un indirizzo IP 10.240.45.66 e il numero di porta 162 per i messaggi trap. Il software Tiebreaker è pronto per inviare trap al ricevitore SNMP specificato.

+
....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version[V1/V3]: v3
Enter SNMP Host: 10.240.45.66
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
Enter SNMP V3 Privacy password:
Engine ID : 8000031504932eff571825192a6f1193b265e24593
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
....
+

NOTE: È necessario configurare SNMPv3 perché SNMPv1 non è sicuro. Assicurarsi che la stringa di comunità predefinita sia *NOT* impostata su public.

. Verificare che le impostazioni SNMP siano configurate:
+
`snmp config test`

+
L'esempio seguente mostra che il software di spareggio può inviare una trap SNMP per l'evento TEST_SNMP_CONFIG:

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V1.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

