---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: 'Quando si pianifica la configurazione MetroCluster per l"utilizzo con dischi e LUN di array, è necessario prendere in considerazione diversi fattori, come l"ordine di impostazione dell"accesso allo storage, la posizione dell"aggregato root e l"utilizzo di porte, switch e bridge FC-SAS.' 
---
= Considerazioni sull'implementazione di una configurazione MetroCluster con dischi e LUN di array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si pianifica la configurazione MetroCluster per l'utilizzo con dischi e LUN di array, è necessario prendere in considerazione diversi fattori, come l'ordine di impostazione dell'accesso allo storage, la posizione dell'aggregato root e l'utilizzo di porte, switch e bridge FC-SAS.

Per pianificare la configurazione, prendere in considerazione le informazioni riportate nella seguente tabella:

|===


| Considerazione | Linee guida 


 a| 
Ordine di impostazione dell'accesso allo storage
 a| 
È possibile impostare prima l'accesso a dischi o LUN di array. Prima di configurare l'altro tipo di storage, è necessario completare tutte le operazioni di configurazione per quel tipo di storage e verificare che siano state configurate correttamente.



 a| 
Posizione dell'aggregato root
 a| 
* Se si sta configurando un'implementazione di _new_ MetroCluster con dischi e LUN di array, è necessario creare l'aggregato root sui dischi nativi.
+
Durante questa operazione, assicurarsi che _almeno un_ shelf di dischi (con 24 dischi) sia configurato in ciascuno dei siti.

* Se si aggiungono dischi nativi a una configurazione MetroCluster _esistente_ che utilizza LUN di array, l'aggregato root può rimanere su un LUN di array.




 a| 
Utilizzo di switch e bridge FC-SAS
 a| 
I bridge FC-SAS sono richiesti in configurazioni a quattro nodi e due nodi fabric-attached per collegare i sistemi ONTAP agli shelf di dischi attraverso gli switch.

È necessario utilizzare gli stessi switch per connettersi agli array di storage e ai bridge FC-SAS.



 a| 
Utilizzando le porte FC Initiator
 a| 
Le porte iniziatore utilizzate per il collegamento a un bridge FC-SAS devono essere diverse dalle porte utilizzate per il collegamento agli switch, che si collegano agli array di storage.

Per collegare un sistema ONTAP a dischi e LUN di array sono necessarie almeno otto porte di iniziatore.

|===
.Informazioni correlate
* Le procedure e i comandi di configurazione dello switch sono diversi, a seconda del vendor dello switch.
+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurazione manuale degli switch Brocade FC"]

+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configurazione manuale degli switch Cisco FC"]

* Quando si aggiunge nuovo storage alla configurazione, si installano e cablano i bridge RTO FibreBridge e gli shelf di dischi SAS.
+
link:task_fb_new_install.html["Installazione di bridge FC-SAS e shelf di dischi SAS"]

* Lo zoning dello switch definisce i percorsi tra i nodi connessi. La configurazione dello zoning consente di definire quali LUN di array possono essere visualizzati da un sistema ONTAP specifico.
+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Esempio di zoning dello switch in una configurazione MetroCluster a quattro nodi con LUN array"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Esempio di zoning dello switch in una configurazione MetroCluster a otto nodi con LUN array"]

* https://hwu.netapp.com["NetApp Hardware Universe"]

