---
permalink: install-fc/concept_considerations_7mt.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 'Durante la preparazione all"installazione di MetroCluster, è necessario conoscere l"architettura hardware di MetroCluster e i componenti richiesti.' 
---
= Considerazioni per la transizione da 7-Mode a ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare gli strumenti di transizione per spostare i dati da una configurazione MetroCluster 7-Mode a una configurazione ONTAP, è necessario che la nuova configurazione MetroCluster sia completamente configurata e funzionante. Se la configurazione 7-Mode utilizza switch Brocade 6510, la nuova configurazione può condividere i fabric esistenti per ridurre i requisiti hardware.

Se si dispone di switch Brocade 6510 e si prevede di condividere le fabric dello switch tra 7-Mode Fabric MetroCluster e MetroCluster in esecuzione in ONTAP, è necessario utilizzare la procedura specifica per la configurazione dei componenti MetroCluster.

link:task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html["Configurazione dell'hardware MetroCluster per la condivisione di un fabric FC Brocade 6510 7-Mode durante la transizione"]
