---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html 
sidebar: sidebar 
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster 
summary: Quando si utilizzano ONTAP 9.1 e versioni successive, verificare di utilizzare le assegnazioni delle porte specificate quando si cablano gli switch FC. 
---
= Assegnazioni delle porte per switch FC quando si utilizzano sistemi AFF A900 o FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si utilizzano ONTAP 9.10.1 e versioni successive, verificare di utilizzare le assegnazioni delle porte specificate quando si cablano gli switch FC.

È possibile riconfigurare le porte non utilizzate per il collegamento di porte initiator, porte FC-VI o ISL in modo da fungere da porte di storage. Tuttavia, se vengono utilizzati gli RCF supportati, la zoning deve essere modificata di conseguenza.

Se si utilizzano gli RCF supportati, le porte ISL potrebbero non connettersi alle stesse porte mostrate e potrebbe essere necessario riconfigurarle manualmente.

Se gli switch sono stati configurati utilizzando le assegnazioni delle porte per ONTAP 9, è possibile continuare a utilizzare le assegnazioni precedenti. Tuttavia, le nuove configurazioni che eseguono ONTAP 9.1 o versioni successive devono utilizzare le assegnazioni delle porte indicate di seguito.



== Linee guida generali per il cablaggio

Quando si utilizzano le tabelle di cablaggio, è necessario conoscere le seguenti linee guida:

* I sistemi storage AFF A900 o FAS9500 richiedono otto porte FC-VI. Se si utilizza un AFF A900 o FAS9500, è necessario utilizzare la configurazione a otto porte. Se la configurazione include gli altri modelli di sistemi di storage, utilizzare i cavi mostrati nelle tabelle ma ignorare i cavi delle porte FC-VI non necessarie.
* Se si dispone di due configurazioni MetroCluster che condividono gli ISL, utilizzare le stesse assegnazioni delle porte di un cablaggio MetroCluster a otto nodi.
* Il numero di ISL che si cablano può variare a seconda dei requisiti del sito.
* Consultare la sezione relativa alle considerazioni sull'ISL.
+
link:concept_considerations_isls_mcfc.html["Considerazioni per gli ISL"]


