---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: È possibile configurare i sistemi FAS8020, AFF8020, FAS8200 e AFF A300 utilizzando una singola porta iniziatore per ciascun fabric e due porte iniziatore per ciascun controller. 
---
= Assegnazioni delle porte per i sistemi che utilizzano due porte initiator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare i sistemi FAS8200 e AFF A300 utilizzando una singola porta iniziatore per ogni fabric e due porte iniziatore per ogni controller.

È possibile seguire il cablaggio del bridge FibreBridge 7600N utilizzando una sola porta FC (FC1 o FC2). Invece di utilizzare quattro iniziatori, collegarne solo due e lasciare vuoti gli altri due collegati alla porta dello switch.

Se la suddivisione in zone viene eseguita manualmente, seguire la suddivisione in zone utilizzata per un bridge FibreBridge 7600N che utilizza una porta FC (FC1 o FC2). In questo scenario, a ciascun elemento di zona per fabric viene aggiunta una porta di avvio anziché due.

È possibile modificare la suddivisione in zone o eseguire un aggiornamento da FibreBridge 6500N a FibreBridge 7500N utilizzando la procedura descritta in link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["Scambio a caldo di un bridge FibreBridge 6500N con un bridge FibreBridge 7600N o 7500N"].

La tabella seguente mostra le assegnazioni delle porte per gli switch Brocade FC quando si utilizza una singola porta iniziatore per ogni fabric e due porte iniziatore per ogni controller.

[cols="2a,2a,2a,2a"]
|===
4+| Configurazioni che utilizzano FibreBridge 7500N o 7600N utilizzando una sola porta FC (FC1 o FC2) 


 a| 
*MetroCluster 1 o DR Group 1*



 a| 
*Componente*
 a| 
*Porta*
 a| 
*6505, 6510, 6520, 7840, G620, G630, G610, G710, G720, G730 e DCX 8510-8*



 a| 
*Si collega allo switch FC...*
 a| 
*Si collega alla porta dello switch...*



 a| 
controller_x_1
 a| 
Porta FC-VI A.
 a| 
1
 a| 
0



 a| 
Porta FC-VI b
 a| 
2
 a| 
0



 a| 
Porta FC-VI c
 a| 
1
 a| 
1



 a| 
Porta FC-VI d
 a| 
2
 a| 
1



 a| 
Porta HBA a
 a| 
1
 a| 
2



 a| 
Porta HBA b
 a| 
2
 a| 
2



 a| 
Porta HBA c
 a| 
-
 a| 
-



 a| 
Porta HBA d
 a| 
-
 a| 
-



 a| 
Stack 1
 a| 
bridge_x_1a
 a| 
1
 a| 
8



 a| 
bridge_x_1b
 a| 
2
 a| 
8



 a| 
Stack y
 a| 
bridge_x_ya
 a| 
1
 a| 
11



 a| 
bridge_x_yb
 a| 
2
 a| 
11

|===