---
permalink: install-fc/concept_considerations_when_removing_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, remove, configuration, disk connectivity, interconnects, adjust 
summary: È possibile rimuovere la configurazione MetroCluster da tutti i nodi della configurazione MetroCluster o da tutti i nodi di un gruppo di disaster recovery. 
---
= Considerazioni sulla rimozione delle configurazioni MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere la configurazione MetroCluster da tutti i nodi della configurazione MetroCluster o da tutti i nodi di un gruppo di disaster recovery (DR). Dopo aver rimosso la configurazione MetroCluster, tutte le interconnessioni e la connettività dei dischi devono essere regolate in modo da essere supportate. Per rimuovere la configurazione MetroCluster, contattare il supporto tecnico.


IMPORTANT: Non è possibile annullare la configurazione di MetroCluster. Questo processo deve essere eseguito solo con l'assistenza del supporto tecnico. Contattare il supporto tecnico NetApp e consultare la guida appropriata per la configurazione dal link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_remove_nodes_from_a_MetroCluster_configuration_-_Resolution_Guide["Come rimuovere i nodi da una configurazione MetroCluster - Guida alla risoluzione."^]
