---
permalink: install-fc/concept_implementing_a_mcc_configuration_with_both_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, implement, configuration, disks, array, luns 
summary: Per implementare una configurazione MetroCluster con dischi e LUN di array nativi, è necessario assicurarsi che i sistemi ONTAP utilizzati nella configurazione possano essere collegati agli array di storage. 
---
= Implementazione di una configurazione MetroCluster con dischi e LUN di array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per implementare una configurazione MetroCluster con dischi e LUN di array nativi, è necessario assicurarsi che i sistemi ONTAP utilizzati nella configurazione possano essere collegati agli array di storage.

Una configurazione MetroCluster con dischi e LUN di array può avere due o quattro nodi. Sebbene la configurazione MetroCluster a quattro nodi debba essere fabric-attached, la configurazione a due nodi può essere estensibile o fabric-attached.

In https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp (IMT)"], È possibile utilizzare il campo soluzione storage per selezionare la soluzione MetroCluster. Utilizzare *Esplora componenti* per selezionare i componenti e la versione di ONTAP per perfezionare la ricerca. È possibile fare clic su *Mostra risultati* per visualizzare l'elenco delle configurazioni supportate che corrispondono ai criteri.

.Informazioni correlate
Per configurare una configurazione MetroCluster con collegamento a fabric a due nodi o una configurazione MetroCluster a quattro nodi con dischi e LUN di array nativi, è necessario utilizzare bridge FC-SAS per collegare i sistemi ONTAP agli shelf di dischi attraverso gli switch FC. È possibile collegare i LUN degli array ai sistemi ONTAP attraverso gli switch FC.

link:reference_example_of_a_two_node_fabric_attached_mcc_configuration_with_disks_and_array_luns.html["Esempio di una configurazione MetroCluster a due nodi collegata al fabric con dischi e LUN di array"]

link:concept_example_of_a_four_node_mcc_configuration_with_disks_and_array_luns.html["Esempio di configurazione MetroCluster a quattro nodi con dischi e LUN di array"]
