---
permalink: install-fc/concept_considerations_8510.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 'Durante la preparazione all"installazione di MetroCluster, è necessario conoscere l"architettura hardware di MetroCluster e i componenti richiesti.' 
---
= Requisiti per l'utilizzo di uno switch Brocade DCX 8510-8
:allow-uri-read: 


* Gli switch DCX 8510-8 utilizzati nelle configurazioni MetroCluster devono essere acquistati da NetApp.
* Per la scalabilità, è necessario lasciare un blocco di porte tra le configurazioni MetroCluster se si collegano solo due MetroClusters in moduli a 4 porte. Ciò consente di espandere l'utilizzo delle porte nelle configurazioni MetroCluster senza doverlo riabilitare.
* Ogni switch Brocade DCX 8510-8 nella configurazione MetroCluster deve essere configurato correttamente per le porte ISL e le connessioni storage. Per l'utilizzo delle porte, consultare la seguente sezione: link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Assegnazioni delle porte per gli switch FC quando si utilizza ONTAP 9.1 e versioni successive"].
* Gli MetroCluster non possono essere condivisi e ogni ISL richiede due ISL per ogni fabric.
* Lo switch DCX 8510-8 utilizzato per la connettività MetroCluster back-end non deve essere utilizzato per altre connessioni.
+
I dispositivi non MetroCluster non devono essere collegati a questi switch e il traffico non MetroCluster non deve passare attraverso gli switch DCX 8510-8.

* Una scheda di linea può essere collegata a MetroClusters * ONTAP o * MetroClusters 7-Mode ONTAP.



NOTE: I file RCF non sono disponibili per questo switch.

Di seguito sono riportati i requisiti per l'utilizzo di due switch Brocade DCX 8510-8:

* È necessario disporre di uno switch DCX 8510-8 in ogni sito.
* È necessario utilizzare almeno due blade a 48 porte che contengono 16 GB di SFP in ogni switch.


Di seguito sono riportati i requisiti per l'utilizzo di quattro switch DCX 8510-8 in ogni sito in una configurazione MetroCluster:

* È necessario disporre di due switch DCX 8510-8 per ciascun sito.
* È necessario utilizzare almeno un blade a 48 porte per ogni switch DCX 8510-8.
* Ogni blade viene configurato come switch virtuale utilizzando fabric virtuali.


Gli switch Brocade DCX 8510-8 non supportano i seguenti prodotti NetApp:

* Config Advisor
* Fabric Health Monitor
* MyAutoSupport (i rischi del sistema potrebbero mostrare falsi positivi)
* Active IQ Unified Manager (in precedenza Unified Manager di OnCommand)



NOTE: Assicurarsi che tutti i componenti necessari per questa configurazione si trovino in https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]. Per informazioni sulle configurazioni supportate, consultare la sezione delle note del tool Interoperability Matrix.
