---
permalink: install-fc/reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, switch, zoning, array, luns, requirements 
summary: Quando si utilizza lo zoning dello switch in una configurazione MetroCluster con LUN array, è necessario assicurarsi che vengano rispettati alcuni requisiti di base. 
---
= Requisiti per lo zoning dello switch in una configurazione MetroCluster con LUN array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si utilizza lo zoning dello switch in una configurazione MetroCluster con LUN array, è necessario assicurarsi che vengano rispettati alcuni requisiti di base.

I requisiti per lo zoning dello switch in una configurazione MetroCluster con LUN array sono i seguenti:

* La configurazione di MetroCluster deve seguire lo schema di zoning da singolo iniziatore a destinazione singola.
+
La zoning da singolo iniziatore a destinazione singola limita ogni zona a una singola porta FC Initiator e a una singola porta di destinazione.

* Le porte FC-VI devono essere zonate end-to-end nel fabric.
* La condivisione di più porte initiator con una singola porta di destinazione può causare problemi di performance.
+
Analogamente, la condivisione di più porte di destinazione con una singola porta iniziatore può causare problemi di performance.

* È necessario aver eseguito una configurazione di base degli switch FC utilizzati nella configurazione MetroCluster.
+
** link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configurare manualmente gli switch Cisco FC"]
** link:ask_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurare manualmente gli switch FC Brocade"]






== Supporto di iniziatore condiviso e destinazione condivisa per la configurazione MetroCluster con LUN array

La possibilità di condividere una data porta FC Initiator o una data porta di destinazione è utile per le organizzazioni che desiderano ridurre al minimo il numero di porte initiator o di destinazione utilizzate. Ad esempio, un'organizzazione che prevede un basso utilizzo di i/o su una porta FC Initiator o su porte di destinazione potrebbe preferire condividere la porta FC Initiator o le porte di destinazione invece di dedicare ciascuna porta FC Initiator a una singola porta di destinazione.

Tuttavia, la condivisione delle porte iniziatore o di destinazione può influire negativamente sulle prestazioni.

.Informazioni correlate
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_support_Shared_Initiator_and_Shared_Target_configuration_with_Array_LUNs_in_a_MetroCluster_environment["Come supportare la configurazione Shared Initiator e Shared Target con LUN array in un ambiente MetroCluster"]

* Lo zoning dello switch definisce i percorsi tra i nodi connessi. La configurazione dello zoning consente di definire quali LUN di array possono essere visualizzati da specifici sistemi ONTAP.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["Esempio di zoning dello switch in una configurazione MetroCluster a due nodi con LUN array"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Esempio di zoning dello switch in una configurazione MetroCluster a quattro nodi con LUN array"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Esempio di zoning dello switch in una configurazione MetroCluster a otto nodi con LUN array"]


