---
permalink: install-fc/reference_supported_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, supported, array, luns 
summary: È possibile impostare una configurazione MetroCluster con LUN array. Sono supportate le configurazioni stretch e fabric-attached. I sistemi AFF non sono supportati con i LUN degli array. 
---
= Configurazione MetroCluster supportata con LUN array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile impostare una configurazione MetroCluster con LUN array. Sono supportate le configurazioni stretch e fabric-attached. I sistemi AFF non sono supportati con i LUN degli array.

Le funzioni supportate nelle configurazioni MetroCluster variano in base ai tipi di configurazione. La seguente tabella elenca le funzionalità supportate dai diversi tipi di configurazioni MetroCluster con LUN array:

|===


.2+| Funzione 3+| Configurazioni fabric-attached | Configurazioni di estensione 


| Otto nodi | Quattro nodi | A due nodi | A due nodi 


 a| 
Numero di controller
 a| 
Otto
 a| 
Quattro
 a| 
Due
 a| 
Due



| Utilizza un fabric storage switch FC | Sì | Sì | Sì | Sì 


| Utilizza bridge FC-SAS | Sì | Sì | Sì | Sì 


| Supporta ha locale | Sì | Sì | No | No 


| Supporta lo switchover automatico | Sì | Sì | Sì | Sì 
|===
.Informazioni correlate
link:concept_considerations_differences.html["Differenze tra le configurazioni ONTAP MetroCluster"]
