---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: I sistemi ONTAP, gli storage array e gli switch FC utilizzati nelle configurazioni MetroCluster devono soddisfare i requisiti di tali tipi di configurazioni. Inoltre, è necessario considerare i requisiti SyncMirror per le configurazioni MetroCluster con LUN array. 
---
= Requisiti per una configurazione MetroCluster con LUN array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi ONTAP, gli storage array e gli switch FC utilizzati nelle configurazioni MetroCluster devono soddisfare i requisiti di tali tipi di configurazioni. Inoltre, è necessario considerare i requisiti SyncMirror per le configurazioni MetroCluster con LUN array.



== Requisiti per i sistemi ONTAP

* I sistemi ONTAP devono essere identificati come supportati per le configurazioni MetroCluster.
+
In https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp (IMT)"], È possibile utilizzare il campo soluzione storage per selezionare la soluzione MetroCluster. Utilizzare *Esplora componenti* per selezionare i componenti e la versione di ONTAP per perfezionare la ricerca. È possibile fare clic su *Mostra risultati* per visualizzare l'elenco delle configurazioni supportate che corrispondono ai criteri.

+

NOTE: È necessario fare riferimento ai dettagli degli avvisi associati a qualsiasi configurazione selezionata nella matrice di interoperabilità.

* Tutti i sistemi ONTAP in una configurazione MetroCluster devono essere dello stesso modello.
* Gli adattatori FC-VI devono essere installati negli slot appropriati per ciascun sistema ONTAP, a seconda del modello.
+
https://hwu.netapp.com["NetApp Hardware Universe"]





== Requisiti per gli array di storage

* Gli array di storage devono essere identificati come supportati per le configurazioni MetroCluster.
+
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]

* Gli array di storage nella configurazione MetroCluster devono essere simmetrici:
+
** I due array storage devono essere della stessa famiglia di vendor supportati e avere la stessa versione del firmware installata.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["Implementazione della virtualizzazione FlexArray per lo storage NetApp e-Series"]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["Implementazione della virtualizzazione FlexArray per storage di terze parti"]

** I tipi di dischi (ad esempio SATA, SSD o SAS) utilizzati per lo storage mirrorato devono essere gli stessi su entrambi gli array di storage.
** I parametri per la configurazione degli array di storage, come il tipo RAID e il tiering, devono essere gli stessi in entrambi i siti.






== Requisiti per gli switch FC

* Gli switch e il firmware dello switch devono essere identificati come supportati per le configurazioni MetroCluster.
+
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]

* Ogni fabric deve disporre di due switch FC.
* Ogni sistema ONTAP deve essere collegato allo storage utilizzando componenti ridondanti in modo da garantire la ridondanza in caso di guasti al dispositivo e al percorso.
* I sistemi storage AFF A700, FAS9000, AFF A900 e FAS9500 supportano fino a otto ISL per fabric. Altri modelli di sistemi storage supportano fino a quattro ISL per fabric.


Gli switch devono utilizzare la configurazione di base dello switch MetroCluster, le impostazioni ISL e le configurazioni FC-VI.

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Configurazione manuale degli switch FC Cisco o Brocade"]



== Requisiti SyncMirror

* SyncMirror è necessario per una configurazione MetroCluster.
* Per lo storage mirrorato sono necessari due storage array separati, uno per sito.
* Sono necessari due set di LUN array.
+
Un set è richiesto per l'aggregato sull'array di storage locale (pool0) e un altro set è richiesto sull'array di storage remoto per il mirror dell'aggregato (l'altro plex dell'aggregato, pool1).

+
Per eseguire il mirroring dell'aggregato, i LUN dell'array devono avere le stesse dimensioni.

* Nella configurazione di MetroCluster sono supportati anche gli aggregati senza mirror.
+
Non sono protetti in caso di disastro del sito.


