---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, cisco, fc, switch, nx, software 
summary: È necessario scaricare il file del sistema operativo dello switch e il file RCF su ogni switch nella configurazione MetroCluster Fabric. 
---
= Download e installazione del software NX-OS dello switch FC Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario scaricare il file del sistema operativo dello switch e il file RCF su ogni switch nella configurazione MetroCluster Fabric.

.Prima di iniziare
Questa attività richiede un software per il trasferimento dei file, ad esempio FTP, TFTP, SFTP o SCP, per copiare i file sui centralini.

.A proposito di questa attività
Questi passaggi devono essere ripetuti su ciascuno switch FC nella configurazione MetroCluster Fabric.

È necessario utilizzare la versione del software dello switch supportata.

https://hwu.netapp.com["NetApp Hardware Universe"]


NOTE: Le uscite mostrate si riferiscono agli switch IP Cisco; tuttavia, questi passaggi sono applicabili anche agli switch FC Cisco.

.Fasi
. Scaricare il file software NX-OS supportato.
+
https://software.cisco.com/download/home["Pagina di download di Cisco"]

. Copiare il software dello switch sullo switch:
+
`copy sftp://root@server-ip-address/tftpboot/NX-OS-file-name bootflash: vrf management`

+
In questo esempio, il `nxos.7.0.3.I4.6.bin` Il file viene copiato dal server SFTP 10.10.99.99 al bootflash locale:

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. Verificare su ogni switch che i file NX-OS dello switch siano presenti nella directory bootflash di ogni switch:
+
`dir bootflash`

+
L'esempio seguente mostra la presenza dei file su `IP_switch_A_1`:

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Installare il software dello switch:
+
`install all system bootflash:nxos.version-number.bin kickstart bootflash:nxos.version-kickstart-number.bin`

+
[listing]
----
IP_switch_A_1#  install all system bootflash:nxos.7.0.3.I4.6.bin kickstart bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "kickstart".
[####################] 100% -- SUCCESS

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "system".
[####################] 100% -- SUCCESS

Performing module support checks.                                                                                                            [####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Extracting "system" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Extracting "kickstart" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS
...
----
+
Lo switch si riavvia automaticamente dopo l'installazione del software dello switch.

. Attendere che lo switch si ricarichi, quindi accedere allo switch.
+
Una volta riavviato lo switch, viene visualizzato il prompt di login:

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. Verificare che il software dello switch sia stato installato:
+
`show version`

+
L'esempio seguente mostra l'output:

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. Ripetere questa procedura sugli altri tre switch FC nella configurazione MetroCluster Fabric.

