---
permalink: install-fc/task_cable_storage_arrays_to_fc_switches_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, storage, arrays, fc, switches, configuration 
summary: È necessario collegare gli array di storage agli switch FC in modo che i sistemi ONTAP nella configurazione MetroCluster possano accedere a un LUN di array specifico attraverso almeno due percorsi. 
---
= Cablaggio degli array di storage agli switch FC in una configurazione MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario collegare gli array di storage agli switch FC in modo che i sistemi ONTAP nella configurazione MetroCluster possano accedere a un LUN di array specifico attraverso almeno due percorsi.

.Prima di iniziare
* Gli array di storage devono essere configurati per presentare le LUN degli array a ONTAP.
* I controller ONTAP devono essere collegati agli switch FC.
* Gli ISL devono essere cablati tra gli switch FC nei siti MetroCluster.
* È necessario ripetere questa attività per ciascun array di storage in entrambi i siti MetroCluster.
* È necessario collegare i controller in una configurazione MetroCluster agli array di storage tramite switch FC.


.Fasi
. Collegare le porte dello storage array alle porte dello switch FC.
+
In ogni sito, collegare le coppie di porte ridondanti nell'array di storage agli switch FC su fabric alternativi. Ciò fornisce ridondanza nei percorsi per l'accesso alle LUN dell'array.



.Informazioni correlate
* La configurazione dello zoning dello switch consente di definire quali LUN di array possono essere visualizzati da uno specifico sistema ONTAP nella configurazione MetroCluster.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["Zoning dello switch in una configurazione MetroCluster con LUN array"]

* In una configurazione MetroCluster con LUN array, è necessario collegare le porte dello storage array che formano una coppia di porte ridondanti a switch FC alternativi.
+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_two_node_mcc_configuration.html["Esempio di collegamento delle porte dello storage array agli switch FC in una configurazione MetroCluster a due nodi"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_mcc_configuration.html["Esempio di collegamento delle porte dello storage array agli switch FC in una configurazione MetroCluster a quattro nodi"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_mcc_configuration.html["Esempio di collegamento delle porte dello storage array agli switch FC in una configurazione MetroCluster a otto nodi"]


