---
permalink: install-fc/task_reset_the_cisco_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, cisco, fc, switch, factory, defaults 
summary: Prima di installare una nuova versione software e gli RCF, è necessario cancellare la configurazione dello switch Cisco ed eseguire la configurazione di base. 
---
= Ripristino delle impostazioni predefinite dello switch FC Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare una nuova versione software e gli RCF, è necessario cancellare la configurazione dello switch Cisco ed eseguire la configurazione di base.

.A proposito di questa attività
È necessario ripetere questi passaggi su ciascuno switch FC nella configurazione MetroCluster Fabric.


NOTE: Le uscite mostrate si riferiscono agli switch IP Cisco; tuttavia, questi passaggi sono applicabili anche agli switch FC Cisco.

.Fasi
. Ripristinare le impostazioni predefinite dello switch:
+
.. Cancellare la configurazione esistente: +
`*write erase*`
.. Ricaricare il software dello switch: +
`*reload*`
+
Il sistema viene riavviato e viene avviata la configurazione guidata. Durante l'avvio, se viene visualizzato il messaggio Interrompi provisioning automatico e continua con la normale configurazione?(sì/no)[n], dovresti rispondere `*yes*` per procedere.

.. Nella configurazione guidata, immettere le impostazioni di base dello switch:
+
*** Password amministratore
*** Nome dello switch
*** Configurazione della gestione fuori banda
*** Gateway predefinito
*** Servizio SSH (Remote Support Agent).
+
Al termine della configurazione guidata, lo switch si riavvia.



.. Quando richiesto, immettere il nome utente e la password per accedere allo switch.
+
L'esempio seguente mostra i prompt e le risposte del sistema quando si accede allo switch. Le staffe angolari (`*<<<*`) mostra dove inserire le informazioni.

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

    Enter the password for "admin": password  **<<<**
  Confirm the password for "admin": password  **<<<**
         ---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus3000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus3000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.
----
.. Inserire le informazioni di base nel successivo set di prompt, inclusi nome dello switch, indirizzo di gestione e gateway, quindi immettere `*rsa*` Per la chiave SSH come mostrato nell'esempio:
+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
    Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
    Number of rsa key bits <1024-2048> [1024]:
  Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
  Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
L'ultimo set di prompt completa la configurazione:

+
[listing]
----
The following configuration will be applied:
  password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
  no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. Salvare la configurazione:
+
[listing]
----
IP_switch_A_1# copy running-config startup-config
----
. Riavviare lo switch e attendere che lo switch si ricarichi:
+
[listing]
----
IP_switch_A_1# reload
----
. Ripetere i passaggi precedenti sugli altri tre switch nella configurazione MetroCluster Fabric.

