---
permalink: install-fc/task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, hardware, brocade, fc, transition 
summary: Se la configurazione 7-Mode Fabric MetroCluster utilizza switch Brocade 6510, è possibile condividere i fabric switch esistenti con la nuova configurazione Clustered MetroCluster. Fabric switch condivisi significa che la nuova configurazione MetroCluster non richiede un nuovo fabric switch separato. Questa configurazione temporanea è supportata solo con lo switch Brocade 6510 a scopo di transizione. 
---
= Configurazione dell'hardware per la condivisione di un fabric FC Brocade 6510 durante la transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la configurazione 7-Mode Fabric MetroCluster utilizza switch Brocade 6510, è possibile condividere i fabric switch esistenti con la nuova configurazione Clustered MetroCluster. Fabric switch condivisi significa che la nuova configurazione MetroCluster non richiede un nuovo fabric switch separato. Questa configurazione temporanea è supportata solo con lo switch Brocade 6510 a scopo di transizione.

.Prima di iniziare
* 7-Mode Fabric MetroCluster deve utilizzare switch Brocade 6510.
+
Se la configurazione MetroCluster non utilizza attualmente switch Brocade 6510, è necessario aggiornare gli switch a Brocade 6510 prima di utilizzare questa procedura.

* La configurazione 7-Mode Fabric MetroCluster deve utilizzare solo shelf di storage SAS.
+
Se la configurazione esistente include shelf di storage FC (come DS14mk4 FC), la condivisione fabric dello switch FC non è supportata.

* Gli SFP sulle porte dello switch utilizzati dalla nuova configurazione Clustered MetroCluster devono supportare velocità a 16 Gbps.
+
Il fabric MetroCluster 7-Mode esistente può rimanere connesso alle porte utilizzando SFP a 8 Gbps o 16 Gbps.

* Su ciascuno dei quattro switch Brocade 6510, le porte da 24 a 45 devono essere disponibili per collegare le porte dei nuovi componenti MetroCluster.
* Verificare che i collegamenti Inter-Switch (ISL) esistenti si trovino sulle porte 46 e 47.
* Gli switch Brocade 6510 devono eseguire una versione del firmware FOS supportata sia nella configurazione 7-Mode Fabric MetroCluster che in quella Clustered ONTAP MetroCluster.


.Al termine
Dopo aver condiviso il fabric e aver completato la configurazione MetroCluster, è possibile trasferire i dati dalla configurazione 7-Mode Fabric MetroCluster.

Dopo aver effettuato la transizione dei dati, è possibile rimuovere il cablaggio 7-Mode Fabric MetroCluster e, se necessario, spostare il cablaggio Clustered ONTAP MetroCluster sulle porte con numero inferiore precedentemente utilizzate per il cablaggio 7-Mode MetroCluster. Le porte sono illustrate nella sezione "analisi delle assegnazioni delle porte degli switch FC per un MetroCluster a quattro nodi". È necessario regolare lo zoning per le porte ridisposte.

link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Assegnazioni delle porte per gli switch FC quando si utilizza ONTAP 9.1 e versioni successive"]

.Informazioni correlate
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transizione basata sulla copia"]
