---
permalink: install-fc/task_install_the_license_for_us_array_luns_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, license, array, luns, configuration 
summary: È necessario installare la licenza V_StorageAttach su ogni nodo MetroCluster che si desidera utilizzare con le LUN degli array. Non è possibile utilizzare le LUN degli array in un aggregato fino a quando la licenza non viene installata. 
---
= Installazione della licenza per l'utilizzo di LUN array in una configurazione MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare la licenza V_StorageAttach su ogni nodo MetroCluster che si desidera utilizzare con le LUN degli array. Non è possibile utilizzare le LUN degli array in un aggregato fino a quando la licenza non viene installata.

.Prima di iniziare
* Il cluster deve essere installato.
* È necessario disporre della chiave di licenza per la licenza V_StorageAttach.


.A proposito di questa attività
È necessario utilizzare una chiave di licenza separata per ciascun nodo su cui si desidera installare la licenza V_StorageAttach.

.Fasi
. Installare la licenza V_StorageAttach.
+
`system license add`

+
Ripetere questo passaggio per ogni nodo del cluster su cui si desidera installare la licenza.

. Verificare che la licenza V_StorageAttach sia installata su tutti i nodi richiesti in un cluster.
+
`system license show`

+
L'output di esempio seguente mostra che la licenza V_StorageAttach è installata sui nodi di cluster_A:

+
[listing]
----

cluster_A::> system license show
Serial Number: nnnnnnnn
Owner: controller_A_1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage


Serial Number: llllllll
Owner: controller_A_2
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage
----

