---
permalink: install-fc/task_mirror_the_root_aggregates_mcc_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, mirror, root, aggregates 
summary: È necessario eseguire il mirroring degli aggregati root nella configurazione MetroCluster per garantire la protezione dei dati. 
---
= Mirroring degli aggregati root
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario eseguire il mirroring degli aggregati root nella configurazione MetroCluster per garantire la protezione dei dati.

.Prima di iniziare
È necessario assicurarsi che i requisiti SyncMirror per la configurazione MetroCluster con le LUN degli array siano soddisfatti. Fare riferimento a.link:reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html["Requisiti per una configurazione MetroCluster con LUN array"].

.A proposito di questa attività
Ripetere questa operazione per ogni controller nella configurazione MetroCluster.

.Fase
. Eseguire il mirroring dell'aggregato root senza mirror:
+
`storage aggregate mirror`

+
Il seguente comando esegue il mirroring dell'aggregato root per controller_A_1:

+
[listing]
----
controller_A_1::> storage aggregate mirror aggr0_controller_A_1
----
+
L'aggregato root viene mirrorato con LUN di array dal pool1.


