= Attiva la crittografia end-to-end
:allow-uri-read: 


A partire da ONTAP 9.15.1, è possibile configurare la crittografia end-to-end sui sistemi supportati per crittografare il traffico back-end, ad esempio i dati di replicazione NVlog e di storage, tra i siti in una configurazione IP MetroCluster .

.A proposito di questa attività
* Per eseguire questa attività, è necessario essere un amministratore del cluster.
* Prima di poter configurare la crittografia end-to-end, è necessario link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-concept.html["Configurare la gestione esterna delle chiavi"^].
* Esaminare i sistemi supportati e la versione ONTAP minima richiesta per configurare la crittografia end-to-end in una configurazione IP di MetroCluster:
+
[cols="2*"]
|===
| Release ONTAP minima | Sistemi supportati 


 a| 
ONTAP 9.17.1
 a| 
** AFF A800, AFF C800
** AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
** AFF A70, AFF A90, AFF A1K, AFF C80
** FAS50, FAS70, FAS90




 a| 
ONTAP 9.15.1
 a| 
** AFF A400
** FAS8300
** FAS8700


|===




== Attiva la crittografia end-to-end

Per attivare la crittografia end-to-end, procedere come segue.

.Fasi
. Verificare lo stato della configurazione MetroCluster.
+
.. Verificare che i componenti di MetroCluster siano integri:
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run
----
+
L'operazione viene eseguita in background.

.. Dopo il `metrocluster check run` l'operazione è completata, eseguire:
+
[source, cli]
----
metrocluster check show
----
+
Dopo circa cinque minuti, vengono visualizzati i seguenti risultati:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Controllare lo stato dell'operazione di controllo MetroCluster in esecuzione:
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. Verificare che non siano presenti avvisi sullo stato di salute:
+
[source, cli]
----
system health alert show
----


. Verificare che la gestione delle chiavi esterne sia configurata su entrambi i cluster:
+
[source, cli]
----
security key-manager external show-status
----
. Abilita la crittografia end-to-end per ogni gruppo di DR:
+
[source, cli]
----
metrocluster modify -is-encryption-enabled true -dr-group-id <dr_group_id>
----
+
*Esempio*

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled true -dr-group-id 1
Warning: Enabling encryption for a DR Group will secure NVLog and Storage
         replication data sent between MetroCluster nodes and have an impact on
         performance. Do you want to continue? {y|n}: y
[Job 244] Job succeeded: Modify is successful.
----
+
Ripetere questa operazione per ciascun gruppo DR nella configurazione.

. Verificare che la crittografia end-to-end sia abilitata:
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
*Esempio*

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          true
1           cluster_A  node_A_2  configured          true
1           cluster_B  node_B_1  configured          true
1           cluster_B  node_B_2  configured          true
4 entries were displayed.
----




== Disattiva la crittografia end-to-end

Per disattivare la crittografia end-to-end, procedere come segue.

.Fasi
. Verificare lo stato della configurazione MetroCluster.
+
.. Verificare che i componenti di MetroCluster siano integri:
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run

----
+
L'operazione viene eseguita in background.

.. Dopo il `metrocluster check run` l'operazione è completata, eseguire:
+
[source, cli]
----
metrocluster check show
----
+
Dopo circa cinque minuti, vengono visualizzati i seguenti risultati:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Controllare lo stato dell'operazione di controllo MetroCluster in esecuzione:
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. Verificare che non siano presenti avvisi sullo stato di salute:
+
[source, cli]
----
system health alert show
----


. Verificare che la gestione delle chiavi esterne sia configurata su entrambi i cluster:
+
[source, cli]
----
security key-manager external show-status
----
. Disattivare la crittografia end-to-end per ogni gruppo di DR:
+
[source, cli]
----
metrocluster modify -is-encryption-enabled false -dr-group-id <dr_group_id>
----
+
*Esempio*

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled false -dr-group-id 1
[Job 244] Job succeeded: Modify is successful.
----
+
Ripetere questa operazione per ciascun gruppo DR nella configurazione.

. Verificare che la crittografia end-to-end sia disattivata:
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
*Esempio*

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          false
1           cluster_A  node_A_2  configured          false
1           cluster_B  node_B_1  configured          false
1           cluster_B  node_B_2  configured          false
4 entries were displayed.
----

