= 
:allow-uri-read: 


Alcune piattaforme utilizzano una VLAN per l'interfaccia IP di MetroCluster. Per impostazione predefinita, ciascuna delle due porte utilizza una VLAN diversa: 10 e 20.

+ se supportato, è anche possibile specificare una VLAN diversa (non predefinita) superiore a 100 (tra 101 e 4095) utilizzando il `-vlan-id` parametro nel `metrocluster configuration-settings interface create` comando.

+ le seguenti piattaforme *non* supportano il `-vlan-id` parametro:

+ ** FAS8200 e AFF A300 ** AFF A320 ** FAS9000 e AFF A700 ** AFF C800, ASA C800, AFF A800 e ASA A800

+ tutte le altre piattaforme supportano il `-vlan-id` parametro.

+ le assegnazioni VLAN predefinite e valide dipendono dal supporto del parametro da parte della piattaforma `-vlan-id` :

+

[role="tabbed-block"]
====
.Piattaforme che supportano <code>-vlan-</code>
--
VLAN predefinita:

* Quando il `-vlan-id` parametro non è specificato, le interfacce vengono create con VLAN 10 per le porte "A" e VLAN 20 per le porte "B".
* La VLAN specificata deve corrispondere alla VLAN selezionata nell'RCF.


Intervalli VLAN validi:

* VLAN 10 e 20 predefinite
* VLAN 101 e superiori (tra 101 e 4095)


--
.Piattaforme che non supportano <code>-vlan-</code>
--
VLAN predefinita:

* Non applicabile. L'interfaccia non richiede che venga specificata una VLAN sull'interfaccia MetroCluster. La porta dello switch definisce la VLAN utilizzata.


Intervalli VLAN validi:

* Tutte le VLAN non esplicitamente escluse durante la generazione dell'RCF. L'RCF avvisa l'utente se la VLAN non è valida.


--
====