---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= Novità della configurazione MetroCluster per le funzionalità ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni versione del software per la gestione dei dati ONTAP 9 offre funzioni nuove e migliorate che migliorano le capacità, la gestibilità e le prestazioni delle configurazioni ONTAP MetroCluster.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento che interessano le configurazioni di ONTAP MetroCluster, consultare https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

[cols="20,65,15"]
|===
| Funzioni supportate nella configurazione MetroCluster | Descrizione | Inizio disponibile 


 a| 
Supporto di mobilità dei dati SVM per la migrazione delle configurazioni MetroCluster
 a| 
ONTAP supporta la migrazione di una SVM da una coppia ha non MetroCluster a una configurazione MetroCluster o da una configurazione MetroCluster a una coppia ha non MetroCluster. Impossibile migrare una SVM tra configurazioni MetroCluster.

link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["Mobilità dei dati SVM"^]
 a| 
ONTAP 9.16.1



 a| 
Supporto di autenticazione MD5 per i gruppi di peer BGP
 a| 
ONTAP supporta l'autenticazione MD5 sui gruppi di peer BGP per proteggere le sessioni BGP. Quando MD5 è abilitato, le sessioni BGP possono essere stabilite ed elaborate solo tra i peer autorizzati, evitando potenziali interruzioni della sessione da parte di un attore non autorizzato.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Configurare i LIF VIP (Virtual IP)"^]
 a| 
ONTAP 9.16.1



 a| 
Supporto IP MetroCluster per NVMe
 a| 
Il protocollo host front-end NVMe/TCP è supportato sulle configurazioni MetroCluster IP a quattro nodi.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurazioni SAN in un ambiente MetroCluster"^]
 a| 
ONTAP 9.15.1



 a| 
Supporto dello storage a oggetti S3 su aggregati con mirroring e senza mirror
 a| 
È possibile abilitare un server per lo storage a oggetti S3 su una SVM in un aggregato con mirroring o senza mirror nelle configurazioni IP e FC di MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/index.html["Panoramica della configurazione S3"]
 a| 
ONTAP 9.14.1



 a| 
Supporto per il provisioning di un bucket S3 su aggregati con mirroring e senza mirror in un cluster MetroCluster
 a| 
È possibile creare un bucket su un aggregato con mirroring o senza mirror nelle configurazioni di MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["Crea un bucket su un aggregato con mirroring o senza mirror in una configurazione MetroCluster"]
 a| 
ONTAP 9.12.1



 a| 
Supporto IP MetroCluster per NVMe
 a| 
Il protocollo NVMe/FC è supportato sulle configurazioni IP MetroCluster a quattro nodi.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurazioni SAN in un ambiente MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Supporto IPSec per il protocollo host front-end nelle configurazioni fabric-attached MetroCluster IP e MetroCluster
 a| 
Il supporto IPSec per il protocollo host front-end (ad esempio NFS e iSCSI) è disponibile nelle configurazioni MetroCluster IP e MetroCluster fabric-attached.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurare la crittografia IP Security (IPsec) over wire"]
 a| 
ONTAP 9.11.1



 a| 
Gruppi di coerenza
 a| 
I gruppi di coerenza sono supportati nelle configurazioni MetroCluster.
 a| 
ONTAP 9,7



 a| 
Mirroring di FabricPool sulle configurazioni MetroCluster
 a| 
Puoi impostare configurazioni di FabricPool on MetroCluster con mirroring per il tiering dei dati cold su due diverse zone di errore.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["Impostazione degli archivi di oggetti per FabricPool in una configurazione MetroCluster"]
 a| 
ONTAP 9,7



 a| 
Disaster recovery SVM
 a| 
Le Storage Virtual Machine (SVM) attive in una configurazione MetroCluster possono essere utilizzate come origini con la funzionalità di disaster recovery SVM di SnapMirror.
 a| 
ONTAP 9,5

|===