---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= Novità delle funzionalità di MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni versione del software per la gestione dei dati ONTAP 9 offre funzioni nuove e migliorate che migliorano le capacità, la gestibilità e le prestazioni delle configurazioni ONTAP MetroCluster.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento che interessano le configurazioni di ONTAP MetroCluster, consultare https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

[cols="20,65,15"]
|===
| Funzioni supportate nella configurazione MetroCluster | Descrizione e dove saperne di più | Inizio disponibile 


 a| 
Supporto Flash Cache per sistemi FAS50 nelle configurazioni IP MetroCluster
 a| 
Flash Cache è supportato sui sistemi FAS50 nelle configurazioni IP MetroCluster .

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["Assegnazione del disco sui sistemi FAS50 con Flash Cache"]
 a| 
ONTAP 9.18.1



 a| 
Supporto IP di MetroCluster per crittografia end-to-end
 a| 
La crittografia end-to-end è supportata sui seguenti sistemi per crittografare il traffico back-end, ad esempio i dati di replicazione NVlog e di storage, tra i siti in una configurazione IP MetroCluster .

* AFF A800, AFF C800
* AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
* AFF A70, AFF A90, AFF A1K, AFF C80
* FAS50, FAS70, FAS90


link:../maintain/task-configure-encryption.html["Configurare la crittografia end-to-end in una configurazione IP MetroCluster"]
 a| 
ONTAP 9.17.1



 a| 
Limita le modifiche per le configurazioni IP MetroCluster
 a| 
ONTAP 9.17.1 include i seguenti aggiornamenti dei limiti per le configurazioni IP MetroCluster a quattro nodi:

* I sistemi AFF C800, AFF A800, AFF A900, AFF A90 e AFF A1K presentano i seguenti limiti aggiornati:
+
** Limiti FlexVol volume per nodo: 1250
** Limiti SVM: 64 SVM per cluster
** Conteggio LIF: 256 LIF per cluster


* I sistemi AFF A400, AFF C400, ASA A400, ASA C400, AFF C80, AFF A70 e AFF A50 presentano i seguenti limiti aggiornati:
+
** Limiti di FlexVol volume per aggregato (singolo o multiplo): 625
** Limiti FlexVol volume per nodo: 1250
** Limiti FlexVol volume per coppia ad alta disponibilità (HA): 2500
** Limiti di FlexVol volume per cluster: 5000
** Limiti SVM: 64 SVM per cluster
** Conteggio LIF: 256 LIF per cluster




Fare riferimento al link:https://hwu.netapp.com["Hardware Universe"^] per maggiori informazioni.
 a| 
ONTAP 9.17.1



 a| 
Aggiornamento del firmware FibreBridge tramite credenziali
 a| 
È possibile aggiornare il firmware sui bridge FibreBridge utilizzando le credenziali se richieste dal server per scaricare il pacchetto firmware.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["Aggiornare il firmware su un bridge FibreBridge"]
 a| 
ONTAP 9.16.1



 a| 
Supporto di mobilità dei dati SVM per la migrazione delle configurazioni MetroCluster
 a| 
ONTAP supporta le seguenti migrazioni SVM di MetroCluster:

* Migrazione di una SVM tra una coppia ha non MetroCluster e una configurazione IP MetroCluster
* Migrazione di una SVM tra due configurazioni IP di MetroCluster
* Migrazione di una SVM tra una configurazione FC di MetroCluster e una configurazione IP di MetroCluster


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["Mobilità dei dati SVM"^]
 a| 
ONTAP 9.16.1



 a| 
Supporto di autenticazione MD5 per i gruppi di peer BGP
 a| 
ONTAP supporta l'autenticazione MD5 sui gruppi di peer BGP per proteggere le sessioni BGP. Quando MD5 è abilitato, le sessioni BGP possono essere stabilite ed elaborate solo tra i peer autorizzati, evitando potenziali interruzioni della sessione da parte di un attore non autorizzato.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Configurare i LIF VIP (Virtual IP)"^]
 a| 
ONTAP 9.16.1



 a| 
Supporto IP di MetroCluster per crittografia end-to-end
 a| 
La crittografia end-to-end è supportata sui sistemi AFF A400, FAS8300 e FAS8700 per crittografare il traffico back-end, come i dati di replica dello storage e NVlog, tra i siti in una configurazione IP MetroCluster.

link:../maintain/task-configure-encryption.html["Configurare la crittografia end-to-end in una configurazione IP MetroCluster"]
 a| 
ONTAP 9.15.1



 a| 
Aumento del limite del volume per configurazioni IP MetroCluster a quattro nodi su sistemi AFF A800 e AFF C800
 a| 
Nelle configurazioni MetroCluster IP a quattro nodi, sono aumentati i seguenti limiti di volume per i sistemi AFF A800 e AFF C800:

* Il numero massimo di volumi FlexVol per aggregato è aumentato da 200 a 625.
* Il numero massimo di volumi FlexVol per nodo è aumentato da 800 a 1250.
* Il numero massimo di volumi FlexVol per coppia di HA è aumentato da 1600 a 2500.

 a| 
ONTAP 9.15.1



 a| 
Supporto IP MetroCluster per NVMe
 a| 
Il protocollo host front-end NVMe/TCP è supportato sulle configurazioni MetroCluster IP a quattro nodi.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurazioni SAN in un ambiente MetroCluster"^]
 a| 
ONTAP 9.15.1



 a| 
Aumento del limite del volume per configurazioni IP MetroCluster a quattro nodi su sistemi AFF A900
 a| 
Nelle configurazioni MetroCluster IP a quattro nodi, sono aumentati i seguenti limiti di volume per i sistemi AFF A900:

* Il numero massimo di volumi FlexVol per aggregato è aumentato da 200 a 625.
* Il numero massimo di volumi FlexVol per nodo è aumentato da 800 a 1250.
* Il numero massimo di volumi FlexVol per coppia di HA è aumentato da 1600 a 2500.

 a| 
ONTAP 9.14.1



 a| 
Supporto dello storage a oggetti S3 su aggregati con mirroring e senza mirror
 a| 
È possibile abilitare un server per lo storage a oggetti S3 su una SVM in un aggregato con mirroring o senza mirror nelle configurazioni IP e FC di MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Supporto S3 con MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Supporto per il provisioning di un bucket S3 su aggregati con mirroring e senza mirror in un cluster MetroCluster
 a| 
È possibile creare un bucket su un aggregato con mirroring o senza mirror nelle configurazioni di MetroCluster.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["Creare un bucket ONTAP S3 su un aggregato con mirroring o senza mirror in una configurazione MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Transizione da MetroCluster FC a MetroCluster IP usando uno switch condiviso per lo storage collegato MetroCluster IP e Ethernet
 a| 
È possibile passare senza interruzioni da una configurazione MetroCluster FC a una configurazione MetroCluster IP utilizzando uno switch storage condiviso.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Transizione senza interruzioni da una configurazione MetroCluster FC a una configurazione MetroCluster IP (ONTAP 9.8 e versioni successive)"]
 a| 
ONTAP 9.13.1



 a| 
Transizioni senza interruzioni da una configurazione MetroCluster FC a otto nodi a una configurazione MetroCluster IP
 a| 
Puoi trasferire senza interruzioni i carichi di lavoro e i dati da una configurazione FC MetroCluster a otto nodi esistente a una nuova configurazione IP MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Passare senza interruzioni da una configurazione FC MetroCluster a una configurazione IP MetroCluster"]
 a| 
ONTAP 9.13.1



 a| 
Aggiornamenti della configurazione IP MetroCluster a quattro nodi mediante switchover e switchback
 a| 
Puoi eseguire l'upgrade dei controller in una configurazione IP MetroCluster a quattro nodi utilizzando switchover e switchback con `system controller replace` comandi.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["Aggiornare i controller in una configurazione IP MetroCluster a quattro nodi"]
 a| 
ONTAP 9.13.1



 a| 
Lo switchover non pianificato automatico assistito dal mediatore (MAUSO) viene attivato per uno spegnimento ambientale
 a| 
Se un sito si arresta senza problemi a causa di un arresto ambientale, viene attivato MAUSO.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["In che modo il mediatore ONTAP supporta lo switchover automatico non pianificato"]
 a| 
ONTAP 9.13.1



 a| 
Supporto delle configurazioni MetroCluster IP a otto nodi
 a| 
È possibile aggiornare i controller e lo storage in una configurazione IP MetroCluster a otto nodi espandendo la configurazione fino a diventare una configurazione temporanea a dodici nodi, quindi rimuovere i vecchi gruppi di disaster recovery.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["Aggiornare una configurazione MetroCluster IP a quattro nodi"]
 a| 
ONTAP 9.13.1



 a| 
Conversione della configurazione IP di MetroCluster in una configurazione di switch MetroCluster di storage condiviso
 a| 
È possibile convertire una configurazione IP di MetroCluster in una configurazione di switch MetroCluster di storage condiviso.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["Sostituire uno switch IP"]
 a| 
ONTAP 9.13.1



 a| 
Funzione di switchover forzato automatico di MetroCluster in una configurazione IP di MetroCluster
 a| 
È possibile attivare la funzione di switchover forzato automatico di MetroCluster in una configurazione IP di MetroCluster. Questa funzione è un'estensione della funzione MAUSO (Mediator-Assisted Unplanned Switchover).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["Limitazioni dello switchover automatico"]
 a| 
ONTAP 9.12.1



 a| 
S3 su una SVM su un aggregato senza mirror in una configurazione IP di MetroCluster
 a| 
È possibile abilitare un server per lo storage a oggetti ONTAP Simple Storage Service (S3) su una SVM in un aggregato senza mirror in una configurazione IP di MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Supporto S3 con MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Supporto IP MetroCluster per NVMe
 a| 
Il protocollo NVMe/FC è supportato sulle configurazioni IP MetroCluster a quattro nodi.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurazioni SAN in un ambiente MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Supporto IPSec per il protocollo host front-end nelle configurazioni fabric-attached MetroCluster IP e MetroCluster
 a| 
Il supporto IPSec per il protocollo host front-end (ad esempio NFS e iSCSI) è disponibile nelle configurazioni MetroCluster IP e MetroCluster fabric-attached.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurare la crittografia IP Security (IPsec) over wire"^]
 a| 
ONTAP 9.12.1



 a| 
Transizione da una configurazione FC MetroCluster a una configurazione IP AFF A250 o FAS500f MetroCluster
 a| 
È possibile passare da una configurazione FC MetroCluster a una configurazione IP AFF A250 o FAS500f MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["Spostare le connessioni del cluster locale"]
 a| 
ONTAP 9.11.1



 a| 
Gruppi di coerenza
 a| 
I gruppi di coerenza sono supportati nelle configurazioni MetroCluster.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["Gruppi di coerenza nelle configurazioni MetroCluster"^]
 a| 
ONTAP 9.11.1



 a| 
Aggiornamento semplificato del controller dei nodi in una configurazione MetroCluster FC
 a| 
La procedura di upgrade per il processo di upgrade che utilizza switchover e switchback è stata semplificata.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Eseguire l'upgrade dei controller in una configurazione FC MetroCluster utilizzando switchover e switchback"]
 a| 
ONTAP 9.10.1



 a| 
Supporto IP per il collegamento condiviso nel livello 3
 a| 
Le configurazioni IP di MetroCluster possono essere implementate con connessioni back-end con routing IP (livello 3).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["Considerazioni per le reti wide-area di livello 3"]
 a| 
ONTAP 9.9.1



 a| 
Supporto delle configurazioni MetroCluster a otto nodi
 a| 
I cluster permanenti a otto nodi sono supportati nelle configurazioni IP e MetroCluster fabric-attached.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Installare e cablare i componenti MetroCluster"]
 a| 
ONTAP 9.9.1

|===