---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Con ogni release vengono fornite nuove funzionalità del mediatore ONTAP.  Ecco le novità. 
---
= Novità nel supporto ONTAP Mediator per MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità e i miglioramenti MetroCluster per il supporto di ONTAP Mediator.

Per i dettagli sulle funzionalità e i miglioramenti per ogni versione di ONTAP Mediator, fare riferimento alink:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["Novità di ONTAP Mediator"^] .

[cols="4,2"]
|===
| Funzionalità ONTAP Mediator | Inizio disponibile 


 a| 
IPv6 è supportato per ONTAP Mediator 1.11 o versioni successive nelle configurazioni IP MetroCluster .

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Impostare ONTAP Mediator per una configurazione IP MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 aggiunge il supporto per la gestione di un massimo di dieci configurazioni IP MetroCluster utilizzando una singola istanza di ONTAP Mediator.

link:../install-ip/concept_mediator_requirements.html["Prepararsi all'installazione di ONTAP Mediator in una configurazione IP MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
Lo switchover non pianificato automatico assistito da mediatore (MAUSO) è supportato in caso di arresto ambientale.

Se un sito si arresta senza problemi a causa di un arresto ambientale, viene attivato MAUSO.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Come ONTAP Mediator supporta il passaggio automatico non pianificato"]
 a| 
ONTAP 9.13.1



 a| 
Supporto iniziale per ONTAP Mediator nelle configurazioni IP MetroCluster
 a| 
ONTAP 9,7

|===