---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Con ogni release vengono fornite nuove funzionalità del mediatore ONTAP.  Ecco le novità. 
---
= Novità nel supporto di ONTAP Mediator per MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità e i miglioramenti MetroCluster IP per il supporto ONTAP Mediator.

Per i dettagli sulle funzionalità e i miglioramenti per ogni versione di ONTAP Mediator, fare riferimento alink:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["Novità di ONTAP Mediator"^] .

[cols="4,1"]
|===
| Funzionalità ONTAP Mediator | Inizio disponibile 


 a| 
A partire da ONTAP Mediator 1.12.1, una singola istanza di ONTAP Mediator configurata con HTTPS può monitorare simultaneamente le seguenti configurazioni:

* Un massimo di dieci configurazioni IP MetroCluster a quattro nodi o cinque a otto nodi se installate su un host con almeno 8 core CPU e almeno 16GB di RAM.
* Una configurazione IP MetroCluster a quattro nodi e una relazione peer di sincronizzazione attiva SnapMirror se installato su un sistema operativo host con una CPU a 2 core.


link:../install-ip/concept_mediator_requirements.html#mediator-multiple-mccip["Scopri di più sul supporto di ONTAP Mediator per più configurazioni IP MetroCluster"].
 a| 
ONTAP 9.19.1



 a| 
ONTAP Mediator 1.12 supporta la configurazione di un ONTAP Mediator che utilizza HTTPS per la comunicazione nelle configurazioni IP MetroCluster. HTTPS offre una maggiore sicurezza crittografando intere sessioni tramite SSL/TLS. È possibile scegliere di installare un ONTAP Mediator che utilizza solo il protocollo HTTPS. Il pacchetto SCST non viene installato se si utilizza questo metodo di installazione. Per ulteriori informazioni sull'installazione di un ONTAP Mediator che utilizza solo il protocollo HTTPS, vedere link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["Opzioni di installazione HTTPS e iSCSI per ONTAP Mediator"^].

link:../install-ip/concept_mediator_requirements.html#select-a-communication-protocol-for-ontap-mediator["Scopri di più sui protocolli iSCSI e HTTPS in ONTAP Mediator"].
 a| 
ONTAP 9.19.1



 a| 
IPv6 è supportato per ONTAP Mediator 1.11 o versioni successive nelle configurazioni IP MetroCluster .

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Impostare ONTAP Mediator per una configurazione IP MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 aggiunge il supporto per la gestione di un massimo di dieci configurazioni IP MetroCluster utilizzando una singola istanza di ONTAP Mediator.

link:../install-ip/concept_mediator_requirements.html["Prepararsi all'installazione di ONTAP Mediator in una configurazione IP MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
Lo switchover non pianificato automatico assistito da mediatore (MAUSO) è supportato in caso di arresto ambientale.

Se un sito si arresta senza problemi a causa di un arresto ambientale, viene attivato MAUSO.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Come ONTAP Mediator supporta il passaggio automatico non pianificato"]
 a| 
ONTAP 9.13.1



 a| 
Supporto iniziale per ONTAP Mediator nelle configurazioni IP MetroCluster
 a| 
ONTAP 9,7

|===