---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Con ogni release vengono fornite nuove funzionalità del mediatore ONTAP.  Ecco le novità. 
---
= Novità del supporto di ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con ogni release vengono forniti nuovi miglioramenti al mediatore ONTAP.  Ecco le novità.

[cols="75,25"]
|===


| Versione/funzionalità di ONTAP Mediator | Versione di ONTAP 


 a| 
ONTAP Mediator 1,5 è disponibile per il monitoraggio delle configurazioni IP di MetroCluster.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installare o aggiornare il servizio di supporto ONTAP"^]
 a| 
ONTAP 9.12.1



 a| 
Il software ONTAP Mediator versione 1,4 è supportato nelle configurazioni MetroCluster IP.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installare o aggiornare il servizio di supporto ONTAP"^]
 a| 
ONTAP 9.11.1



 a| 
Il servizio ONTAP Mediator può assistere la configurazione IP di MetroCluster nell'esecuzione dello switchover non pianificato automatico fornendo un archivio fisicamente separato per le informazioni di stato.
Configurazione del servizio ONTAP Mediator per lo switchover automatico non pianificato
 a| 
ONTAP 9,7

|===