---
permalink: maintain/concept_using_the_interoperability_matrix_tool_to_find_mcc_information.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, interoperability, matrix, tool, information 
summary: Quando si imposta la configurazione MetroCluster, è possibile utilizzare lo strumento di interoperabilità per assicurarsi di utilizzare le versioni software e hardware supportate. 
---
= Utilizzo dello strumento matrice di interoperabilità per trovare le informazioni MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si imposta la configurazione MetroCluster, è possibile utilizzare lo strumento di interoperabilità per assicurarsi di utilizzare le versioni software e hardware supportate.

https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]

Dopo aver aperto la matrice di interoperabilità, è possibile utilizzare il campo soluzione storage per selezionare la soluzione MetroCluster in uso.

Utilizzare *Esplora componenti* per selezionare i componenti e la versione di ONTAP per perfezionare la ricerca.

È possibile fare clic su *Mostra risultati* per visualizzare l'elenco delle configurazioni supportate che corrispondono ai criteri.
