---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: 'Quando si eseguono le attività di manutenzione dell"hardware MetroCluster, assicurarsi di selezionare la procedura corretta.' 
---
= Scopri la manutenzione di MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scoprite come preparare le attività di manutenzione di MetroCluster e scegliere la procedura di manutenzione corretta per la vostra configurazione.



== Prepararsi per le attività di manutenzione

Prima di eseguire qualsiasi procedura di manutenzione, rivedere le informazioni contenute in link:enable-console-logging-before-maintenance.html["Prepararsi per la manutenzione di MetroCluster"].


NOTE: È necessario abilitare la registrazione della console e rimuovere il monitoraggio di ONTAP Mediator o Tiebreaker prima di eseguire le attività di manutenzione.



== Procedure di manutenzione per diversi tipi di configurazioni MetroCluster

* Se si dispone di una configurazione IP MetroCluster, consultare le procedure descritte in link:task-modify-ip-netmask-properties.html["Procedure di manutenzione per le configurazioni IP di MetroCluster"].
* Se si dispone di una configurazione MetroCluster FC, consultare le procedure descritte in link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["Procedure di manutenzione per le configurazioni MetroCluster FC"].
* Se non è possibile trovare la procedura nella sezione specifica della configurazione, consultare le procedure descritte in link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["Procedure di manutenzione per tutte le configurazioni MetroCluster"].




== Tutte le altre procedure di manutenzione

Nella tabella seguente sono riportati i collegamenti alle procedure di manutenzione MetroCluster non presenti nelle tre sezioni elencate in precedenza:

|===


| Componente | Tipo di MetroCluster (FC o IP) | Attività | Procedura 


 a| 
Software ONTAP
 a| 
Entrambi
 a| 
Aggiornamento del software ONTAP
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["Upgrade, revert o downgrade"^]



 a| 
Modulo controller
 a| 
Entrambi
 a| 
Sostituzione della FRU (inclusi moduli controller, schede PCIe, scheda FC-VI e così via)


NOTE: Lo spostamento di un modulo controller storage o di una scheda NVRAM tra i sistemi storage MetroCluster non è supportato.
 a| 
https://docs.netapp.com/platstor/index.jsp["Documentazione dei sistemi hardware ONTAP"^]



 a| 
Upgrade ed espansione
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Upgrade ed espansione di MetroCluster"]



 a| 
Transizione dalla connettività FC a quella IP
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["Transizione da MetroCluster FC a MetroCluster IP"]



 a| 
Shelf di dischi
 a| 
FC
 a| 
Tutte le altre procedure di manutenzione degli shelf. È possibile utilizzare le procedure standard.
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Manutenzione degli shelf di dischi DS460C DS224C e DS212C"^]



 a| 
IP
 a| 
Tutte le procedure di manutenzione degli shelf. È possibile utilizzare le procedure standard.

Se si aggiungono shelf per un aggregato senza mirror, vedere http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["Considerazioni sull'utilizzo di aggregati senza mirror"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Manutenzione degli shelf di dischi DS460C DS224C e DS212C"^]

|===