---
permalink: maintain/concept_migrating_root_volumes_to_a_new_destination.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, migrate, root, volumes, new, destination 
summary: 'Potrebbe essere necessario spostare i volumi root in un altro aggregato root all"interno di una configurazione MetroCluster a due o quattro nodi.' 
---
= Quando migrare i volumi root in una nuova destinazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario spostare i volumi root in un altro aggregato root all'interno di una configurazione MetroCluster a due o quattro nodi.



== Migrazione dei volumi root all'interno di una configurazione MetroCluster a due nodi

Per migrare i volumi root in un nuovo aggregato root all'interno di una configurazione MetroCluster a due nodi, fare riferimento a. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_move_mroot_to_a_new_root_aggregate_in_a_2-node_Clustered_MetroCluster_with_Switchover["Come spostare mroot in un nuovo aggregato root in un Clustered MetroCluster a 2 nodi con switchover"]. Questa procedura illustra come migrare senza interruzioni i volumi root durante un'operazione di switchover MetroCluster. Questa procedura è leggermente diversa da quella utilizzata in una configurazione a quattro nodi.



== Migrazione dei volumi root all'interno di una configurazione MetroCluster a quattro nodi

Per migrare i volumi root in un nuovo aggregato root all'interno di una configurazione MetroCluster a quattro nodi, è possibile utilizzare http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/system%5F%5Fnode%5F%5Fmigrate-root.html["nodo di sistema migra-root"] controllare rispettando i seguenti requisiti.

* È possibile utilizzare il nodo di sistema migra-root per spostare gli aggregati root all'interno di una configurazione MetroCluster a quattro nodi.
* Tutti gli aggregati root devono essere sottoposti a mirroring.
* È possibile aggiungere nuovi shelf su entrambi i siti con dischi più piccoli per ospitare l'aggregato root.
* Prima di collegare nuovi dischi, è necessario controllare i limiti dei dischi supportati dalla piattaforma.
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* Se si sposta l'aggregato root su dischi più piccoli, è necessario adattare le dimensioni minime del volume root della piattaforma per garantire il salvataggio di tutti i file core.



NOTE: La procedura a quattro nodi può essere applicata anche a una configurazione a otto nodi.
