---
permalink: maintain/reference_fb_replace_a_power_supply.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, replacing, failed, power, supply, module 
summary: In caso di modifica dello stato di un modulo di alimentazione al bridge, è possibile rimuovere e installare il modulo di alimentazione. 
---
= Sostituzione a caldo di un modulo alimentatore guasto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In caso di modifica dello stato di un modulo di alimentazione al bridge, è possibile rimuovere e installare il modulo di alimentazione.

È possibile visualizzare il cambiamento di stato di un modulo di alimentazione tramite i LED sul bridge. È inoltre possibile visualizzare lo stato dei moduli di alimentazione tramite la GUI ExpressNAV e la CLI del bridge, tramite la porta seriale o Telnet.

* Questa procedura è NDO (senza interruzioni) e richiede circa 15 minuti per essere completata.
* È necessaria la password admin e l'accesso a un server FTP o SCP.



NOTE: Il _Manuale d'installazione e di funzionamento di FibreBridge atto_ per il tuo modello bridge contiene ulteriori informazioni sulle interfacce di gestione.

Puoi accedere a questo e ad altri contenuti sul sito web di atto utilizzando il link fornito nella pagina ATTO Fibrebridge Description.
