---
permalink: maintain/reference_where_to_find_additional_information_mcc_service_guide.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, additional, information 
summary: Per ulteriori informazioni sulla configurazione, il funzionamento e il monitoraggio di una configurazione MetroCluster, consultare la documentazione completa di NetApp. 
---
= Dove trovare ulteriori informazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ulteriori informazioni sulla configurazione, il funzionamento e il monitoraggio di una configurazione MetroCluster sono disponibili nella documentazione completa di NetApp.

|===


| Informazioni | Soggetto 


 a| 
link:../index.html["Documentazione MetroCluster"]
 a| 
* Tutte le informazioni MetroCluster




 a| 
https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["Architettura e progettazione della soluzione NetApp MetroCluster"^]
 a| 
* Panoramica tecnica della configurazione e del funzionamento di MetroCluster.
* Best practice per la configurazione di MetroCluster.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installazione e configurazione di Fabric-Attached MetroCluster"]
 a| 
* Architettura Fabric-Attached MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione degli switch FC
* Configurazione di MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["Estensione dell'installazione e della configurazione di MetroCluster"]
 a| 
* Estendi l'architettura MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione di MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["Installazione e configurazione di MetroCluster IP"]
 a| 
* Architettura IP di MetroCluster
* Collegamento della configurazione IP di MetroCluster
* Configurazione di MetroCluster in ONTAP




 a| 
https://www.netapp.com/support-and-training/documentation/["Documentazione NetApp: Guide e risorse sui prodotti"^]
 a| 
* Monitoraggio della configurazione e delle prestazioni di MetroCluster




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installazione e configurazione del software MetroCluster Tiebreaker"]
 a| 
* Monitoraggio della configurazione MetroCluster con il software MetroCluster Tiebreaker




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Transizione basata sulla copia"]
 a| 
* Transizione dei dati dai sistemi storage 7-Mode ai sistemi storage in cluster


|===