---
permalink: maintain/task_change_isl_properties_isl_ports_or_the_iod_ood_configuration_on_a_brocade_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, isl, properties, isl, ports, iod, configuration, brocade, switch 
summary: Potrebbe essere necessario aggiungere gli ISL a uno switch se si sta aggiungendo o aggiornando hardware come controller o switch aggiuntivi o più veloci. 
---
= Modifica delle proprietà ISL, delle porte ISL o della configurazione IOD/OOOD su uno switch Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario aggiungere gli ISL a uno switch se si sta aggiungendo o aggiornando hardware come controller o switch aggiuntivi o più veloci.

.Prima di iniziare
Assicurarsi che il sistema sia configurato correttamente, che tutti gli switch fabric siano operativi e che non siano presenti errori.

link:enable-console-logging-before-maintenance.html["Attivare la registrazione della console"] prima di eseguire questa attività.

Se l'apparecchiatura sul collegamento ISL cambia e la nuova configurazione del collegamento non supporta più la configurazione corrente----trunking e consegna ordinata----allora il fabric deve essere riconfigurato per la policy di routing corretta: In-order-delivery (IOD) o out-of-order-delivery (OOOD).


NOTE: Per apportare modifiche a OOD dal software ONTAP, attenersi alla seguente procedura: link:../install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["Configurazione della consegna in-order o out-of-order dei frame sul software ONTAP"]

.Fasi
. Disattivare le porte FCVI e HBA dello storage:
+
`portcfgpersistentdisable _port number_`

+
Per impostazione predefinita, le prime 8 porte (porte da 0 a 7) vengono utilizzate per FCVI e Storage HBA. Le porte devono essere costantemente disattivate in modo che rimangano disattivate in caso di riavvio dello switch.

+
L'esempio seguente mostra che le porte ISL 0-7 sono disabilitate su entrambi gli switch:

+
[listing]
----

    Switch_A_1:admin> portcfgpersistentdisable 0-7
    Switch_B_1:admin> portcfgpersistentdisable 0-7
----
. Modificare le porte ISL secondo necessità.
+
[cols="30,70"]
|===


| Opzione | Fase 


 a| 
Per modificare la velocità di una porta ISL...
 a| 
Utilizzare `portcfgspeed _port number port speed_` comando su entrambi gli switch del fabric.

Nell'esempio seguente, la velocità della porta ISL viene modificata da 40 Gbps a 16 Gbps:

`brocade_switch_A_1:admin> portcfgspeed 40 16`

È possibile verificare che la velocità sia cambiata utilizzando `switchshow` comando:

`brocade_switch_A_1:admin> switchshow`

Viene visualizzato il seguente output:

....
  . . .
   40 40  062800  id 16G  No_Sync FC Disabled
  . . .
....


 a| 
Per modificare la distanza di una porta ISL...
 a| 
Utilizzare `portcfglongdistance _port number port distance_` comando su entrambi gli switch nel fabric.



 a| 
Per rimuovere un ISL...
 a| 
Scollegare il tirante.



 a| 
Per aggiungere un ISL...
 a| 
Inserire gli SFP nelle porte che si stanno aggiungendo come porte ISL. Assicurarsi che queste porte siano elencate nella link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installare un MetroCluster collegato al fabric"] per lo switch a cui si desidera aggiungerli.



 a| 
Per spostare un ISL...
 a| 
Il trasferimento di un ISL equivale alla rimozione e all'aggiunta di un ISL. Innanzitutto, rimuovere l'ISL scollegando il collegamento, quindi inserire gli SFP nelle porte che si stanno aggiungendo come porte ISL.

|===
+

NOTE: Quando si apportano modifiche alle porte ISL, potrebbe essere necessario applicare ulteriori impostazioni consigliate dal fornitore di WDM. Fare riferimento alla documentazione del fornitore WDM per le indicazioni.

. Riconfigurare per la consegna fuori ordine (OOD) o la consegna in-order (IOD).
+

NOTE: Se i criteri di routing rimangono invariati, non è necessario riconfigurare e questo passaggio può essere ignorato. La configurazione ONTAP deve corrispondere alla configurazione fabric. Se il fabric è configurato per OOD, anche ONTAP deve essere configurato per OOD. Lo stesso vale per IOD.

+
Questo passaggio deve essere eseguito nei seguenti scenari:

+
** Più di un ISL ha formato una linea prima della modifica, ma dopo la modifica, il trunking non è più supportato. In questo caso, è necessario configurare il fabric per OOD.
** C'è un ISL prima della modifica e più ISL dopo la modifica.
** Se più ISL formano una linea, configurare la struttura per IOD. Se più ISL *non possono* formare un trunk, configurare il fabric per OOD.
** Disattivare in modo persistente gli switch utilizzando `switchcfgpersistentdisable` come illustrato nell'esempio seguente:
+
[listing]
----

Switch_A_1:admin> switchcfgpersistentdisable
Switch_B_1:admin> switchcfgpersistentdisable
----
+
... Configurare la modalità trunking per ogni ISL `portcfgtrunkport _port number_` come mostrato nella seguente tabella:
+
[cols="30,70"]
|===


| Scenario | Fasi 


 a| 
Configurare l'ISL per il trunking (IOD)
 a| 
Impostare `portcfgtrunkport _port number_` a 1:

....
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
....


 a| 
Configurare l'ISL per il trunking
 a| 
Impostare `portcfgtrunkport _port number_` a 0:

....
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
....
|===
... Configurare il fabric per IOD o OOOD secondo necessità.
+
[cols="30,70"]
|===


| Scenario | Fasi 


 a| 
Configurare il fabric per IOD
 a| 
Impostare le tre impostazioni di IOD, APT e DLS utilizzando `iodset`, `aptpolicypolicy`, e. `dlsreset` comandi come mostrato nell'esempio seguente:

....
Switch_A_1:admin> iodset
Switch_A_1:admin> aptpolicy 1
Policy updated successfully.
Switch_A_1:admin> dlsreset
FC_switch_A_1:admin>portcfgtrunkport 40 1
FC_switch_A_1:admin>portcfgtrunkport 41 1

Switch_B_1:admin> iodset
Switch_B_1:admin> aptpolicy 1
Policy updated successfully.
Switch_B_1:admin> dlsreset
FC_switch_B_1:admin>portcfgtrunkport 20 1
FC_switch_B_1:admin>portcfgtrunkport 21 1
....


 a| 
Configurare il fabric per OOD
 a| 
Impostare le tre impostazioni di IOD, APT e DLS utilizzando `iodreset`, `aptpolicy__policy__`, e. `dlsset` comandi come mostrato nell'esempio seguente:

....
Switch_A_1:admin> iodreset
Switch_A_1:admin> aptpolicy 3
Policy updated successfully.
Switch_A_1:admin> dlsset
FC_switch_A_1:admin> portcfgtrunkport 40 0
FC_switch_A_1:admin> portcfgtrunkport 41 0

Switch_B_1:admin> iodreset
Switch_B_1:admin> aptpolicy 3
Policy updated successfully.
Switch_B_1:admin> dlsset
FC_switch_B_1:admin> portcfgtrunkport 40 0
FC_switch_B_1:admin> portcfgtrunkport 41 0
....
|===
... Abilitare gli switch in modo persistente:
+
`switchcfgpersistentenable`

+
[listing]
----
switch_A_1:admin>switchcfgpersistentenable
switch_B_1:admin>switchcfgpersistentenable
----
+
Se questo comando non esiste, utilizzare `switchenable` come illustrato nell'esempio seguente:

+
[listing]
----
brocade_switch_A_1:admin>
switchenable
----
... Verificare le impostazioni OOOD utilizzando `iodshow`, `aptpolicy`, e. `dlsshow` comandi come mostrato nell'esempio seguente:
+
[listing]
----
switch_A_1:admin> iodshow
IOD is not set

switch_A_1:admin> aptpolicy

       Current Policy: 3 0(ap)

       3 0(ap) : Default Policy
       1: Port Based Routing Policy
       3: Exchange Based Routing Policy
       0: AP Shared Link Policy
       1: AP Dedicated Link Policy
       command aptpolicy completed

switch_A_1:admin> dlsshow
DLS is set by default with current routing policy
----
+

NOTE: È necessario eseguire questi comandi su entrambi gli switch.

... Verificare le impostazioni IOD utilizzando `iodshow`, `aptpolicy`, e. `dlsshow` comandi come mostrato nell'esempio seguente:
+
[listing]
----
switch_A_1:admin> iodshow
IOD is set

switch_A_1:admin> aptpolicy
       Current Policy: 1 0(ap)

       3 0(ap) : Default Policy
       1: Port Based Routing Policy
       3: Exchange Based Routing Policy
       0: AP Shared Link Policy
       1: AP Dedicated Link Policy
       command aptpolicy completed

switch_A_1:admin> dlsshow
DLS is not set
----
+

NOTE: È necessario eseguire questi comandi su entrambi gli switch.





. Verificare che gli ISL siano online e trunked (se l'apparecchiatura di collegamento supporta il trunking) utilizzando `islshow` e. `trunkshow` comandi.
+

NOTE: Se FEC è attivato, il valore di disallineamento dell'ultima porta online del fascio di linee potrebbe mostrare una differenza fino a 36, anche se i cavi sono tutti della stessa lunghezza.

+
[cols="20,80"]
|===


| Gli ISL sono trunked? | Viene visualizzato il seguente output di sistema... 


 a| 
Sì
 a| 
Se gli ISL sono trunked, nell'output di viene visualizzato solo un ISL singolo `islshow` comando. A seconda del trunk master, è possibile visualizzare la porta 40 o 41. L'output di `trunkshow` Se una linea con ID "`1`" elenca entrambi gli ISL fisici sulle porte 40 e 41. Nell'esempio seguente, le porte 40 e 41 sono configurate per l'utilizzo come ISL:

[listing]
----
switch_A_1:admin> islshow 1:
40-> 40 10:00:00:05:33:88:9c:68 2 switch_B_1 sp: 16.000G bw: 32.000G TRUNK CR_RECOV FEC
switch_A_1:admin> trunkshow
1: 40-> 40 10:00:00:05:33:88:9c:68 2 deskew 51 MASTER
41-> 41 10:00:00:05:33:88:9c:68 2 deskew 15
----


 a| 
No
 a| 
Se gli ISL non sono trunked, entrambi gli ISL vengono visualizzati separatamente negli output per `islshow` e. `trunkshow`. Entrambi i comandi elencano gli ISL con il loro ID "`1`" e "`2`". Nell'esempio seguente, le porte "`40`" e "`41`" sono configurate per l'utilizzo come ISL:

[listing]
----
switch_A_1:admin> islshow
1: 40-> 40 10:00:00:05:33:88:9c:68 2 switch_B_1 sp: 16.000G bw: 16.000G TRUNK CR_RECOV FEC
2: 41-> 41 10:00:00:05:33:88:9c:68 2 switch_B_1 sp: 16.000G bw: 16.000G TRUNK CR_RECOV FEC
switch_A_1:admin> trunkshow
1: 40-> 40 10:00:00:05:33:88:9c:68 2 deskew 51 MASTER
2: 41-> 41 10:00:00:05:33:88:9c:68 2 deskew 48 MASTER
----
|===
. Eseguire `spinfab` Su entrambi gli switch per verificare che gli ISL siano integri:
+
[listing]
----
switch_A_1:admin> spinfab -ports 0/40 - 0/41
----
. Attivare le porte disattivate al passaggio 1:
+
`portenable _port number_`

+
L'esempio seguente mostra le porte ISL da "`0`" a "`7`" attivate:

+
[listing]
----
brocade_switch_A_1:admin> portenable 0-7
----

