---
permalink: maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches, cleanupfiles, cisco 
summary: Potrebbe essere necessario aggiornare un file RCF su uno switch IP Cisco. Ad esempio, un aggiornamento ONTAP o un aggiornamento del firmware dello switch richiedono un nuovo file RCF. 
---
= Aggiorna i file RCF sugli switch Cisco usando CleanUpFiles in una configurazione IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potresti dover aggiornare un file di configurazione di riferimento (RCF) su uno switch IP Cisco. Ad esempio, un upgrade di ONTAP o un upgrade del firmware dello switch richiedono entrambi un nuovo RCF.

.A proposito di questa attività
* A partire dalla versione 1.4a di RcfFileGenerator, è disponibile una nuova opzione per modificare (aggiornare, eseguire il downgrade o sostituire) la configurazione dello switch sugli switch IP Cisco senza eseguire una "cancellazione in scrittura".
* link:enable-console-logging-before-maintenance.html["Attivare la registrazione della console"] prima di eseguire questa attività.


* Lo switch Cisco 9336C-FX2 è dotato di due tipi di storage di switch diversi con nomi diversi nell'RCF. Utilizzare la tabella seguente per determinare il tipo di storage Cisco 9336C-FX2 corretto per la propria configurazione:
+
[cols="3*"]
|===
| Se si sta collegando il seguente dispositivo di archiviazione... | Scegliere il tipo di storage Cisco 9336C-FX2... | Esempio di banner/MOTD RCF 


 a| 
** Shelf SAS collegati direttamente
** Shelf NVMe connessi direttamente
** Shelf NVMe connessi a switch storage dedicati

 a| 
9336C-FX2 - solo archiviazione diretta
 a| 
`* Switch    : NX9336C (direct storage, L2 Networks, direct ISL)`



 a| 
** Shelf SAS collegati direttamente
** Shelf NVMe connessi agli switch IP MetroCluster



NOTE: È richiesto almeno uno shelf NVMe connesso a Ethernet
 a| 
9336C-FX2 – Storage SAS ed Ethernet
 a| 
`* Switch    : NX9336C (SAS and Ethernet storage, L2 Networks, direct ISL)`

|===


.Prima di iniziare
È possibile utilizzare questo metodo se la configurazione soddisfa i seguenti requisiti:

* Viene applicata la configurazione RCF standard.
* Il https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"] deve essere in grado di creare lo stesso RCF che viene applicato, con la stessa versione e configurazione (piattaforme, VLAN).
* Il RCF applicato non è stato fornito da NetApp per una configurazione speciale.
* Il RCF non è stato modificato prima che venisse applicato.
* Prima di applicare l'attuale RCF, hai seguito i passaggi per ripristinare le impostazioni di fabbrica dello switch.
* Non sono state apportate modifiche alla configurazione dello switch (porta) dopo l'applicazione dell'RCF.
+
Se non soddisfi questi requisiti, non puoi usare i CleanUpFiles che vengono creati quando generi gli RCF. Tuttavia, puoi sfruttare la funzione per creare CleanUpFiles generici: la pulizia usando questo metodo deriva dall'output di  `show running-config` ed è best practice.

+

NOTE: È necessario aggiornare gli switch nel seguente ordine: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2. In alternativa, è possibile aggiornare gli switch Switch_A_1 e Switch_B_1 contemporaneamente, seguiti dagli switch Switch_A_2 e Switch_B_2.



.Fasi
. link:../install-ip/switch-move-cluster-lifs.html["Sposta i LIF del cluster"]prima di iniziare l'aggiornamento.
. Determina la versione corrente di RCF e quali porte e VLAN sono utilizzate: `IP_switch_A_1# show banner motd`
+

NOTE: È necessario ottenere queste informazioni da tutti e quattro gli switch e completare la seguente tabella di informazioni.

+
[listing]
----
* NetApp Reference Configuration File (RCF)
*
* Switch : NX9336C (SAS storage, L2 Networks, direct ISL)
* Filename : NX9336_v1.81_Switch-A1.txt
* Date : Generator version: v1.3c_2022-02-24_001, file creation time: 2021-05-11, 18:20:50
*
* Platforms : MetroCluster 1 : FAS8300, AFF-A400, FAS8700
*              MetroCluster 2 : AFF-A320, FAS9000, AFF-A700, AFF-A800
* Port Usage:
* Ports 1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 111
* Ports 3- 4: Intra-Cluster Node Ports, Cluster: MetroCluster 2, VLAN 151
* Ports 5- 6: Ports not used
* Ports 7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 111, 151
* Ports 9-10: MetroCluster 1, Node Ports, VLAN 119
* Ports 11-12: MetroCluster 2, Node Ports, VLAN 159
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used
*

#
IP_switch_A_1#
----
+
Da questo output, è necessario raccogliere le informazioni mostrate nelle due tabelle seguenti.

+
|===


| Informazioni generiche | MetroCluster | Dati 


| Versione RCF |  | 1.81 


| Tipo di switch |  | NX9336 


| Tipologia di rete |  | Reti L2, ISL diretto 


| Tipo di storage |  | Storage SAS 


.2+| Piattaforme | 1 | AFF A400 


| 2 | FAS9000 
|===
+
|===
| Informazioni sulla VLAN | Rete | Configurazione di MetroCluster | Switchport | Sito A | Sito B 


.4+| Cluster locale VLAN .2+| Rete 1 | 1 | 1, 2 | 111 | 222 


| 2 | 3, 4 | 151 | 251 


.2+| Rete 2 | 1 | 1, 2 | 111 | 222 


| 2 | 3, 4 | 151 | 251 


.4+| VLAN MetroCluster .2+| Rete 1 | 1 | 9, 10 | 119 | 119 


| 2 | 11, 12 | 159 | 159 


.2+| Rete 2 | 1 | 9, 10 | 219 | 219 


| 2 | 11, 12 | 259 | 259 
|===
. [[Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles]] Crea i file RCF e CleanUpFiles, oppure crea file generici CleanUpFiles per la configurazione corrente.
+
Se la configurazione soddisfa i requisiti indicati nei prerequisiti, selezionare *opzione 1*. Se la configurazione *non* soddisfa i requisiti indicati nei prerequisiti, selezionare *opzione 2*.

+
[role="tabbed-block"]
====
.Opzione 1: Crea gli RCF e CleanUpFiles
--
Utilizzare questa procedura se la configurazione soddisfa i requisiti.

.Fasi
.. Usa il RcfFileGenerator 1.4a (o successivo) per creare gli RCF con le informazioni che hai recuperato nel passaggio 1. La nuova versione del RcfFileGenerator crea un set aggiuntivo di CleanUpFiles che puoi usare per ripristinare alcune configurazioni e preparare lo switch ad applicare una nuova configurazione RCF.
.. Confronta il banner motd con le RCF attualmente applicate. I tipi di piattaforma, il tipo di switch, la porta e l'utilizzo delle VLAN devono essere gli stessi.
+

NOTE: Devi usare il CleanUpFiles della stessa versione dell'RCF e per la stessa identica configurazione. Usare qualsiasi CleanUpFile diverso non funzionerà e potrebbe richiedere un reset completo dello switch.

+

NOTE: La versione di ONTAP per cui è stato creato l'RCF non è rilevante. È importante solo la versione dell'RCF.

+

NOTE: Il file RCF (anche se si tratta della stessa versione) potrebbe elencare meno o più piattaforme. Assicurati che la tua piattaforma sia elencata.



--
.Opzione 2: Creazione di file CleanUpFiles generici
--
Utilizzare questa procedura se la configurazione *non* soddisfa tutti i requisiti.

.Fasi
.. Recuperare l'output di `show running-config` da ogni switch.
.. Aprire lo strumento RcfFileGenerator e fare clic su "Create generic CleanUpFiles" (Crea file di pulizia generici) nella parte inferiore della finestra
.. Copiare l'output recuperato al punto 1 dal commutatore 'uno' nella finestra superiore. È possibile rimuovere o lasciare l'output predefinito.
.. Fare clic su "Create CUF Files" (Crea file CUF).
.. Copiare l'output dalla finestra inferiore in un file di testo (questo file è CleanUpFile).
.. Ripetere i passaggi c, d ed e per tutti gli switch della configurazione.
+
Al termine di questa procedura, si dovrebbero avere quattro file di testo, uno per ogni switch. È possibile utilizzare questi file nello stesso modo dei CleanUpFiles che è possibile creare utilizzando l'opzione 1.



--
====
. [[Create-the-new-RCF-files-for-the-new-configuration]] Crea i "nuovi" file RCF per la nuova configurazione. Crea questi file nello stesso modo in cui hai creato i file nel passaggio precedente, ma scegli la rispettiva versione di ONTAP e RCF.
+
Dopo aver completato questo passaggio dovresti avere due set di RCF, ciascun set composto da dodici file.

. Scaricare i file sul bootflash.
+
.. Scarica il CleanUpFiles che hai creato in <<Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles,Crea gli RCF e CleanUpFiles, oppure crea generici CleanUpFiles per la configurazione corrente>>
+

NOTE: Questo CleanUpFile è per l'RCF attualmente applicato e *NON* per il nuovo RCF a cui vuoi aggiornare.

+
Esempio di CleanUpFile per Switch-A1: `Cleanup_NX9336_v1.81_Switch-A1.txt`

.. Scarica i 'nuovi' RCF che hai creato in <<Create-the-new-RCF-files-for-the-new-configuration,Crea i 'nuovi' RCF per la nuova configurazione.>>
+
Esempio di RCF per lo switch A1: `NX9336_v1.90_Switch-A1.txt`

.. Scarica il CleanUpFiles che hai creato in <<Create-the-new-RCF-files-for-the-new-configuration,Crea i 'nuovi' RCF per la nuova configurazione.>> Questo passaggio è facoltativo: puoi usare il file in futuro per aggiornare la configurazione dello switch. Corrisponde alla configurazione attualmente applicata.
+
Esempio di CleanUpFile per Switch-A1: `Cleanup_NX9336_v1.90_Switch-A1.txt`

+

NOTE: Utilizzare CleanUpFile per la versione RCF corretta (corrispondente). Se si utilizza un CleanUpFile per una versione RCF diversa o per una configurazione diversa, la pulizia della configurazione potrebbe non funzionare correttamente.

+
Il seguente esempio copia i tre file nella flash di avvio:

+
[listing]
----
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.81_MetroCluster-IP_L2Direct_A400FAS8700_xxx_xxx_xxx_xxx/Cleanup_NX9336_v1.81_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//NX9336_v1.90_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//Cleanup_NX9336_v1.90_Switch-A1.txt bootflash:
----
+

NOTE: Viene richiesto di specificare Virtual Routing and Forwarding (VRF).



. Applicare il file CleanUpFile o il file CleanUpFile generico.
+
Alcune configurazioni vengono ripristinate e gli switchport vengono "offline".

+
.. Verificare che non vi siano modifiche in sospeso alla configurazione di avvio: `show running-config diff`
+
[listing]
----
IP_switch_A_1# show running-config diff
IP_switch_A_1#
----


. Se viene visualizzato l'output di sistema, salvare la configurazione in esecuzione nella configurazione di avvio: `copy running-config startup-config`
+

NOTE: L'output del sistema indica che la configurazione di avvio e la configurazione in esecuzione sono diverse e in sospeso. Se non si salvano le modifiche in sospeso, non è possibile eseguire il rollback utilizzando un ricaricamento dello switch.

+
.. Applicare il comando CleanUpFile:
+
[listing]
----

IP_switch_A_1# copy bootflash:Cleanup_NX9336_v1.81_Switch-A1.txt running-config

IP_switch_A_1#
----
+

NOTE: Lo script potrebbe impiegare del tempo per tornare al prompt dello switch. Nessun output previsto.



. Visualizzare la configurazione in esecuzione per verificare che la configurazione sia stata cancellata: `show running-config`
+
La configurazione corrente dovrebbe mostrare:

+
** Non sono configurate mappe di classe ed elenchi di accesso IP
** Non sono configurate mappe di policy
** Nessuna policy di servizio configurata
** Nessun profilo porta configurato
** Tutte le interfacce Ethernet (ad eccezione di mgmt0 che non devono mostrare alcuna configurazione e deve essere configurata solo la VLAN 1).
+
Se riscontri che uno qualsiasi degli elementi sopra elencati è configurato, potresti non essere in grado di applicare una nuova configurazione RCF. Tuttavia, puoi ripristinare la configurazione precedente riavviando lo switch *senza* salvare la configurazione in esecuzione nella configurazione di avvio. Lo switch si avvierà con la configurazione precedente.



. Applica l'RCF e verifica che le porte siano online.
+
.. Applica l'RCF.
+
[listing]
----
IP_switch_A_1# copy bootflash:NX9336_v1.90-X2_Switch-A1.txt running-config
----
+

NOTE: Durante l'applicazione della configurazione vengono visualizzati alcuni messaggi di avviso. I messaggi di errore generalmente non sono previsti. Tuttavia, se si è connessi con SSH, potrebbe essere visualizzato il seguente errore: `Error: Can't disable/re-enable ssh:Current user is logged in through ssh`

.. Una volta applicata la configurazione, verificare che il cluster e le porte MetroCluster siano in linea con uno dei seguenti comandi: `show interface brief`, `show cdp neighbors`, o. `show lldp neighbors`
+

NOTE: Se è stata modificata la VLAN per il cluster locale e si è aggiornato il primo switch del sito, il monitoraggio dello stato del cluster potrebbe non riportare lo stato come "integro" perché le VLAN delle configurazioni precedenti e nuove non corrispondono. Dopo l'aggiornamento del secondo switch, lo stato dovrebbe tornare a essere integro.

+
Se la configurazione non viene applicata correttamente o non si desidera mantenere la configurazione, è possibile tornare alla configurazione precedente ricaricando lo switch *senza* salvare la configurazione in esecuzione nella configurazione di avvio. Lo switch verrà configurato in precedenza.



. Salvare la configurazione e ricaricare lo switch.
+
[listing]
----
IP_switch_A_1# copy running-config startup-config

IP_switch_A_1# reload
----
. Modifica tutti i LIF del cluster per abilitare il ripristino automatico:
+
.. Riattiva il ripristino automatico:
+
`network interface modify -vserver Cluster -lif * -auto-revert true`

+
[listing]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert true

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.

cluster_A::*>
----
.. Ripristina tutti i LIF del cluster che attualmente non si trovano sulle loro porte home alle loro porte home:
+
`network interface revert -vserver Cluster -lif *`

+
Attendi qualche minuto affinché i LIF tornino alla loro porta home:

.. Conferma che tutti i LIF siano sulle rispettive porte home:
+
[listing]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      192.168.204.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      192.168.204.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      192.168.204.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      192.168.204.97/18  node_A_2      e4b     true
4 entries were displayed.
----
.. Verifica lo stato dei nodi MetroCluster:
+
`metrocluster node show`

+
[listing]
----
cluster_A::*> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_B
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.

cluster_A::*>
----



