---
permalink: maintain/task_power_off_an_entire_mcc_fc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, power, off, entire, metrocluster, fc, configuration 
summary: 'Prima di iniziare la manutenzione o il trasferimento del sito, è necessario spegnere l"intera configurazione MetroCluster FC e tutte le apparecchiature.' 
---
= Spegnimento di un'intera configurazione MetroCluster FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di iniziare la manutenzione o il trasferimento del sito, è necessario spegnere l'intera configurazione MetroCluster FC e tutte le apparecchiature.

.A proposito di questa attività
È necessario eseguire le fasi di questa procedura da entrambi i siti, contemporaneamente.


NOTE: A partire da ONTAP 9.8, la `*storage switch*` il comando viene sostituito con `*system switch*`. La procedura riportata di seguito mostra `*storage switch*` Ma se si utilizza ONTAP 9.8 o versione successiva, il comando `*system switch*` è preferibile utilizzare il comando.

.Fasi
. Verificare la configurazione MetroCluster da entrambi i siti nella configurazione MetroCluster.
+
.. Confermare la configurazione MetroCluster e verificare che la modalità operativa sia normale. +
`*metrocluster show*`
.. Confermare la connettività ai dischi immettendo il seguente comando su uno qualsiasi dei nodi MetroCluster: +
`*run local sysconfig -v*`
.. Eseguire il seguente comando: +
`*storage bridge show*`
.. Eseguire il seguente comando: +
`*storage port show*`
.. Eseguire il seguente comando: +
`*storage switch show*`
.. Eseguire il seguente comando: +
`*network port show*`
.. Eseguire un controllo MetroCluster: +
`*metrocluster check run*`
.. Visualizzare i risultati del controllo MetroCluster: +
`*metrocluster check show*`


. Disattivare AUSO modificando IL dominio di errore AUSO in
+
`*auso-disabled*`

+
[listing]
----
cluster_A_site_A::*>metrocluster modify -auto-switchover-failure-domain auso-disabled
----
. Verificare la modifica utilizzando il comando
+
`*metrocluster operation show*`

+
[listing]
----

	cluster_A_site_A::*> metrocluster operation show
       Operation: modify
           State: successful
      Start Time: 4/25/2020 20:20:36
        End Time: 4/25/2020 20:20:36
          Errors: -
----
. Arrestare i nodi utilizzando il seguente comando:
`*halt*`
+
** Per una configurazione MetroCluster a quattro o otto nodi, utilizzare `*inhibit-takeover*` e. `*skip-lif-migration-before-shutdown*` parametri:
+
[listing]
----
system node halt -node node1_SiteA -inhibit-takeover true -ignore-quorum-warnings true -skip-lif-migration-before-shutdown true
----
** Per una configurazione MetroCluster a due nodi, utilizzare il comando:
+
[listing]
----
system node halt -node node1_SiteA -ignore-quorum-warnings true
----


. Spegnere le seguenti apparecchiature presso il sito:
+
** Controller di storage
** Switch FC MetroCluster (se in uso e la configurazione non è una configurazione stretch a due nodi)
** ATTO FibreBridges
** Shelf di storage


. Attendere trenta minuti, quindi accendere la seguente apparecchiatura presso il sito:
+
** Shelf di storage
** ATTO FibreBridges
** Switch FC MetroCluster
** Controller di storage


. Dopo aver acceso i controller, verificare la configurazione MetroCluster da entrambi i siti.
+
Per verificare la configurazione, ripetere il passaggio 1.

. Eseguire i controlli del ciclo di alimentazione.
+
.. Verificare che tutte le SVM di origine della sincronizzazione siano online: +
`*vserver show*`
.. Avviare tutte le SVM di origine della sincronizzazione non in linea: +
`*vserver start*`



