---
permalink: maintain/task_change_an_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, fc, switch 
summary: 'Potrebbe essere necessario cambiare il vendor di uno switch FC (da Cisco a Brocade o viceversa), cambiare il modello dello switch o entrambe le cose.' 
---
= Modificare il vendor o il modello degli switch FC
:allow-uri-read: 


[role="lead"]
Potrebbe essere necessario cambiare il vendor per gli switch FC da Cisco a Brocade o viceversa, modificare il modello dello switch o entrambi.

.A proposito di questa attività
* Questa procedura si applica quando si utilizzano interruttori convalidati NetApp.
* link:enable-console-logging-before-maintenance.html["Attivare la registrazione della console"] prima di eseguire questa attività.
* È necessario eseguire i passaggi di questa procedura su un tessuto alla volta, per entrambi i fabric nella configurazione.


.Fasi
. [[step_1,Step 1]]controllare lo stato della configurazione.
+
.. Verificare che MetroCluster sia configurato e in modalità normale su ciascun cluster: `*metrocluster show*`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Verificare che il mirroring sia attivato su ciascun nodo: `*metrocluster node show*`
+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Verificare che i componenti di MetroCluster siano in buone condizioni: `*metrocluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. Verificare che non siano presenti avvisi sullo stato di salute: `*system health alert show*`


. Configurare i nuovi switch prima dell'installazione.
+
Seguire la procedura descritta in link:../install-fc/concept-configure-fc-switches.html["Configurare gli switch FC"].

. Scollegare i collegamenti dai vecchi interruttori rimuovendo i collegamenti nell'ordine seguente:
+
.. Scollegare le interfacce MetroCluster FC e FCVI.
.. Scollegare i ponti atto FibreBridge.
.. Scollegare gli ISL MetroCluster.


. Spegnere i vecchi interruttori, rimuovere i cavi e sostituire fisicamente i vecchi interruttori con il nuovo interruttore.
. Collegare gli interruttori nel seguente ordine:
+
È necessario seguire la procedura descritta in link:../install-fc/task_configure_the_mcc_hardware_components_fabric.html["Cablaggio di una configurazione MetroCluster collegata al fabric"].

+
.. Collegare gli ISL al sito remoto.
.. Collegare i ponti atto FibreBridge.
.. Collegare le interfacce MetroCluster FC e FCVI.


. Accendere gli interruttori.
. Verificare che la configurazione di MetroCluster sia corretta ripetendo la configurazione <<Fase 1>>.
. Ripetere i passaggi da 1 a 7 per il secondo fabric nella configurazione.

