---
permalink: maintain/task_do_not_use_for_9_8_and_later_reconfigure_the_fc_switch_layout_for_ontap_9_1_or_later.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, reconfigure, fc, switch, layout, configured 
summary: 'Se il layout dello switch FC esistente è stato configurato prima di ONTAP 9.1, è necessario riconfigurare il layout delle porte e applicare i file di configurazione di riferimento (RCF) più recenti. Questa procedura si applica solo alle configurazioni MetroCluster FC.' 
---
= Riconfigurazione del layout di uno switch FC configurato prima di ONTAP 9.x.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il layout dello switch FC esistente è stato configurato prima di ONTAP 9.1, è necessario riconfigurare il layout delle porte e applicare i file di configurazione di riferimento (RCF) più recenti. Questa procedura si applica solo alle configurazioni MetroCluster FC.

.Prima di iniziare
È necessario identificare gli switch FC presenti nel dominio fabric.

È necessaria la password admin e l'accesso a un server FTP o SCP.

È necessario eseguire questa attività se il layout dello switch FC esistente è stato configurato prima di ONTAP 9.1. Non è necessario eseguire l'aggiornamento da un layout di switch esistente configurato per ONTAP 9.1 o versione successiva.

.A proposito di questa attività
Questa procedura è senza interruzioni e richiede circa quattro ore per il completamento (esclusi rack e stack) quando i dischi vengono azzerati.



== Invio di un messaggio AutoSupport personalizzato prima della riconfigurazione degli switch

Prima di riconfigurare gli switch, devi inviare un messaggio AutoSupport per informare il supporto tecnico di NetApp che la manutenzione è in corso. Informare il supporto tecnico che la manutenzione è in corso impedisce loro di aprire un caso partendo dal presupposto che si sia verificata un'interruzione.

Questa attività deve essere eseguita su ciascun sito MetroCluster.

.Fasi
. Accedere al cluster.
. Richiamare un messaggio AutoSupport che indica l'inizio della manutenzione:
+
`system node autosupport invoke -node * -type all -message MAINT=__maintenance-window-in-hours__*`

+
intervallo di manutenzione in ore specifica la durata della finestra di manutenzione, con un massimo di 72 ore. Se la manutenzione viene completata prima che sia trascorso il tempo, è possibile richiamare un messaggio AutoSupport che indica la fine del periodo di manutenzione:

+
`system node autosupport invoke -node * -type all -message MAINT=end`

. Ripetere questi passaggi sul sito del partner.




== Verifica dello stato della configurazione MetroCluster

Verificare lo stato della configurazione MetroCluster per verificarne il corretto funzionamento.

.Fasi
. Verificare che i componenti di MetroCluster siano integri:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----
+
L'operazione viene eseguita in background.

. Dopo il `metrocluster check run` operazione completata, eseguire `metrocluster check show` per visualizzare i risultati.
+
Dopo circa cinque minuti, vengono visualizzati i seguenti risultati:

+
[listing]
----
-----------
cluster_A::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
. Per verificare lo stato dell'operazione MetroCluster check in corso, utilizzare il comando:
+
`metrocluster operation history show -job-id 38`

. Verificare che non siano presenti avvisi sullo stato di salute:
+
`system health alert show`





== Verifica degli errori di configurazione di MetroCluster in corso

È possibile utilizzare lo strumento Config Advisor disponibile sul sito del supporto NetApp per verificare la presenza di errori di configurazione comuni.

Config Advisor è uno strumento per la convalida della configurazione e il controllo dello stato di salute. È possibile implementarlo sia in siti sicuri che in siti non sicuri per la raccolta di dati e l'analisi del sistema.


NOTE: Il supporto per Config Advisor è limitato e disponibile solo online.

. Scarica lo strumento Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]

. Eseguire Config Advisor, esaminare l'output e seguire i consigli per risolvere eventuali problemi.




== Disattivazione persistente degli switch

È necessario disattivare gli switch nel fabric in modo persistente per modificarne la configurazione.

Per disattivare gli switch, eseguire i comandi sulla riga di comando dello switch; i comandi utilizzati per questo non sono comandi ONTAP.

.Fasi
. Disattivare in modo persistente lo switch:
+
** Utilizzare il seguente comando per disattivare uno switch Brocade in modo persistente:
+
`FC_switch_A_1:admin> switchCfgPersistentDisable`

** Utilizzare il seguente comando per disattivare uno switch Cisco in modo persistente:
+
`vsan [vsna #] suspend`







== Determinazione del nuovo layout di cablaggio

È necessario determinare il cablaggio dei nuovi moduli controller e dei nuovi shelf di dischi per gli switch FC esistenti.

Questa attività deve essere eseguita in ogni sito MetroCluster.

.Fasi
. Utilizzare https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installazione e configurazione di Fabric-Attached MetroCluster"^] Per determinare il layout del cablaggio per il tipo di switch, utilizzando l'utilizzo della porta per una configurazione MetroCluster a otto nodi.
+
L'utilizzo della porta dello switch FC deve corrispondere all'utilizzo descritto nella guida per poter utilizzare i file di configurazione di riferimento (RCF).

+

NOTE: Non utilizzare questa procedura se il cablaggio non può utilizzare RCF.





== Applicazione dei file RCF e ricablaggio degli switch

È necessario applicare i file di configurazione di riferimento (RCF) appropriati per riconfigurare gli switch in modo da ospitare i nuovi nodi. Dopo aver applicato i file RCF, è possibile recuperare gli switch.

L'utilizzo della porta dello switch FC deve corrispondere all'utilizzo descritto in https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installazione e configurazione di Fabric-Attached MetroCluster"^] In modo da poter utilizzare gli RCF.

.Fasi
. Individuare i file RCF per la configurazione.
+
È necessario utilizzare i file RCF corrispondenti al modello di switch in uso.

. Applicare i file RCF seguendo le istruzioni nella pagina Download e regolando le impostazioni ISL in base alle necessità.
. Verificare che la configurazione dello switch sia stata salvata.
. Collegare entrambi i bridge FC-SAS agli switch FC, utilizzando il layout di cablaggio creato nella sezione "`Ddefinizione del nuovo layout di cablaggio`".
. Verificare che le porte siano in linea:
+
** Per gli switch Brocade, utilizzare `switchshow` comando.
** Per gli switch Cisco, utilizzare `show interface brief` comando.


. Collegare le porte FC-VI dai controller agli switch.
. Dai nodi esistenti, verificare che le porte FC-VI siano in linea:
+
`metrocluster interconnect adapter show`

+
`metrocluster interconnect mirror show`





== Abilitare gli switch in modo persistente

È necessario abilitare gli switch nel fabric in modo persistente.

.Fasi
. Abilitare costantemente lo switch:
+
** Per gli switch Brocade, utilizzare `switchCfgPersistentenable` comando.
** Per gli switch Cisco, utilizzare il comando no `suspend` comando. Il seguente comando abilita costantemente uno switch Brocade:
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentenable
----
+
Il seguente comando abilita uno switch Cisco:

+
[listing]
----
vsan [vsna #]no suspend
----






== Verifica dello switchover, della riparazione e dello switchback

Verificare le operazioni di switchover, riparazione e switchback della configurazione MetroCluster.

. Utilizzare le procedure per lo switchover negoziato, la riparazione e lo switchback descritte in https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_dr_workflow.html["Gestione MetroCluster e disaster recovery"^].

