---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: Potrebbe essere necessario aggiornare un file RCF su uno switch IP MetroCluster. Ad esempio, un aggiornamento ONTAP o un aggiornamento del firmware dello switch richiedono un nuovo file RCF. 
---
= Aggiornare i file RCF sugli switch IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario aggiornare un file RCF (Reference Configuration file) su uno switch IP MetroCluster. Ad esempio, se la versione RCF in esecuzione sugli switch non è supportata dalla versione ONTAP, dalla versione firmware dello switch o da entrambe.

.Prima di iniziare
* Se si sta installando un nuovo firmware dello switch, è necessario installare il firmware dello switch prima di aggiornare il file RCF.
* Prima di aggiornare l'RCF, link:task_upgrade_firmware_on_mcc_ip_switches.html["Verificare che l'RCF sia supportato"].
* link:enable-console-logging-before-maintenance.html["Attivare la registrazione della console"] prima di eseguire questa attività.


.A proposito di questa attività
* Questa procedura interrompe il traffico sullo switch in cui viene aggiornato il file RCF. Il traffico riprende quando viene applicato il nuovo file RCF.
* Eseguire le operazioni su un interruttore alla volta, nell'ordine seguente: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.


.Fasi
. Verificare lo stato della configurazione.
+
.. Verificare che i componenti di MetroCluster siano integri:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
L'operazione viene eseguita in background.

+
.. Dopo il `metrocluster check run` operazione completata, eseguire `metrocluster check show` per visualizzare i risultati.
+
Dopo circa cinque minuti, vengono visualizzati i seguenti risultati:

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Controllare lo stato dell'operazione di controllo MetroCluster in esecuzione:
+
`metrocluster operation history show -job-id 38`

.. Verificare che non siano presenti avvisi sullo stato di salute:
+
`system health alert show`



. Preparare gli switch IP per l'applicazione dei nuovi file RCF.
+
Seguire la procedura per il fornitore dello switch:

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Ripristinare l'interruttore Broadcom IP alle impostazioni predefinite"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Ripristinare lo switch IP Cisco alle impostazioni predefinite"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Ripristinare le impostazioni predefinite dello switch NVIDIA IP SN2100"]


. Scaricare e installare il file RCF IP, a seconda del fornitore dello switch.
+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Scaricare e installare i file Broadcom IP RCF"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Scaricare e installare i file RCF IP di Cisco"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Scaricare e installare i file RCF NVIDIA IP"]
+

NOTE: Se si dispone di una configurazione di rete L2 condivisa o L3, potrebbe essere necessario regolare le porte ISL sugli switch intermedi/clienti. La modalità switchport potrebbe passare dalla modalità 'access' alla modalità 'trunk'. Procedere all'aggiornamento della seconda coppia di switch (A_2, B_2) solo se la connettività di rete tra gli switch A_1 e B_1 è completamente operativa e la rete funziona correttamente.




