---
permalink: maintain/task_online_or_offline_the_mcc_ip_interface.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, online, offline, ip, interface port 
summary: 'Quando si eseguono interventi di manutenzione, potrebbe essere necessario disattivare la porta dell"interfaccia IP di MetroCluster.' 
---
= Porte di interfaccia IP MetroCluster online o offline
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si eseguono attività di manutenzione, potrebbe essere necessario portare una porta di interfaccia IP MetroCluster offline o online.

È possibile utilizzare la seguente procedura per collegare una porta di interfaccia IP di MetroCluster in modalità non in linea o in linea.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato).
+
[source, cli]
----
set -privilege advanced
----
+
*Esempio di output*

+
[listing]
----
Cluster A_1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. Portare la porta di interfaccia IP MetroCluster offline.
+
[source, cli]
----
system ha interconnect link off -node <node_name> -link <link_num, 0 or 1>
----
+
*Esempio di output*

+
[listing]
----
Cluster_A1::*> system ha interconnect link off -node node-a1 -link 0
----
+
.. Verificare che l'interfaccia IP MetroCluster non sia in linea.
+
[source, cli]
----
Cluster_A1::*> system ha interconnect port show
----
+
*Esempio di output*

+
[listing]
----
Cluster_A1::*> system ha interconnect port show
                               Physical  Link
                Link           Layer     Layer      Physical   Physical  Active
Node            Monitor  Port  State     State       Link Up  Link Down  Link
--------------  -------  ----  --------  ---------  --------  ---------  ------
node-a1        off
                            0  disabled  down              4          3  false
                            1  linkup    active            4          2  true
node-a2        off
                            0  linkup    active            4          2  true
                            1  linkup    active            4          2  true
2 entries were displayed.
----


. Portare online la porta di interfaccia IP MetroCluster.
+
[source, cli]
----
system ha interconnect link on -node <node_name> -link <link_num, 0 or 1>
----
+
*Esempio di output*

+
[listing]
----
Cluster_A1::*> system ha interconnect link on -node node-a1 -link 0
----
+
.. Verificare che la porta di interfaccia IP MetroCluster sia in linea.
+
[source, cli]
----
Cluster_A1::*> system ha interconnect port show
----
+
*Esempio di output*

+
[listing]
----
Cluster_A1::*> system ha interconnect port show
                               Physical  Link
                Link           Layer     Layer      Physical   Physical  Active
Node            Monitor  Port  State     State       Link Up  Link Down  Link
--------------  -------  ----  --------  ---------  --------  ---------  ------
node-a1        off
                            0  linkup    active            5          3  true
                            1  linkup    active            4          2  true
node-a2        off
                            0  linkup    active            4          2  true
                            1  linkup    active            4          2  true
2 entries were displayed.
----



