---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: Aggiornamento del firmware sugli switch IP MetroCluster. 
---
= Aggiornare il firmware sugli switch IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario aggiornare il firmware su uno switch IP MetroCluster.



== Verificare che l'RCF sia supportato

Quando si modifica la versione di ONTAP o la versione del firmware dello switch, è necessario verificare di disporre di un file di configurazione di riferimento (RCF) supportato per tale versione. Se si utilizza link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"^]lo strumento, viene generato l'RCF corretto per la configurazione.

.Fasi
. Per verificare la versione dell'RCF, utilizzare i seguenti comandi delle opzioni:
+
[cols="30,70"]
|===


| Da questo switch... | Eseguire questo comando... 


 a| 
Switch Broadcom
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Switch Cisco
 a| 
`IP_switch_A_1# show banner motd`



 a| 
Interruttore NVIDIA SN2100
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
Individuare la riga nell'output del comando che indica la versione RCF. Ad esempio, la seguente uscita da un interruttore Cisco indica che la versione RCF è "`v1,80'".

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. Per verificare quali file sono supportati per una specifica versione, switch e piattaforma ONTAP, utilizzare link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator per MetroCluster IP"^]. Se è possibile generare l'RCF per la configurazione in uso o a cui si desidera eseguire l'aggiornamento, l'RCF è supportato.
. Per verificare che il firmware dello switch sia supportato, fare riferimento a quanto segue:
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["Matrice di interoperabilità NetApp"^]






== Aggiornare il firmware dello switch

.A proposito di questa attività
È necessario ripetere questa attività su ciascuno switch in successione.

link:enable-console-logging-before-maintenance.html["Attivare la registrazione della console"] prima di eseguire questa attività.

[[step_1_fw_upgrade]]
.Fasi
. Controllare lo stato della configurazione.
+
.. Verificare che MetroCluster sia configurato e in modalità normale su ciascun cluster:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Verificare che il mirroring sia attivato su ciascun nodo:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Verificare che i componenti di MetroCluster siano in buone condizioni:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
L'operazione viene eseguita in background.

.. Dopo il `metrocluster check run` l'operazione è completata, eseguire:
+
`metrocluster check show`

+
Dopo circa cinque minuti, vengono visualizzati i seguenti risultati:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Verificare che non siano presenti avvisi sullo stato di salute:
+
`system health alert show`



. Installare il software sul primo switch.
+

NOTE: È necessario installare il software dello switch sugli switch nel seguente ordine: Switch_A_1, switch_B_1, switch_A_2, switch_B_2.

+
Seguire la procedura per l'installazione del software switch nell'argomento pertinente, a seconda che il tipo di switch sia Broadcom, Cisco o NVIDIA:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Scaricare e installare il software Broadcom switch EFOS"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Scaricare e installare il software Cisco switch NX-OS"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Scaricare e installare il software Cumulus switch NVIDIA SN2100"]


. Ripetere il passaggio precedente per ciascuno degli switch.
. Ripetere <<step_1_fw_upgrade,Fase 1>> per controllare lo stato di salute della configurazione.

