---
permalink: maintain/task_change_speed_of_isl_ports_on_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, speed, isl, ports, cisco, fc, switch 
summary: 'Potrebbe essere necessario modificare la velocità delle porte ISL su uno switch per migliorare la qualità dell"ISL. Gli ISL che viaggiano su distanze maggiori potrebbero aver bisogno di una riduzione della velocità per migliorare la qualità.' 
---
= Modifica della velocità delle porte ISL su uno switch FC Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario modificare la velocità delle porte ISL su uno switch per migliorare la qualità dell'ISL. Gli ISL che viaggiano su distanze maggiori potrebbero aver bisogno di una riduzione della velocità per migliorare la qualità.

Per garantire la connettività ISL, è necessario completare tutti i passaggi su entrambi gli switch.

. Disattivare le porte ISL degli ISL che si desidera modificare in base alla velocità di su entrambi gli switch del fabric:
+
`*FC_switch_A_1# config t*`

+
Immettere i comandi di configurazione, uno per riga. Terminare con CTRL-Z dopo aver immesso tutti i comandi di configurazione.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. Modificare la velocità delle porte ISL su entrambi gli switch del fabric:
+
`*FC_switch_A_1# config t*`

+
Immettere i comandi di configurazione, uno per riga. Terminare con CTRL-Z dopo aver immesso tutti i comandi di configurazione.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+

NOTE: Le velocità delle porte sono 16 = 16,000 Gbps, 8 = 8,000 Gbps, 4 = 4,000 Gbps.

+
Assicurarsi che queste porte ISL per lo switch siano elencate nella _Guida all'installazione e alla configurazione di Fabric-Attached MetroCluster_.

. Abilitare tutte le porte ISL (se non attivate) su entrambi gli switch del fabric:
+
`*FC_switch_A_1# config t*`

+
Immettere i comandi di configurazione, uno per riga. Terminare con CTRL-Z dopo aver immesso tutti i comandi di configurazione.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. Verificare che gli ISL siano stati stabiliti tra entrambi gli switch:
+
`*show topology isl*`

+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----
. Ripetere la procedura per il secondo fabric dello switch.

