---
permalink: install-stretch/concept_deciding_whether_to_use_this_guide_stretch_mcc_installation_and_configuration_guide.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, stretch, configuration, decide 
summary: 'Queste informazioni descrivono come installare e configurare i componenti hardware e software di MetroCluster in una configurazione stretch (a volte chiamata configurazione SAS Optical MetroCluster).' 
---
= Estensione dell'installazione e della configurazione di MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste informazioni descrivono come installare e configurare i componenti hardware e software di MetroCluster in una configurazione stretch (a volte chiamata configurazione SAS Optical MetroCluster).

Utilizzare queste informazioni per la pianificazione, l'installazione e la configurazione di una configurazione di Stretch MetroCluster nei seguenti casi:

* Si desidera comprendere l'architettura di una configurazione Stretch MetroCluster.
* Si desidera comprendere i requisiti e le Best practice per la configurazione di una configurazione Stretch MetroCluster.
* Si desidera utilizzare l'interfaccia della riga di comando (CLI), non uno strumento di scripting automatico.

