---
permalink: install-stretch/reference_information_gathering_worksheet_for_fc_to_sas_bridges_2_node_atto.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, worksheet, fc, sas, bridges, information 
summary: Prima di iniziare a configurare i siti MetroCluster, è necessario raccogliere le informazioni di configurazione richieste. 
---
= Scheda di raccolta informazioni per ponti FC-SAS stretch MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di iniziare a configurare i siti MetroCluster, è necessario raccogliere le informazioni di configurazione richieste.



[[site-a-fc-to-sas-bridge-1-fcbridgea1a]]
== Sito A, bridge FC-SAS 1 (FC_bridge_A_1a)

Ogni stack SAS richiede almeno due bridge FC-SAS.

Ciascun bridge si connette a Controller_A_1_``__port-number__`` E Controller_B_1_``__port-number__``.

|===


| Sito A | Il tuo valore 


 a| 
Indirizzo IP Bridge_A_1a
 a| 



 a| 
Nome utente Bridge_A_1a
 a| 



 a| 
Password Bridge_A_1a
 a| 

|===


[[site-a-fc-to-sas-bridge-2-fcbridgea1b]]
== Sito A, bridge FC-SAS 2 (FC_bridge_A_1b)

Ogni stack SAS richiede almeno due bridge FC-SAS.

Ciascun bridge si connette a Controller_A_1_``__port-number__`` E Controller_B_1_``__port-number__``.

|===


| Sito A | Il tuo valore 


 a| 
Indirizzo IP Bridge_A_1b
 a| 



 a| 
Nome utente Bridge_A_1b
 a| 



 a| 
Password Bridge_A_1b
 a| 

|===


[[site-b-fc-to-sas-bridge-1-fcbridgeb1a]]
== Sito B, bridge FC-SAS 1 (FC_bridge_B_1a)

Ogni stack SAS richiede almeno due bridge FC-SAS.

Ciascun bridge si connette a Controller_A_1_`__Port-Number__` e Controller_B_1_`__Port-Number__`.

|===


| Sito B | Il tuo valore 


 a| 
Indirizzo IP Bridge_B_1a
 a| 



 a| 
Nome utente Bridge_B_1a
 a| 



 a| 
Password Bridge_B_1a
 a| 

|===


[[site-b-fc-to-sas-bridge-2-fcbridgeb1b]]
== Sito B, bridge FC-SAS 2 (FC_bridge_B_1b)

Ogni stack SAS richiede almeno due bridge FC-SAS.

Ciascun bridge si connette a Controller_A_1_`__Port-Number__` e Controller_B_1_`__Port-Number__`.

|===


| Sito B | Il tuo valore 


 a| 
Indirizzo IP Bridge_B_1b
 a| 



 a| 
Nome utente Bridge_B_1b
 a| 



 a| 
Password Bridge_B_1b
 a| 

|===