---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html 
sidebar: sidebar 
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, additional, information, miscellaneous, guide 
summary: Ulteriori informazioni sulla configurazione e sul funzionamento di MetroCluster sono disponibili nella documentazione completa di NetApp. 
---
= Dove trovare ulteriori informazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri di più sulla configurazione e sul funzionamento di MetroCluster.



== MetroCluster e informazioni varie

|===


| Informazioni | Soggetto 


 a| 
link:../index.html["Documentazione MetroCluster"]
 a| 
* Tutte le informazioni MetroCluster




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["Report tecnico NetApp 4375: NetApp MetroCluster per ONTAP 9.3"^]
 a| 
* Panoramica tecnica della configurazione e del funzionamento di MetroCluster.
* Best practice per la configurazione di MetroCluster.




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html["Installazione e configurazione di Fabric-Attached MetroCluster"]
 a| 
* Architettura Fabric-Attached MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione degli switch FC
* Configurazione di MetroCluster in ONTAP




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html["Estensione dell'installazione e della configurazione di MetroCluster"]
 a| 
* Estendi l'architettura MetroCluster
* Cablaggio della configurazione
* Configurazione dei bridge FC-SAS
* Configurazione di MetroCluster in ONTAP




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html["Installazione e configurazione di MetroCluster IP"]
 a| 
* Architettura IP di MetroCluster
* Cablaggio della configurazione
* Configurazione di MetroCluster in ONTAP




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installazione e configurazione del software MetroCluster Tiebreaker 1.21"]
 a| 
* Monitoraggio della configurazione MetroCluster con il software MetroCluster Tiebreaker




 a| 
Documentazione Active IQ Unified Manager https://www.netapp.com/support-and-training/documentation/["Documentazione NetApp: Guide e risorse sui prodotti"^]
 a| 
* Monitoraggio della configurazione e delle prestazioni di MetroCluster




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transizione basata sulla copia"]
 a| 
* Transizione dei dati dai sistemi storage 7-Mode ai sistemi storage in cluster


|===