---
permalink: manage/task_send_a_custom_autosupport_message_prior_to_negotiated_switchover.html 
sidebar: sidebar 
keywords: perform, negotiate, switchover, autosupport, message, netapp, technical, support, maintenance, underway, failure, trigger, support, prevent, disruption, custom, prior 
summary: 'Prima di eseguire uno switchover negoziato, devi inviare un messaggio AutoSupport per informare il supporto tecnico NetApp che la manutenzione è in corso. Lo switchover negoziato potrebbe causare errori operativi plex o MetroCluster che attivano i messaggi AutoSupport. Informare il supporto tecnico che la manutenzione è in corso impedisce loro di aprire un caso partendo dal presupposto che si sia verificata un"interruzione.' 
---
= Invio di un messaggio AutoSupport personalizzato prima dello switchover negoziato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire uno switchover negoziato, devi inviare un messaggio AutoSupport per informare il supporto tecnico NetApp che la manutenzione è in corso. Lo switchover negoziato potrebbe causare errori operativi plex o MetroCluster che attivano i messaggi AutoSupport. Informare il supporto tecnico che la manutenzione è in corso impedisce loro di aprire un caso partendo dal presupposto che si sia verificata un'interruzione.

Questa attività deve essere eseguita su ciascun sito MetroCluster.

.Fasi
. Accedere al cluster dal sito_A.
. Richiamare un messaggio AutoSupport che indica l'inizio della manutenzione: `system node autosupport invoke -node * -type all -message MAINT=maintenance-window-in-hours`
+
intervallo di manutenzione in ore specifica la durata della finestra di manutenzione e può essere di un massimo di 72 ore. Se la manutenzione viene completata prima che sia trascorso il tempo, è possibile inviare un comando a per indicare che il periodo di manutenzione è terminato:``system node autosupport invoke -node * -type all -message MAINT=end``

. Ripetere questo passaggio sul sito del partner.

